'use strict';

const fs = require('node:fs'); const path = require('node:path'); const { execFileSync, spawnSync } = require('node:child_process');
const { pathsOverlap, validateChecks } = require('../plans/format'); const { atomicWrite } = require('../core/plans');

class ExecutionGit {
  constructor(root, { git = execFileSync, io = fs } = {}) { this.root = path.resolve(root); this.gitCommand = git; this.io = io; }
  git(args, cwd = this.root, options = {}) { return `${this.gitCommand('git', args, { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], ...options })}`.trim(); }
  baseline(reference = 'HEAD', repository = this.root) { return this.git(['rev-parse', reference], repository); }
  target(repository = this.root) { const branch = this.git(['branch', '--show-current'], repository); const head = this.baseline('HEAD', repository); this.assertTarget(branch, head, repository); return { branch, head }; }
  assertTarget(expectedBranch, expectedHead, repository = this.root) { const branch = this.git(['branch', '--show-current'], repository); const head = this.baseline('HEAD', repository); const dirty = this.git(['status', '--porcelain=v1', '--untracked-files=all'], repository).split('\n').filter((line) => line && !line.slice(3).startsWith('.bdfl/')).join('\n'); if (branch !== expectedBranch || head !== expectedHead || dirty) { const error = new Error('Original target changed or is dirty; final integration stopped'); error.code = 'TARGET_CHANGED'; throw error; } }
  createWorker(executionId, chunkId, attempt, base, repository = this.root) { const safe = `${executionId}-${chunkId}-${attempt}`.replace(/[^a-zA-Z0-9._-]/g, '-'); const branch = `bdfl/${safe}`; const worktree = path.join(repository, '.bdfl', 'worktrees', 'workers', safe); this.io.mkdirSync(path.dirname(worktree), { recursive: true }); const commit = this.baseline(base, repository); this.git(['worktree', 'add', '-b', branch, worktree, commit], repository); return { branch, worktree, base: commit }; }
  checkpoint(worktree, message) { this.git(['add', '-A'], worktree); if (this.git(['diff', '--cached', '--name-only'], worktree)) this.git(['commit', '-m', message], worktree); return this.git(['rev-parse', 'HEAD'], worktree); }
  changed(base, head, cwd = this.root) { const output = this.git(['diff', '--name-only', '--diff-filter=ACMRTUXB', `${base}..${head}`], cwd); return output ? output.split('\n') : []; }
  patch(base, head, cwd = this.root) { return this.git(['diff', '--no-ext-diff', `${base}..${head}`], cwd); }
  runChecks(checks, cwd) { const results = []; for (const command of validateChecks(checks)) { const result = spawnSync(command[0], command.slice(1), { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }); results.push({ command, ok: result.status === 0, output: `${result.stdout || result.stderr || ''}`.slice(0, 4000) }); if (result.status !== 0) break; } return results; }
  verifyResult({ base, head, ownedPaths, checks = [], worktree }) { const changedPaths = this.changed(base, head, worktree); const violations = changedPaths.filter((file) => !ownedPaths.some((owned) => pathsOverlap(file, owned))); if (violations.length) throw new Error(`Worker changed paths outside ownership: ${violations.join(', ')}`); const results = this.runChecks(checks, worktree); return { state: results.some((result) => !result.ok) ? 'fail' : 'pass', commit: head, changedPaths, checks: results, diff: this.patch(base, head, worktree) }; }
  resultCommit(chunk, repository = this.root) { const head = chunk.commit; const base = chunk.attempts?.at(-1)?.base; if (!head) throw new Error(`Worker result has no commit: ${chunk.id}`); if (!base) return head; const tree = this.git(['rev-parse', `${head}^{tree}`], repository); const baseTree = this.git(['rev-parse', `${base}^{tree}`], repository); if (tree === baseTree) return null; return this.git(['commit-tree', tree, '-p', base, '-m', `BDFL result ${chunk.id}`], repository); }
  discardGeneratedWorktree(branch, worktree, repository = this.root) { let exists = this.io.existsSync(worktree); try { this.git(['rev-parse', '--verify', branch], repository); exists = true; } catch {} if (!exists) return; try { this.git(['worktree', 'remove', '--force', worktree], repository); } catch {} this.git(['worktree', 'prune'], repository); try { this.git(['branch', '-D', branch], repository); } catch {} if (this.io.existsSync(worktree)) throw new Error(`Unable to reset generated worktree: ${worktree}`); }
  composeBase(executionId, chunkId, attempt, baseline, chunks, repository = this.root) { const safe = `${executionId}-${chunkId}-${attempt}`.replace(/[^a-zA-Z0-9._-]/g, '-'); const branch = `bdfl/base-${safe}`; const worktree = path.join(repository, '.bdfl', 'worktrees', 'bases', safe); this.discardGeneratedWorktree(branch, worktree, repository); this.io.mkdirSync(path.dirname(worktree), { recursive: true }); this.git(['worktree', 'add', '-b', branch, worktree, baseline], repository); for (const chunk of chunks) { const commit = this.resultCommit(chunk, repository); if (commit) this.git(['cherry-pick', commit], worktree); } return this.git(['rev-parse', 'HEAD'], worktree); }
  createIntegration(executionId, base, repository = this.root) { const safe = executionId.replace(/[^a-zA-Z0-9._-]/g, '-'); const branch = `bdfl/integration-${safe}`; const worktree = path.join(repository, '.bdfl', 'worktrees', 'integration', safe); this.io.mkdirSync(path.dirname(worktree), { recursive: true }); this.git(['worktree', 'add', '-b', branch, worktree, base], repository); return { branch, worktree, base }; }
  consolidate(integration, chunks) { const ordered = [...chunks].sort((left, right) => left.order - right.order); for (const chunk of ordered) { try { const commit = this.resultCommit(chunk, integration.worktree); if (commit) this.git(['cherry-pick', commit], integration.worktree); } catch (error) { return { state: 'conflict', chunkIds: ordered.slice(0, ordered.indexOf(chunk) + 1).map((item) => item.id), pendingChunkIds: ordered.slice(ordered.indexOf(chunk) + 1).map((item) => item.id), message: `${error.stderr || error.message}`.slice(0, 800) }; } } return { state: 'pass', head: this.git(['rev-parse', 'HEAD'], integration.worktree), changedPaths: this.changed(integration.base, 'HEAD', integration.worktree) }; }
  verifierContext(execution, integration, lineage) { const directory = path.join(execution.repositoryRoot || this.root, '.bdfl', 'workers', execution.id, 'verifier', 'context'); this.io.mkdirSync(path.join(directory, 'chunks'), { recursive: true }); atomicWrite(path.join(directory, 'shared.md'), lineage.readSection(execution.planId, execution.version, 'shared')); for (const chunk of execution.chunks) atomicWrite(path.join(directory, 'chunks', `${chunk.id}.md`), lineage.readSection(execution.planId, execution.version, chunk.id)); atomicWrite(path.join(directory, 'global-validation.md'), lineage.readSection(execution.planId, execution.version, 'global-validation')); atomicWrite(path.join(directory, 'diff.patch'), this.git(['diff', '--no-ext-diff', `${integration.base}..HEAD`], integration.worktree)); atomicWrite(path.join(directory, 'checks.json'), `${JSON.stringify({ chunks: execution.chunks.map(({ id, checks, checkResults }) => ({ id, approved: checks, results: checkResults || [] })), global: { approved: execution.globalValidation.checks || [], results: integration.checkResults || [] } }, null, 2)}\n`); return directory; }
  integrate(integration, { targetBranch, targetHead, message, repository = this.root }) { this.assertTarget(targetBranch, targetHead, repository); const tree = this.git(['rev-parse', `${integration.branch}^{tree}`], integration.worktree); const commit = this.git(['commit-tree', tree, '-p', targetHead, '-m', message], repository); this.git(['merge', '--ff-only', commit], repository); return commit; }
}

module.exports = { ExecutionGit };
