'use strict';

class IntegrationCoordinator {
  constructor({ scheduler, git, lineage, verifierLauncher, now = () => new Date() }) { this.scheduler = scheduler; this.git = git; this.lineage = lineage; this.verifierLauncher = verifierLauncher; this.now = now; }
  prepare(executionId) { const execution = this.scheduler.load(executionId); if (execution.chunks.some((chunk) => chunk.status !== 'accepted')) throw new Error('All chunks must be accepted before consolidation'); const integration = this.git.createIntegration(executionId, execution.baseline); const result = this.git.consolidate(integration, execution.chunks); if (result.state === 'conflict') return { ...result, requiresIntegrationWorker: true, integration }; const context = this.git.verifierContext(execution, integration, this.lineage); const verifier = this.verifierLauncher?.({ execution, integration, context, readOnly: true, profile: execution.profile }); execution.status = 'verifying'; execution.integration = { ...integration, head: result.head, verifier, context, startedAt: this.now().toISOString() }; this.scheduler.save(execution); return execution.integration; }
  verification(executionId, report) { const execution = this.scheduler.load(executionId); if (execution.status !== 'verifying') throw new Error('Execution is not awaiting global verification'); execution.verification = { state: report.state, summary: `${report.summary || ''}`.slice(0, 800), affectedChunkIds: report.affectedChunkIds || [], completedAt: this.now().toISOString() }; execution.status = report.state === 'pass' ? 'integration-review' : 'verification-failed'; this.scheduler.save(execution); return execution.verification; }
  finalize(executionId, target) { const execution = this.scheduler.load(executionId); if (execution.status !== 'integration-review' || execution.verification?.state !== 'pass') throw new Error('Passing global verification is required before final integration'); const commit = this.git.integrate(execution.integration, { targetBranch: target.branch, targetHead: target.head, message: target.message || `Integrate ${execution.planId}` }); execution.status = 'complete'; execution.finalCommit = commit; execution.completedAt = this.now().toISOString(); this.scheduler.save(execution); return commit; }
}
module.exports = { IntegrationCoordinator };
