'use strict';

const fs = require('node:fs'); const path = require('node:path');
const { WorkspaceStore } = require('../state/workspace'); const { SessionManager } = require('../sessions/manager');
const { LineageStore } = require('../plans/store'); const { WorkerScheduler } = require('../workers/scheduler'); const { IntegrationCoordinator } = require('../workers/integration'); const { ExecutionGit } = require('../worktrees/execution');
const { PlanService, WorkerService, ControlServer } = require('../mcp/bridge');
const { errorDetails, ISSUE_URL } = require('../core/errors');
const { codexRuntime } = require('../providers/adapters');
const { WorkstreamWizard, display } = require('./wizard');

const ESC = '\u001b['; const COLORS = { yellow: `${ESC}38;5;220m`, cyan: `${ESC}38;5;81m`, green: `${ESC}38;5;114m`, red: `${ESC}38;5;203m`, white: `${ESC}38;5;255m`, black: `${ESC}38;5;16m`, bgYellow: `${ESC}48;5;220m`, bgCyan: `${ESC}48;5;81m`, bgGray: `${ESC}48;5;245m`, gray: `${ESC}38;5;245m`, reset: `${ESC}0m`, bold: `${ESC}1m`, underline: `${ESC}4m`, inverse: `${ESC}7m`, dim: `${ESC}2m` };
const ACTIONS = ['New', 'Plans', 'Sessions', 'Review', 'Close', 'Quit'];
const NATIVE_PAGES = new Set(['New', 'Plans', 'Sessions', 'Review']);
const STAR_MESSAGE = 'Tip: Star github.com/thisisnsh/bdfl to show support.';
const QUIT_MESSAGE = 'Press Ctrl+C again to quit.';
const QUIT_CONFIRMATION_TIMEOUT = 5000;
const FOOTER_MESSAGES = [
  'Tip: Press Ctrl+] to toggle focus between agents and BDFL.',
  STAR_MESSAGE,
  'Tip: Use the arrow keys to navigate options in the top and bottom rows.',
  "Tip: In [Plans], approve sections you don't want changed.",
  'Tip: Use [Plans] to view diffs between plan versions.',
  'Tip: Turn off the BDFL MCP server to avoid breaking plans down for delegation.'
];
const FOOTER_FADE_COLORS = [245, 243, 240, 238, 240, 243, 245];
const FOOTER_FADE_MIDPOINT = 3;
const FOOTER_FADE_INTERVAL = 50;
function availableActions(workspace) { const sessions = workspace.sessions || []; const active = workspace.workstreams?.some((stream) => stream.status !== 'closed'); return ACTIONS.filter((action) => action === 'New' || action === 'Quit' || action === 'Sessions' && workspace.workstreams?.length || action === 'Close' && active || action === 'Plans' && (workspace.planCount > 0 || sessions.some((session) => session.role === 'plan' && !session.explicitlyClosed)) || action === 'Review' && (workspace.reviewCount > 0 || sessions.some((session) => session.role === 'review' && !session.explicitlyClosed))); }
function characterWidth(character) { if (/\p{Mark}/u.test(character)) return 0; return /\p{Extended_Pictographic}|\p{Script=Han}|\p{Script=Hangul}|\p{Script=Hiragana}|\p{Script=Katakana}|[\uFF01-\uFF60\uFFE0-\uFFE6]/u.test(character) ? 2 : 1; }
function width(value) { return [...`${value}`.replace(/\u001b\][^\u0007]*(?:\u0007|\u001b\\)/g, '').replace(/\u001b\[[0-9;?]*[A-Za-z]/g, '')].reduce((sum, character) => sum + characterWidth(character), 0); }
function stripStyles(value) { return `${value}`.replace(/\u001b\[[0-9;?]*[A-Za-z]/g, ''); }
function crop(value, columns, ellipsis = false) { if (columns <= 0) return ''; const result = []; let used = 0; const limit = ellipsis && width(value) > columns ? Math.max(0, columns - 1) : columns; for (const character of `${value}`) { const size = characterWidth(character); if (used + size > limit) break; result.push(character); used += size; } return `${result.join('')}${ellipsis && width(value) > columns && columns > 0 ? '…' : ''}`; }
function fit(value, columns) { const result = []; let used = 0; const tokens = `${value}`.match(/\u001b\[[0-9;?]*[A-Za-z]|./gu) || []; for (const token of tokens) { if (token.startsWith('\u001b[')) { result.push(token); continue; } const size = characterWidth(token); if (used + size > columns) break; result.push(token); used += size; } return result.join('') + ' '.repeat(Math.max(0, columns - used)); }
function softWrapLine(value, columns) { const line = `${value}`; if (!line || width(line) <= columns) return [line]; const indent = line.match(/^\s*(?:[-*+]\s+|\d+[.)]\s+|>\s*)?/u)?.[0] || ''; const continuation = ' '.repeat(Math.min(width(indent), Math.max(0, columns - 1))); const words = line.slice(indent.length).split(/(\s+)/u); const lines = []; let current = indent; const push = () => { lines.push(current.trimEnd()); current = continuation; }; for (const word of words) { if (!word) continue; if (/^\s+$/u.test(word)) { if (current && !current.endsWith(' ')) current += ' '; continue; } if (width(current) + width(word) <= columns) { current += word; continue; } if (current.trim()) push(); let remainder = word; while (width(current) + width(remainder) > columns) { const budget = Math.max(1, columns - width(current)); let piece = ''; for (const character of remainder) { if (width(piece) + characterWidth(character) > budget) break; piece += character; } current += piece; remainder = remainder.slice(piece.length); push(); } current += remainder; } if (current.trim() || !lines.length) lines.push(current.trimEnd()); return lines; }
function softWrap(lines, columns) { return lines.flatMap((line) => softWrapLine(line, Math.max(8, columns))); }
function railName(value) { return width(value) <= 16 ? `${value}` : crop(value, 16, true); }
const TOGGLE_KEYS = new Set(['\u001d', '\u001b[93;5u', '\u001b[29;5u']);
function isToggleKey(value) { return TOGGLE_KEYS.has(value); }
function inputTokens(value) { return `${value}`.match(/\u001b\][^\u0007]*(?:\u0007|\u001b\\)|\u001b\[[0-?]*[ -/]*[@-~]|\u001bO.|\u001b.|./gsu) || []; }
function mouseEvent(value) { const match = /^\u001b\[<([0-9]+);([0-9]+);([0-9]+)([Mm])$/.exec(value); if (!match) return null; return { button: Number(match[1]), column: Number(match[2]), row: Number(match[3]), final: match[4] }; }
function isVerticalWheel(mouse) { return mouse?.final === 'M' && (mouse.button & 64) !== 0 && (mouse.button & 3) < 2; }
function sanitizeTerminalTitle(value) { return `${value ?? ''}`.replace(/[\u0000-\u001f\u007f-\u009f]/gu, ''); }
function formatLocalDateTime(value) { if (!value) return ''; const date = new Date(value); return Number.isNaN(date.getTime()) ? '' : date.toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' }); }
function hasOpenAttention(workspace) { const open = new Set((workspace.workstreams || []).filter((stream) => stream.status !== 'closed').map((stream) => stream.id)); return (workspace.sessions || []).some((session) => session.attention && !session.explicitlyClosed && open.has(session.workstreamId)); }
function terminalTitle(name = null, attention = false) { const safe = sanitizeTerminalTitle(name); return `\u001b]2;${attention ? '* ' : ''}bdfl${safe ? ` - ${safe}` : ''}\u0007`; }
function fallbackName(session, stream, workspace) { if (session?.name) return session.name; if (session?.role === 'worker') return `W ${session.roleSequence || Math.max(1, session.paneNumber - 1 || 1)}`; const provider = stream?.delegatorProfile?.provider || session?.profile?.provider || 'agent'; const label = provider === 'claude' ? 'Claude Code' : display(provider); const index = workspace.workstreams.indexOf(stream); const sequence = stream?.providerSequence || workspace.workstreams.slice(0, index + 1).filter((item) => item.delegatorProfile?.provider === provider).length || 1; return `${label} ${sequence}`; }
function agentSessions(workspace, stream) { return (workspace.sessions || []).filter((session) => session.workstreamId === stream.id && !session.explicitlyClosed && (session.role === 'delegator' || session.role === 'worker')).sort((a, b) => (a.paneNumber || 0) - (b.paneNumber || 0)); }
function codedError(code, message) { const error = new Error(message); error.code = code; return error; }
function errorPageLines(error) { const details = errorDetails(error); return [`${COLORS.bold}${COLORS.red}BDFL encountered an error${COLORS.reset}`, '', `${COLORS.bold}Code${COLORS.reset}     ${COLORS.yellow}${details.code}${COLORS.reset}`, `${COLORS.bold}Message${COLORS.reset}  ${details.message}`, '', `${COLORS.gray}Please open an issue and include the code and message:${COLORS.reset}`, `${COLORS.cyan}${ISSUE_URL}${COLORS.reset}`]; }

class Navigation {
  constructor(workspace) { this.workspace = workspace; this.rail = 'workstreams'; this.action = 0; this.workstream = 0; this.pane = 0; this.workstreamId = workspace.activeWorkstreamId || null; this.sessionId = null; this.activeAction = null; this.sync(workspace); }
  streams() { return (this.workspace.workstreams || []).filter((stream) => stream.status !== 'closed'); }
  agents() { return this.streams().flatMap((stream) => agentSessions(this.workspace, stream).map((session) => ({ stream, session }))); }
  sync(workspace) {
    this.workspace = workspace; const agents = this.agents(); let index = agents.findIndex(({ session }) => session.id === this.sessionId);
    if (index < 0) { index = agents.findIndex(({ stream, session }) => stream.id === this.workstreamId && session.role === 'delegator'); if (index < 0) index = agents.findIndex(({ stream }) => stream.id === workspace.activeWorkstreamId); if (index < 0) index = 0; }
    const selected = agents[index]; this.sessionId = selected?.session.id || null; this.workstreamId = selected?.stream.id || null; this.workstream = Math.max(0, this.streams().findIndex((stream) => stream.id === this.workstreamId)); const panes = this.panes(); this.pane = Math.max(0, panes.findIndex((session) => session.id === this.sessionId)); this.action = Math.min(this.action, Math.max(0, this.actions().length - 1)); return this;
  }
  currentAgent() { return this.agents().find(({ session }) => session.id === this.sessionId) || null; }
  currentStream() { return this.currentAgent()?.stream || this.streams().find((stream) => stream.id === this.workstreamId); }
  panes() { return this.currentStream() ? agentSessions(this.workspace, this.currentStream()) : []; }
  actions() { return availableActions(this.workspace).filter((action) => action !== 'Close' || !this.activeAction); }
  selectedAction() { return this.actions()[this.action]; }
  selectSession(id) { this.sessionId = id; return this.sync(this.workspace); }
  key(name) {
    if (this.rail === 'workstreams') {
      const agents = this.agents(); const current = Math.max(0, agents.findIndex(({ session }) => session.id === this.sessionId));
      if ((name === 'right' || name === 'left') && agents.length) { const delta = name === 'right' ? 1 : -1; const selected = agents[(current + agents.length + delta) % agents.length]; this.sessionId = selected.session.id; this.workstreamId = selected.stream.id; this.sync(this.workspace); }
      else if (name === 'up') this.rail = 'actions';
    } else if (this.rail === 'actions') {
      if (name === 'left' && this.actions().length) this.action = (this.action + this.actions().length - 1) % this.actions().length;
      else if (name === 'right' && this.actions().length) this.action = (this.action + 1) % this.actions().length;
      else if (name === 'down') this.rail = 'workstreams';
    }
    return { rail: this.rail, action: this.selectedAction(), workstream: this.currentStream(), pane: this.currentAgent()?.session };
  }
}

class TerminalRenderer {
  constructor({ version = '0.1.0', reducedMotion = false } = {}) { this.version = version; this.reducedMotion = reducedMotion; }
  railItems(workspace, navigation) { let previousStream = null; return navigation.agents().map(({ stream, session }) => { const planning = session.role === 'delegator'; const prefix = planning ? previousStream === null ? '' : ' ' : '-'; previousStream = stream.id; const text = `${railName(fallbackName(session, stream, workspace))}${session.attention ? '*' : ''}`; return { session, prefix, open: planning ? '[' : '(', close: planning ? ']' : ')', plain: `${prefix}${planning ? '[' : '('}${text}${planning ? ']' : ')'}`, text }; }); }
  visibleRail(items, selectedId, budget) { if (!items.length) return []; const selected = Math.max(0, items.findIndex((item) => item.session.id === selectedId)); if (width(items[selected].plain) > budget) { const item = items[selected]; const fixed = width(`${item.prefix}${item.open}${item.close}${item.session.attention ? '*' : ''}`); const name = crop(item.text.replace(/\*$/, ''), Math.max(1, budget - fixed), true); return [{ ...item, text: `${name}${item.session.attention ? '*' : ''}`, plain: `${item.prefix}${item.open}${name}${item.session.attention ? '*' : ''}${item.close}` }]; } let start = selected; let end = selected + 1; let used = width(items[selected].plain); let changed = true; while (changed) { changed = false; if (start > 0 && used + width(items[start - 1].plain) <= budget) { start -= 1; used += width(items[start].plain); changed = true; } if (end < items.length && used + width(items[end].plain) <= budget) { used += width(items[end].plain); end += 1; changed = true; } } return items.slice(start, end); }
  footer(workspace, navigation, columns, message, messageColor = null, messageAlign = 'right', messageBright = false) { const available = Math.max(1, columns - 4); const selected = navigation.currentAgent(); const leftFull = selected?.session.taskSnippet ? `Last Prompt: ${selected.session.taskSnippet}` : ''; const right = `${message || FOOTER_MESSAGES[0]}`; const style = `${messageBright ? `${ESC}22m${COLORS.bold}` : ''}${messageColor === null ? '' : `${ESC}38;5;${messageColor}m`}`; if (messageAlign === 'left') return `${COLORS.dim}  ${style}${crop(right, available, width(right) > available).padEnd(available)}  ${COLORS.reset}`; const styledRight = `${style}${right}${messageColor === null && !messageBright ? '' : `${COLORS.reset}${COLORS.dim}`}`; if (width(right) > available) return `${COLORS.dim}  ${style}${crop(right, available, true).padEnd(available)}  ${COLORS.reset}`; const allowance = Math.max(0, available - width(right) - (leftFull ? 1 : 0)); const left = allowance ? crop(leftFull, allowance, width(leftFull) > allowance) : ''; const gap = ' '.repeat(Math.max(left ? 1 : 0, available - width(left) - width(right))); return `${COLORS.dim}  ${left}${gap}${styledRight}  ${COLORS.reset}`; }
  render(workspace, navigation, { columns = 100, rows = 28, content = [], footerMessage = FOOTER_MESSAGES[0], footerColor = null, footerAlign = 'right', footerBright = false } = {}) {
    const providerFocused = navigation.rail === 'content' && !navigation.activeAction; const chromeFocused = !providerFocused; const color = chromeFocused ? COLORS.yellow : COLORS.gray; const inner = Math.max(1, columns - 2); const topLabel = ` bdfl ${this.version} `; const visibleActions = navigation.actions(); const plainActions = visibleActions.map((action) => `[${action}]`).join(' '); const topFill = inner - width(topLabel) - width(plainActions) - 2;
    let headerBody; if (topFill < 0) headerBody = `${fit(`─${topLabel}`, inner - 1)}─`; else { const actions = visibleActions.map((action, index) => { const active = navigation.activeAction === action; const hovered = navigation.rail === 'actions' && navigation.action === index; return active || hovered ? `${COLORS.bgYellow}${COLORS.black}${COLORS.bold}[${action}]${COLORS.reset}${color}` : `[${action}]`; }).join(' '); headerBody = `─${topLabel}${'─'.repeat(topFill)}${actions}─`; }
    const agentSession = !navigation.activeAction && navigation.currentAgent(); const lines = [`${color}┌${headerBody}┐${COLORS.reset}`]; const contentRows = Math.max(1, rows - 3 - (agentSession ? 1 : 0));
    const dimAgent = chromeFocused && !navigation.activeAction && navigation.currentAgent();
    for (let row = 0; row < contentRows; row += 1) { const contentLine = row === 0 ? '' : content[row - 1] || ''; const displayed = dimAgent ? `${COLORS.gray}${stripStyles(contentLine)}${COLORS.reset}` : contentLine; lines.push(`${color}│${COLORS.reset}${fit(`  ${displayed}`, inner)}${color}│${COLORS.reset}`); }
    if (agentSession) lines.push(`${color}│${COLORS.reset}${' '.repeat(inner)}${color}│${COLORS.reset}`);
    const visible = this.visibleRail(this.railItems(workspace, navigation), navigation.sessionId, inner - 1); const labels = visible.map((item) => { const badge = `${item.open}${item.text}${item.close}`; const selected = item.session.id === navigation.sessionId; if (navigation.activeAction) return `${COLORS.gray}${item.prefix}${badge}${COLORS.reset}${color}`; if (providerFocused) return selected ? `${COLORS.gray}${item.prefix}${COLORS.bgGray}${COLORS.black}${COLORS.bold}${badge}${COLORS.reset}${color}` : `${COLORS.gray}${item.prefix}${badge}${COLORS.reset}${color}`; return selected ? `${COLORS.yellow}${item.prefix}${COLORS.bgYellow}${COLORS.black}${COLORS.bold}${badge}${COLORS.reset}${color}` : `${COLORS.yellow}${item.prefix}${badge}${COLORS.reset}${color}`; }); const rail = `─${labels.join('')}`; const bottomBody = width(rail) <= inner ? `${rail}${'─'.repeat(inner - width(rail))}` : fit(rail, inner);
    lines.push(`${color}└${bottomBody}┘${COLORS.reset}`); lines.push(this.footer(workspace, navigation, columns, footerMessage, footerColor, footerAlign, footerBright)); return lines.join('\n');
  }
}

class TerminalSupervisor {
  constructor(root, { input = process.stdin, output = process.stdout, store = new WorkspaceStore(root), sessions, lineage, git, scheduler, integration, bridge, version = '0.1.0', setInterval: startInterval = global.setInterval, clearInterval: stopInterval = global.clearInterval, setTimeout: scheduleTimeout = global.setTimeout, clearTimeout: cancelTimeout = global.clearTimeout } = {}) {
    this.root = path.resolve(root); this.input = input; this.output = output; this.store = store; this.lineage = lineage || new LineageStore(root); this.git = git || new ExecutionGit(root);
    this.scheduler = scheduler || new WorkerScheduler(root, { store, lineage: this.lineage, worktrees: this.git, launcher: (value) => this.launchWorker(value), validator: (value) => this.validateWorker(value) });
    this.integration = integration || new IntegrationCoordinator({ scheduler: this.scheduler, git: this.git, lineage: this.lineage, verifierLauncher: (value) => this.launchVerifier(value), integrationLauncher: (value) => this.launchIntegrationWorker(value) });
    if (!scheduler) this.scheduler.onAllAccepted = (executionId) => this.integration.prepare(executionId);
    this.workerService = new WorkerService({ scheduler: this.scheduler, integration: this.integration, sender: (executionId, chunkId, message) => this.sendWorker(executionId, chunkId, message) }); this.bridge = bridge || new ControlServer({ planService: new PlanService(this.lineage), workerService: this.workerService });
    this.sessions = sessions || new SessionManager(root, store, { bridge: this.bridge, requireBridge: true }); this.sessions.onOutput = (sessionId, event) => { if (!event?.scroll || !this.drawScroll(sessionId, event.scroll)) this.scheduleDraw(); }; this.sessions.onAttention = (sessionId) => this.raiseAttention(sessionId); this.sessions.onBridgeError = (_sessionId, error) => { this.error = codedError('BRIDGE_RECOVERY_FAILED', error.message); this.scheduleDraw(); }; this.renderer = new TerminalRenderer({ version, reducedMotion: process.env.NO_COLOR === '1' }); this.lockFile = path.join(root, '.bdfl', 'run', 'supervisor.lock'); this.frame = 0; this.footerIndex = 0; this.footerTransition = null; this.footerAnimationTimer = undefined; this.quitPending = false; this.quitTimer = undefined; this.startInterval = startInterval; this.stopInterval = stopInterval; this.scheduleTimeout = scheduleTimeout; this.cancelTimeout = cancelTimeout;
  }
  workerPrompt(execution, chunk, context) { return `You are a BDFL-managed worker for chunk ${chunk.id}. Work only in your isolated worktree and only within the approved paths: ${chunk.paths.join(', ')}. Read the clean context at ${context}. Implement the chunk, run useful checks, then call bdfl_workers complete with a concise summary. Do not create subagents, publish plans, start executions, or integrate branches.`; }
  launchWorker({ execution, chunk, attempt, context, profile, taskSnippet }) { const worktree = this.git.createWorker(execution.id, chunk.id, attempt.number, attempt.base); const session = this.store.createSession(execution.workstreamId, 'worker', profile, { executionId: execution.id, chunkId: chunk.id, worktree: worktree.worktree, taskSnippet, roleInstruction: this.workerPrompt(execution, chunk, context) }); this.sessions.open(session.id, this.dimensions()); return { ...worktree, sessionId: session.id, context }; }
  validateWorker({ execution, chunk, attempt }) { const head = this.git.checkpoint(attempt.worktree, `BDFL ${execution.planId} ${chunk.id}`); return this.git.verifyResult({ base: attempt.base, head, ownedPaths: chunk.paths, checks: chunk.checks || [], worktree: attempt.worktree }); }
  sendWorker(executionId, chunkId, message) { const chunk = this.scheduler.load(executionId).chunks.find((item) => item.id === chunkId); const sessionId = chunk?.attempts.at(-1)?.sessionId; if (!sessionId) throw new Error(`No active worker session for ${chunkId}`); this.sessions.write(sessionId, `${message}\r`); }
  launchVerifier({ execution, integration, context, profile }) { const prompt = `You are the fresh read-only BDFL verifier. Inspect the consolidated diff and approved plan context at ${context}. Do not edit files. Report pass or fail through bdfl_workers complete, naming affected chunk IDs when possible.`; const session = this.store.createSession(execution.workstreamId, 'verifier', profile, { executionId: execution.id, worktree: integration.worktree, taskSnippet: `Verify ${execution.planId}`, roleInstruction: prompt }); this.sessions.open(session.id, this.dimensions()); return { sessionId: session.id }; }
  launchIntegrationWorker({ execution, integration, allowedPaths, profile }) { const prompt = `Resolve only the recorded cherry-pick conflict in ${integration.worktree}. Changes are restricted to: ${allowedPaths.join(', ')}. Do not broaden the implementation. Call bdfl_workers complete when the conflict is repaired.`; const session = this.store.createSession(execution.workstreamId, 'integration', profile, { executionId: execution.id, worktree: integration.worktree, taskSnippet: `Resolve integration for ${execution.planId}`, roleInstruction: prompt }); this.sessions.open(session.id, this.dimensions()); return { sessionId: session.id }; }
  acquire() { fs.mkdirSync(path.dirname(this.lockFile), { recursive: true }); for (let attempt = 0; attempt < 2; attempt += 1) { try { this.lock = fs.openSync(this.lockFile, 'wx', 0o600); fs.writeFileSync(this.lock, `${process.pid}\n`); return; } catch (error) { if (error.code !== 'EEXIST') throw error; let owner; try { owner = Number.parseInt(fs.readFileSync(this.lockFile, 'utf8'), 10); } catch {} let alive = Number.isInteger(owner) && owner > 0; if (alive) { try { process.kill(owner, 0); } catch (probe) { if (probe.code === 'ESRCH') alive = false; } } if (alive || attempt) throw new Error('Another BDFL supervisor owns this workspace'); try { fs.unlinkSync(this.lockFile); } catch (remove) { if (remove.code !== 'ENOENT') throw remove; } } } }
  release() { if (this.lock === undefined) return; fs.closeSync(this.lock); this.lock = undefined; try { fs.unlinkSync(this.lockFile); } catch (error) { if (error.code !== 'ENOENT') throw error; } }
  dimensions() { return { columns: Math.max(20, (this.output.columns || 100) - 4), rows: Math.max(1, (this.output.rows || 28) - 5) }; }
  planItems() { const directory = path.join(this.root, '.bdfl', 'plans'); let entries; try { entries = fs.readdirSync(directory, { withFileTypes: true }); } catch { return []; } return entries.filter((entry) => entry.isDirectory()).flatMap((entry) => { try { return [JSON.parse(fs.readFileSync(path.join(directory, entry.name, 'lineage.json'), 'utf8'))]; } catch { return []; } }).sort((a, b) => `${b.updatedAt}`.localeCompare(`${a.updatedAt}`)); }
  planAgentLines(lineage, prefix = '') { const workspace = this.workspace || this.store.load(); const planning = workspace.sessions.find((session) => session.id === lineage.originSessionId); const stream = workspace.workstreams.find((item) => item.id === lineage.workstreamId); const planningText = planning?.name || 'Unavailable'; const profile = stream?.workerProfile; const workerText = stream && profile ? `${display(profile.provider)}${profile.model ? ` ${profile.model}` : ''}${profile.effort ? ` · ${profile.effort} effort` : ''} · max ${stream.workerCapacity}` : 'Unavailable'; const row = (connector, label, detail) => `${COLORS.gray}${prefix}${connector}${COLORS.reset} ${COLORS.bold}${COLORS.white}${label}${COLORS.reset}${COLORS.gray} · ${detail}${COLORS.reset}`; return [row('├─', 'Planning agent', planningText), row('└─', 'Worker agent', workerText)]; }
  versionExecution(planId, version) { return (this.scheduler.list?.() || []).find((execution) => execution.planId === planId && execution.version === version) || null; }
  reviewItems() { const directory = path.join(this.root, '.bdfl', 'executions'); let entries; try { entries = fs.readdirSync(directory, { withFileTypes: true }); } catch { return []; } return entries.filter((entry) => entry.isDirectory()).flatMap((entry) => { try { const execution = JSON.parse(fs.readFileSync(path.join(directory, entry.name, 'execution.json'), 'utf8')); const chunks = execution.chunks.filter((chunk) => chunk.status === 'review').map((chunk) => ({ ...chunk, kind: 'chunk', executionId: execution.id, planId: execution.planId })); if (['verifying', 'verification-failed', 'integration-review', 'integration-conflict'].includes(execution.status)) chunks.push({ id: 'combined-result', kind: 'final', executionId: execution.id, planId: execution.planId, status: execution.status, summary: execution.verification?.summary, diff: execution.integration?.finalDiff, checks: execution.integration?.checkResults || [], verification: execution.verification }); return chunks; } catch { return []; } }); }
  decorateWorkspace(workspace) { return { ...workspace, planCount: this.planItems().length, reviewCount: this.reviewItems().length }; }
  sessionPickerItems(workspace = this.workspace || this.store.load()) { return workspace.workstreams.map((stream, index) => { const agents = workspace.sessions.filter((session) => session.workstreamId === stream.id); const modifiedAt = [stream.updatedAt, stream.createdAt, ...agents.flatMap((session) => [session.updatedAt, session.createdAt])].filter(Boolean).sort().at(-1) || ''; return { stream, index, modifiedAt }; }).sort((a, b) => b.modifiedAt.localeCompare(a.modifiedAt) || a.index - b.index).map(({ stream }) => stream); }
  sessionPickerRows(workspace = this.workspace || this.store.load()) { return this.sessionPickerItems(workspace).flatMap((stream) => { const sessions = workspace.sessions.filter((session) => session.workstreamId === stream.id && (session.role === 'delegator' || session.role === 'worker')).sort((a, b) => (a.paneNumber || 0) - (b.paneNumber || 0)); const planning = sessions.find((session) => session.role === 'delegator'); if (!planning) return []; return [{ stream, session: planning, header: true }, ...sessions.filter((session) => session.role === 'worker').map((session) => ({ stream, session, header: false }))]; }); }
  syncSessionPicker(rows) { let index = rows.findIndex(({ session }) => session.id === this.sessionPicker.sessionId); if (index < 0) index = Math.min(this.sessionPicker.index || 0, Math.max(0, rows.length - 1)); this.sessionPicker.index = Math.max(0, index); this.sessionPicker.sessionId = rows[index]?.session.id || null; return this.sessionPicker.index; }
  actionPageLines() {
    if (!this.topPage) return null; const plans = this.topPage.action === 'Plans'; const items = plans ? this.planItems() : this.reviewItems();
    if (this.topPage.detail && plans) {
      const detail = this.topPage.detail; const lineage = this.lineage.load(detail.planId); const version = Math.min(detail.version, lineage.currentVersion); const manifest = this.lineage.readManifest(lineage.planId, version); const sections = [manifest.shared, ...manifest.chunks, manifest.globalValidation]; const selected = Math.min(detail.sectionIndex || 0, sections.length - 1); const section = sections[selected]; const approved = manifest.approvals[section.id]?.sectionSha === section.sha; const approvedCount = sections.filter((item) => manifest.approvals[item.id]?.sectionSha === item.sha).length; const latest = version === lineage.currentVersion; const versionLabel = latest ? lineage.currentVersion === 1 ? 'Latest' : `v${version} of ${lineage.currentVersion} · Latest` : `Older version — v${lineage.currentVersion} is latest`; const execution = this.versionExecution(lineage.planId, version); const columns = this.dimensions().columns; let content = [];
      if (detail.reader) content = this.lineage.readSection(lineage.planId, version, section.id).trimEnd().split('\n');
      else if (detail.diff && version > 1) { const before = fs.readFileSync(path.join(this.lineage.versionDirectory(lineage.planId, version - 1), 'consolidated.md'), 'utf8'); const after = fs.readFileSync(path.join(this.lineage.versionDirectory(lineage.planId, version), 'consolidated.md'), 'utf8'); content = require('../core/plans').diffLines(before, after).map((line) => `${line.type === 'addition' ? '+' : line.type === 'removal' ? '-' : ' '} ${line.text}`); }
      else content = sections.map((item, index) => { const status = manifest.approvals[item.id]?.sectionSha === item.sha ? `${COLORS.green}Approved${COLORS.reset}` : 'Needs approval'; const kind = item.id === 'shared' ? 'Shared decisions' : item.id === 'global-validation' ? 'Global validation' : `Worker chunk · ${item.id}`; return `${index === selected ? '›' : ' '} ${kind} · ${status}`; });
      content = softWrap(content, columns); const scrollable = detail.reader || detail.diff; const bodyRows = Math.max(1, this.dimensions().rows - 9); const maxScroll = Math.max(0, content.length - bodyRows); detail.scroll = Math.min(detail.scroll || 0, maxScroll); const visible = scrollable ? content.slice(detail.scroll, detail.scroll + bodyRows) : content; const contextual = approved ? 'a remove approval' : 'a approve'; let actions = detail.reader ? `↑/↓ scroll  •  ${contextual}` : detail.diff ? `↑/↓ scroll  •  ←/→ version  •  d close diff` : `↑/↓ section  •  ←/→ version  •  Enter read  •  ${contextual}`;
      if (!detail.reader && !detail.diff) { if (version > 1) actions += `  •  d diff v${version - 1} → v${version}`; if (execution) actions += `  •  Execution ${execution.status}`; else if (approvedCount === sections.length) actions += `  •  e execute v${version}`; }
      const approvalStatus = approved ? `${COLORS.green}Approved${COLORS.reset}` : `${COLORS.gray}Needs approval${COLORS.reset}`; const summary = detail.reader ? `${COLORS.gray}${versionLabel} · ${selected + 1} of ${sections.length} approval sections · ${COLORS.reset}${approvalStatus}` : `${COLORS.gray}${versionLabel} · ${sections.length} approval sections · ${manifest.chunks.length} implementation worker${manifest.chunks.length === 1 ? '' : 's'} + 1 verifier${COLORS.reset}`; const header = [`${COLORS.yellow}${manifest.title} · v${version} of ${lineage.currentVersion}${COLORS.reset}`, summary, ''];
      if (detail.diff) header.push(`${COLORS.white}Diff v${version - 1} → v${version}${COLORS.reset}`, '');
      if (detail.confirmExecute) return [...header, `${COLORS.red}Execute v${version} even though v${lineage.currentVersion} is newer?${COLORS.reset}`, `${COLORS.cyan}Enter confirms · Esc cancels${COLORS.reset}`];
      const actionLines = softWrapLine(`${actions}  •  Esc back`, columns).map((line) => `${COLORS.cyan}${line}${COLORS.reset}`); return [...header, ...visible, scrollable && maxScroll ? `${COLORS.gray}${detail.scroll + 1}–${Math.min(content.length, detail.scroll + bodyRows)} of ${content.length}${COLORS.reset}` : '', '', ...actionLines];
    }
    if (this.topPage.detail && !plans) {
      const item = items.find((candidate) => candidate.executionId === this.topPage.detail.executionId && candidate.id === this.topPage.detail.id) || items[this.topPage.index]; if (!item) return ['No review item is available.'];
      const checks = item.checkResults || item.checks || []; const lines = [`${COLORS.yellow}${item.id} · ${item.planId}${COLORS.reset}`, `${COLORS.gray}${item.kind === 'final' ? item.status : 'Worker result'}${COLORS.reset}`, '', item.summary || 'No summary supplied.', '', ...(item.diff || 'No diff recorded.').split('\n'), '', ...checks.flatMap((check) => [`${check.ok ? '✓' : '✗'} ${(check.command || []).join(' ')}`, ...(check.output ? [check.output] : [])])];
      if (this.topPage.feedback) lines.push('', `${COLORS.cyan}Feedback: ${this.topPage.feedback.value}${COLORS.reset}`, `${COLORS.cyan}Enter send · Esc cancel${COLORS.reset}`); else if (this.topPage.confirmIntegrate) lines.push('', `${COLORS.red}Integrate this verified result into the frozen target? Enter confirms; Esc cancels.${COLORS.reset}`); else lines.push('', item.kind === 'final' ? `${COLORS.cyan}i integrate (only after pass) · Esc back${COLORS.reset}` : `${COLORS.cyan}a accept · f feedback · Esc back${COLORS.reset}`); return lines;
    }
    const title = plans ? 'Plans' : 'Ready for review'; const description = plans ? 'Browse durable implementation plans created in this workspace.' : 'Worker and combined results waiting for review.'; return [`${COLORS.yellow}${title}${COLORS.reset}`, `${COLORS.gray}${description}${COLORS.reset}`, '', ...items.flatMap((item, index) => { const selected = index === this.topPage.index; const name = plans ? item.title || item.planId : `${item.id} · ${item.planId}`; const status = plans ? `${COLORS.green}Latest v${item.currentVersion}${COLORS.reset}` : `${COLORS.yellow}${item.status || 'Needs review'}${COLORS.reset}`; const detail = plans ? `Updated at: ${formatLocalDateTime(item.updatedAt || item.createdAt) || 'recently'}` : item.summary || `${item.changedPaths?.length || 0} changed paths`; return [`${selected ? `${COLORS.inverse}${COLORS.bold} › ${name} ${COLORS.reset}` : `   ${COLORS.bold}${COLORS.white}${name}${COLORS.reset}`}  ${status}`, `${COLORS.gray}   ${detail}${COLORS.reset}`, ...(plans && selected ? this.planAgentLines(item, '   ') : []), '']; }), `${COLORS.cyan}↑/↓ choose  •  Enter open  •  Esc back${COLORS.reset}`];
  }
  sessionPickerLines() {
    const rows = this.sessionPickerRows(); this.syncSessionPicker(rows); const streams = this.sessionPickerItems();
    const lines = [`${COLORS.yellow}Your sessions${COLORS.reset}`, `${COLORS.gray}Open a running session or resume one you closed earlier.${COLORS.reset}`, ''];
    for (const stream of streams) {
      const group = rows.filter((row) => row.stream.id === stream.id); const planning = group.find((row) => row.header); if (!planning) continue;
      const selected = group.find((row) => row.session.id === this.sessionPicker.sessionId); const planningSelected = selected?.header; const deleting = planningSelected && this.sessionPicker.confirmDelete === stream.id; const editingPlanning = this.sessionPicker.edit?.sessionId === planning.session.id;
      const planningName = editingPlanning ? `${this.sessionPicker.edit.value}${COLORS.bgCyan}${COLORS.black} ${COLORS.reset}` : fallbackName(planning.session, stream, this.workspace); const planningMarker = planning.session.attention ? '*' : '';
      const groupStatus = deleting ? `${COLORS.red}${COLORS.bold}Delete permanently?${COLORS.reset}` : stream.status === 'closed' ? `${COLORS.yellow}Ready to resume${COLORS.reset}` : `${COLORS.green}Running${COLORS.reset}`;
      const agents = this.workspace.sessions.filter((session) => session.workstreamId === stream.id); const updatedAt = [stream.updatedAt, ...agents.map((session) => session.updatedAt)].filter(Boolean).sort().at(-1); const updated = formatLocalDateTime(updatedAt); const summary = [stream.title || path.basename(this.root), updated ? `Updated at: ${updated}` : ''].filter(Boolean).join(' · ');
      const description = deleting ? `${COLORS.red}Press Enter to confirm · Esc to keep this session${COLORS.reset}` : `${COLORS.gray}${summary}${COLORS.reset}`;
      lines.push(`${planningSelected ? `${COLORS.inverse}${COLORS.bold} › ${planningName}${planningMarker} ${COLORS.reset}` : `   ${COLORS.bold}${COLORS.white}${planningName}${planningMarker}${COLORS.reset}`}  ${groupStatus}`, `   ${description}`);
      for (const [index, row] of group.entries()) {
        const childSelected = !row.header && row.session.id === this.sessionPicker.sessionId; const editing = this.sessionPicker.edit?.sessionId === row.session.id; const connector = index === group.length - 1 ? '└─' : '├─'; const provider = display(row.session.profile?.provider || stream.delegatorProfile?.provider || 'agent'); const status = row.session.status === 'running' ? `${COLORS.green}Running${COLORS.reset}` : row.session.status === 'bridge-reconnecting' ? `${COLORS.yellow}Bridge reconnecting${COLORS.reset}` : row.session.status === 'bridge-error' ? `${COLORS.red}Bridge error${COLORS.reset}` : row.session.explicitlyClosed ? `${COLORS.gray}Closed${COLORS.reset}` : `${COLORS.yellow}Saved${COLORS.reset}`; const marker = row.session.attention ? '*' : ''; const name = row.header ? 'Planning agent' : editing ? `${this.sessionPicker.edit.value}${COLORS.bgCyan}${COLORS.black} ${COLORS.reset}` : fallbackName(row.session, stream, this.workspace); const task = row.session.taskSnippet ? ` ${COLORS.gray}· Last Prompt: ${row.session.taskSnippet}${COLORS.reset}` : '';
        const body = `${COLORS.bold}${COLORS.white}${name}${row.header ? '' : marker}${COLORS.reset} ${COLORS.gray}· ${provider}${COLORS.reset}  ${status}${task}`; lines.push(`${COLORS.gray}   ${connector}${COLORS.reset} ${childSelected ? `${COLORS.inverse} ${body} ${COLORS.reset}` : body}`);
      }
      lines.push('');
    }
    if (this.sessionPicker.edit?.error) lines.push(`${COLORS.red}! ${this.sessionPicker.edit.error}${COLORS.reset}`, '');
    lines.push(`${COLORS.cyan}↑/↓ choose  •  Enter open  •  r rename  •  d delete  •  Esc back${COLORS.reset}`); return lines;
  }
  selectedSession() { return this.navigation?.currentAgent()?.session || null; }
  focusedSessionId() { if (this.navigation?.rail !== 'content' || this.wizard || this.sessionPicker || this.topPage) return null; return this.navigation.sessionId || null; }
  visibleSessionId() { if (!this.navigation || this.error || this.wizard || this.sessionPicker || this.topPage) return null; return this.navigation.sessionId || null; }
  raiseAttention(sessionId) { if (this.focusedSessionId() === sessionId) return false; this.store.setSessionAttention?.(sessionId, true); this.scheduleDraw(); return true; }
  clearFocusedAttention() { const sessionId = this.focusedSessionId(); if (sessionId) { this.store.setSessionAttention?.(sessionId, false); this.sessions.acknowledgeAttention?.(sessionId); } return sessionId; }
  scheduleDraw() { if (!this.running || this.redrawScheduled) return; this.redrawScheduled = true; setImmediate(() => { this.redrawScheduled = false; if (this.running) this.draw(); }); }
  drawScroll(sessionId, lines) { if (!this.running || this.visibleSessionId() !== sessionId || !Number.isInteger(lines) || !lines) return false; const dimensions = this.dimensions(); const amount = Math.min(Math.abs(lines), dimensions.rows); const content = this.sessions.screen?.(sessionId, dimensions.rows, { cursor: this.navigation.rail === 'content' }) || []; const outerRows = this.output.rows || 28; const bottom = outerRows - 3; const color = this.navigation.rail === 'content' ? COLORS.gray : COLORS.yellow; const indexes = lines < 0 ? Array.from({ length: amount }, (_, index) => index) : Array.from({ length: amount }, (_, index) => dimensions.rows - amount + index); const output = [`${ESC}3;${bottom}r${ESC}3;1H${ESC}${amount}${lines > 0 ? 'S' : 'T'}${ESC}r`]; for (const index of indexes) output.push(`${ESC}${index + 3};1H${color}│${COLORS.reset}${fit(`  ${content[index] || ''}`, Math.max(20, (this.output.columns || 100) - 2))}${color}│${COLORS.reset}`); this.output.write(output.join('')); return true; }
  pageName() { if (this.wizard) return 'New'; if (this.sessionPicker) return 'Sessions'; if (this.topPage) return this.topPage.action; if (NATIVE_PAGES.has(this.navigation?.activeAction)) return this.navigation.activeAction; return null; }
  titleName() { const page = this.pageName(); if (page) return page; const current = this.navigation?.currentAgent(); if (!current) return null; const planning = this.workspace.sessions.find((session) => session.workstreamId === current.stream.id && session.role === 'delegator'); return fallbackName(planning || current.session, current.stream, this.workspace); }
  footerPresentation() { if (this.quitPending) return { message: QUIT_MESSAGE, color: 203, align: 'right', bright: true }; if (!this.footerTransition) return { message: FOOTER_MESSAGES[this.footerIndex], color: null, align: 'right', bright: false }; const { from, to, frame } = this.footerTransition; return { message: frame <= FOOTER_FADE_MIDPOINT ? from : to, color: FOOTER_FADE_COLORS[frame], align: 'right', bright: false }; }
  rotateFooter() {
    const from = FOOTER_MESSAGES[this.footerIndex]; this.footerIndex = (this.footerIndex + 1) % FOOTER_MESSAGES.length;
    if (this.renderer.reducedMotion) { this.footerTransition = null; this.scheduleDraw(); return; }
    if (this.footerAnimationTimer !== undefined) this.cancelTimeout(this.footerAnimationTimer);
    this.footerTransition = { from, to: FOOTER_MESSAGES[this.footerIndex], frame: 0 }; this.scheduleDraw();
    const advance = () => { this.footerAnimationTimer = undefined; if (!this.running || !this.footerTransition) return; this.footerTransition.frame += 1; if (this.footerTransition.frame >= FOOTER_FADE_COLORS.length - 1) this.footerTransition = null; this.scheduleDraw(); if (this.footerTransition) { this.footerAnimationTimer = this.scheduleTimeout(advance, FOOTER_FADE_INTERVAL); this.footerAnimationTimer?.unref?.(); } };
    this.footerAnimationTimer = this.scheduleTimeout(advance, FOOTER_FADE_INTERVAL); this.footerAnimationTimer?.unref?.();
  }
  draw() { this.workspace = this.decorateWorkspace(this.store.load()); this.navigation ||= new Navigation(this.workspace); this.navigation.sync(this.workspace); const session = this.selectedSession(); const providerFocused = this.navigation.rail === 'content' && !this.navigation.activeAction; const picker = this.sessionPicker ? this.sessionPickerLines() : null; const content = this.error ? errorPageLines(this.error) : this.wizard ? this.wizard.render().split('\n') : picker || this.actionPageLines() || (session && this.sessions.screen ? this.sessions.screen(session.id, this.dimensions().rows, { cursor: providerFocused, inputBackground: providerFocused && codexRuntime(session.profile?.provider) }) : []); const footer = this.footerPresentation(); this.output.write(`${terminalTitle(this.titleName(), hasOpenAttention(this.workspace))}${ESC}H${this.renderer.render(this.workspace, this.navigation, { columns: this.output.columns || 100, rows: this.output.rows || 28, content, footerMessage: footer.message, footerColor: footer.color, footerAlign: footer.align, footerBright: footer.bright })}`); }
  start() {
    this.acquire(); this.bridge.start?.(); if (this.bridge.error) throw codedError('BRIDGE_START_FAILED', this.bridge.error.message); this.running = true; this.workspace = this.decorateWorkspace(this.store.load()); const openWorkstreams = new Set(this.workspace.workstreams.filter((stream) => stream.status !== 'closed').map((stream) => stream.id)); const hasOpenSession = this.workspace.sessions.some((session) => !session.explicitlyClosed && openWorkstreams.has(session.workstreamId) && (session.role === 'delegator' || session.role === 'worker'));
    if (!hasOpenSession) { this.navigation = new Navigation(this.workspace); this.navigation.rail = 'content'; if (this.workspace.sessions.length) { const rows = this.sessionPickerRows(this.workspace); const selected = rows.find((row) => row.stream.id === this.workspace.activeWorkstreamId) || rows[0]; this.sessionPicker = { index: Math.max(0, rows.indexOf(selected)), sessionId: selected?.session.id || null }; this.navigation.activeAction = 'Sessions'; } else { this.wizard = new WorkstreamWizard({ lastUsed: this.store.loadConfig?.() }); this.navigation.activeAction = 'New'; } }
    this.footerTimer = this.startInterval(() => this.rotateFooter(), 5000); this.footerTimer?.unref?.(); this.output.write(`${ESC}?1049h${ESC}?25l${ESC}?1000h${ESC}?1006h`); this.input.setRawMode?.(true); this.input.resume?.(); if (!this.wizard && this.sessions.restore) { const restored = this.sessions.restore(this.dimensions()); if (restored?.errors?.length) this.error = codedError('SESSION_RESTORE_FAILED', restored.errors.map(({ sessionId, error }) => `${sessionId}: ${error.message}`).join(' · ')); }
    const keys = { '\u001b[A': 'up', '\u001b[B': 'down', '\u001b[C': 'right', '\u001b[D': 'left' };
    const handle = (value) => {
      if (value === '\u0003') { if (this.quitPending) { this.stop(); return false; } this.quitPending = true; this.quitTimer = this.scheduleTimeout(() => { this.quitTimer = undefined; if (!this.running || !this.quitPending) return; this.quitPending = false; this.draw(); }, QUIT_CONFIRMATION_TIMEOUT); this.quitTimer?.unref?.(); return this.draw(); }
      const mouse = mouseEvent(value); if (mouse) { const sessionId = this.focusedSessionId(); const columns = this.output.columns || 100; const rows = this.output.rows || 28; if (isVerticalWheel(mouse) && this.topPage?.detail && (this.topPage.detail.reader || this.topPage.detail.diff)) { this.topPage.detail.scroll = Math.max(0, (this.topPage.detail.scroll || 0) + ((mouse.button & 1) === 0 ? -3 : 3)); this.draw(); } else if (sessionId && isVerticalWheel(mouse) && mouse.column >= 4 && mouse.column <= columns - 1 && mouse.row >= 3 && mouse.row <= rows - 3) { const translated = { ...mouse, column: mouse.column - 3, row: mouse.row - 2 }; const lines = (mouse.button & 1) === 0 ? -3 : 3; this.sessions.scroll?.(sessionId, lines, translated); } return; }
      if (this.topPage) {
        const plans = this.topPage.action === 'Plans'; const items = plans ? this.planItems() : this.reviewItems();
        if (this.topPage.feedback) { if (value === '\u001b') this.topPage.feedback = null; else if (value === '\r') { try { const detail = this.topPage.detail; this.scheduler.feedback(detail.executionId, detail.id, this.topPage.feedback.value, (executionId, chunkId, message) => this.sendWorker(executionId, chunkId, message)); this.topPage.feedback = null; this.topPage.detail = null; } catch (error) { this.topPage.feedback.error = error.message; } } else if (value === '\u007f' || value === '\b') this.topPage.feedback.value = [...this.topPage.feedback.value].slice(0, -1).join(''); else if (!/[\u0000-\u001f\u007f-\u009f]/u.test(value)) this.topPage.feedback.value += value; return this.draw(); }
        if (this.topPage.confirmIntegrate) { if (value === '\u001b') this.topPage.confirmIntegrate = false; else if (value === '\r') { try { this.integration.finalize(this.topPage.detail.executionId); this.topPage.confirmIntegrate = false; this.topPage.detail = null; } catch (error) { this.error = error; this.topPage = null; } } return this.draw(); }
        if (this.topPage.detail) {
          if (plans) {
            const detail = this.topPage.detail; const lineage = this.lineage.load(detail.planId); const manifest = this.lineage.readManifest(detail.planId, detail.version); const count = manifest.chunks.length + 2;
            if (detail.confirmExecute) { if (value === '\u001b') detail.confirmExecute = false; else if (value === '\r') { this.scheduler.freeze(detail.planId, detail.version, manifest.workstreamId || this.navigation.workstreamId); detail.confirmExecute = false; } return this.draw(); }
            if (isToggleKey(value) || value === 'q') { this.topPage.detail = null; return this.draw(); }
            if (value === '\u001b') { if (detail.reader || detail.diff) { detail.reader = false; detail.diff = false; detail.scroll = 0; } else this.topPage.detail = null; return this.draw(); }
            const scrolling = detail.reader || detail.diff;
            if (value === '\u001b[A') { if (scrolling) detail.scroll = Math.max(0, (detail.scroll || 0) - 1); else detail.sectionIndex = (detail.sectionIndex + count - 1) % count; }
            else if (value === '\u001b[B') { if (scrolling) detail.scroll = (detail.scroll || 0) + 1; else detail.sectionIndex = (detail.sectionIndex + 1) % count; }
            else if (value === '\u001b[5~' && scrolling) detail.scroll = Math.max(0, (detail.scroll || 0) - Math.max(1, this.dimensions().rows - 10));
            else if (value === '\u001b[6~' && scrolling) detail.scroll = (detail.scroll || 0) + Math.max(1, this.dimensions().rows - 10);
            else if (value === '\u001b[D') { detail.version = Math.max(1, detail.version - 1); detail.sectionIndex = 0; detail.scroll = 0; detail.diff = false; }
            else if (value === '\u001b[C') { detail.version = Math.min(lineage.currentVersion, detail.version + 1); detail.sectionIndex = 0; detail.scroll = 0; detail.diff = false; }
            else if (value === '\r' && !detail.reader && !detail.diff) { detail.reader = true; detail.scroll = 0; }
            else if (value === 'd' && !detail.reader && detail.version > 1) { detail.diff = !detail.diff; detail.scroll = 0; }
            else if (value === 'a' && !detail.diff) { const currentManifest = this.lineage.readManifest(detail.planId, detail.version); const section = [currentManifest.shared, ...currentManifest.chunks, currentManifest.globalValidation][detail.sectionIndex]; if (section) { const approved = currentManifest.approvals[section.id]?.sectionSha === section.sha; if (approved) this.lineage.removeApproval(detail.planId, detail.version, section.id); else this.lineage.approve(detail.planId, detail.version, section.id); } }
            else if (value === 'e' && !detail.reader && !detail.diff && !this.versionExecution(detail.planId, detail.version) && this.lineage.executable(detail.planId, detail.version)) { if (detail.version < lineage.currentVersion) detail.confirmExecute = true; else this.scheduler.freeze(detail.planId, detail.version, manifest.workstreamId || this.navigation.workstreamId); }
          }
          else { if (isToggleKey(value) || value === 'q' || value === '\u001b') { this.topPage.detail = null; return this.draw(); } const detail = this.topPage.detail; const item = items.find((candidate) => candidate.executionId === detail.executionId && candidate.id === detail.id); if (value === 'a' && item?.kind === 'chunk') { this.scheduler.accept(item.executionId, item.id); this.topPage.detail = null; } else if (value === 'f' && item?.kind === 'chunk') this.topPage.feedback = { value: '', error: null }; else if (value === 'i' && item?.kind === 'final') this.topPage.confirmIntegrate = true; }
          return this.draw();
        }
        if (isToggleKey(value) || value === 'q' || value === '\u001b') { this.topPage = null; this.navigation.activeAction = null; this.navigation.rail = 'workstreams'; return this.draw(); }
        if (value === '\u001b[A' && items.length) this.topPage.index = (this.topPage.index + items.length - 1) % items.length; else if (value === '\u001b[B' && items.length) this.topPage.index = (this.topPage.index + 1) % items.length; else if (value === '\r' && items.length) { const item = items[this.topPage.index]; this.topPage.detail = plans ? { planId: item.planId, version: item.currentVersion, sectionIndex: 0, reader: false, diff: false, scroll: 0 } : { executionId: item.executionId, id: item.id }; }
        return this.draw();
      }
      if (this.sessionPicker) {
        let rows = this.sessionPickerRows(this.store.load()); this.syncSessionPicker(rows); const selected = () => rows[this.sessionPicker.index];
        if (this.sessionPicker.edit) { if (value === '\u001b') this.sessionPicker.edit = null; else if (value === '\r') { try { this.store.renameSession(this.sessionPicker.edit.sessionId, this.sessionPicker.edit.value); this.sessionPicker.edit = null; } catch (error) { this.sessionPicker.edit.error = error.message; } } else if (value === '\u007f' || value === '\b') { this.sessionPicker.edit.value = [...this.sessionPicker.edit.value].slice(0, -1).join(''); this.sessionPicker.edit.error = null; } else if (!/[\u0000-\u001f\u007f-\u009f]/u.test(value)) { this.sessionPicker.edit.value += value; this.sessionPicker.edit.error = null; } return this.draw(); }
        if (isToggleKey(value) || value === 'q') { this.sessionPicker = null; this.navigation.activeAction = null; this.navigation.rail = 'workstreams'; return this.draw(); }
        if (value === '\u001b') { if (this.sessionPicker.confirmDelete) this.sessionPicker.confirmDelete = null; else { this.sessionPicker = null; this.navigation.activeAction = null; this.navigation.rail = 'workstreams'; } return this.draw(); }
        if ((value === '\u001b[A' || value === '\u001b[B') && rows.length) { const movement = value === '\u001b[A' ? -1 : 1; this.sessionPicker.index = (this.sessionPicker.index + rows.length + movement) % rows.length; this.sessionPicker.sessionId = rows[this.sessionPicker.index].session.id; this.sessionPicker.confirmDelete = null; }
        else if (value === 'r' && selected()) this.sessionPicker.edit = { sessionId: selected().session.id, value: selected().session.name || fallbackName(selected().session, selected().stream, this.workspace), error: null };
        else if (value === 'd' && selected()?.header) this.sessionPicker.confirmDelete = selected().stream.id;
        else if (value === '\r' && selected()) { const row = selected(); if (row.header && this.sessionPicker.confirmDelete === row.stream.id) { const sessionIds = this.store.load().sessions.filter((item) => item.workstreamId === row.stream.id).map((item) => item.id); for (const sessionId of sessionIds) this.sessions.delete?.(sessionId); this.store.deleteWorkstream(row.stream.id); rows = this.sessionPickerRows(this.store.load()); if (!rows.length) { this.sessionPicker = null; this.wizard = new WorkstreamWizard({ lastUsed: this.store.loadConfig?.() }); this.navigation = new Navigation(this.store.load()); this.navigation.rail = 'content'; this.navigation.activeAction = 'New'; } else { this.sessionPicker.index = Math.min(this.sessionPicker.index, rows.length - 1); this.sessionPicker.sessionId = rows[this.sessionPicker.index].session.id; this.sessionPicker.confirmDelete = null; } } else { if (row.stream.status === 'closed') this.store.reopenWorkstream(row.stream.id); else this.store.activateWorkstream(row.stream.id); const state = this.store.load(); const errors = []; for (const session of state.sessions.filter((item) => item.workstreamId === row.stream.id && (!item.explicitlyClosed || item.id === row.session.id))) { try { this.sessions.open(session.id, this.dimensions()); } catch (error) { errors.push(error.message); } } this.error = errors.length ? codedError('SESSION_RESTORE_FAILED', errors.join(' · ')) : null; this.sessionPicker = null; this.navigation = new Navigation(this.store.load()); this.navigation.selectSession(row.session.id); this.navigation.rail = 'workstreams'; this.navigation.activeAction = null; } }
        return this.draw();
      }
      if (value === 'q' && this.navigation.rail !== 'content') { this.stop(); return false; }
      if (isToggleKey(value)) { if (this.wizard && this.navigation.agents().length) { this.wizard = null; this.navigation.activeAction = null; this.navigation.rail = 'workstreams'; } else if (this.wizard) this.navigation.rail = this.navigation.rail === 'content' ? 'actions' : 'content'; else if (this.navigation.rail === 'content') this.navigation.rail = 'workstreams'; else { const selected = this.selectedSession(); if (selected) { try { this.sessions.open(selected.id, this.dimensions()); this.error = null; this.navigation.activeAction = null; this.navigation.rail = 'content'; this.clearFocusedAttention(); } catch (error) { this.error = error; } } } return this.draw(); }
      if (this.wizard && value === '\u001b') { this.wizard = null; this.navigation.activeAction = null; this.navigation.rail = 'workstreams'; return this.draw(); }
      if (this.wizard && this.navigation.rail === 'content') { const config = this.wizard.handle(value); if (config) { const stream = this.store.createWorkstream(config); const session = this.store.createSession(stream.id, 'delegator', config.delegatorProfile); this.wizard = null; this.navigation = null; try { this.sessions.open(session.id, this.dimensions()); } catch (error) { this.error = error; } } return this.draw(); }
      if (value === '\r' && this.navigation.rail === 'actions') return this.activate(this.navigation.selectedAction());
      if (value === '\r' && this.navigation.rail === 'workstreams') { const selected = this.selectedSession(); if (selected) { try { this.store.activateWorkstream?.(selected.workstreamId); this.sessions.open(selected.id, this.dimensions()); this.error = null; this.navigation.activeAction = null; this.navigation.rail = 'content'; this.clearFocusedAttention(); } catch (error) { this.error = error; } } return this.draw(); }
      if (keys[value] && this.navigation.rail !== 'content') { this.navigation.key(keys[value]); return this.draw(); }
      const session = this.selectedSession(); if (this.navigation.rail === 'content' && session) this.sessions.write(session.id, value);
    };
    this.onData = (data) => { for (const value of inputTokens(data)) if (handle(value) === false) break; }; this.onResize = () => { const dimensions = this.dimensions(); for (const sessionId of this.sessions.processes?.keys?.() || []) this.sessions.resize?.(sessionId, dimensions.columns, dimensions.rows); this.draw(); }; this.input.on?.('data', this.onData); this.output.on?.('resize', this.onResize); this.draw(); return this;
  }
  activate(action) {
    if (action === 'Quit') return this.stop();
    if (action === 'New') { this.sessionPicker = null; this.topPage = null; this.wizard = new WorkstreamWizard({ lastUsed: this.store.loadConfig?.() }); this.navigation.activeAction = 'New'; this.navigation.rail = 'content'; return this.draw(); }
    if (action === 'Sessions') { this.wizard = null; this.topPage = null; const rows = this.sessionPickerRows(this.store.load()); const current = rows.findIndex(({ session }) => session.id === this.navigation.sessionId); this.sessionPicker = { index: Math.max(0, current), sessionId: rows[Math.max(0, current)]?.session.id || rows[0]?.session.id || null }; this.navigation.activeAction = 'Sessions'; this.navigation.rail = 'content'; return this.draw(); }
    if (action === 'Close') { const streamId = this.navigation.workstreamId; const workspace = this.workspace || this.store.load(); if (streamId) { const sessionIds = workspace.sessions.filter((session) => session.workstreamId === streamId && !session.explicitlyClosed).map((session) => session.id); for (const sessionId of sessionIds) this.sessions.close?.(sessionId); if (this.store.closeWorkstream) this.store.closeWorkstream(streamId); else { const stream = workspace.workstreams.find((item) => item.id === streamId); if (stream) stream.status = 'closed'; } } this.navigation.activeAction = null; this.navigation.sessionId = null; this.navigation.workstreamId = null; this.navigation.rail = 'workstreams'; return this.draw(); }
    if (action === 'Plans' || action === 'Review') { const items = action === 'Plans' ? this.planItems() : this.reviewItems(); if (items.length) { this.wizard = null; this.sessionPicker = null; this.topPage = { action, index: 0 }; this.navigation.activeAction = action; this.navigation.rail = 'content'; return this.draw(); } const role = action === 'Plans' ? 'plan' : 'review'; const session = this.workspace.sessions.findLast((item) => item.workstreamId === this.navigation.workstreamId && item.role === role && !item.explicitlyClosed); if (session) { this.sessions.open(session.id, this.dimensions()); this.navigation.sessionId = session.id; this.navigation.activeAction = action; this.navigation.rail = 'content'; this.store.setSessionAttention?.(session.id, false); } return this.draw(); }
    return this.draw();
  }
  stop() { this.running = false; this.quitPending = false; if (this.quitTimer !== undefined) { this.cancelTimeout(this.quitTimer); this.quitTimer = undefined; } if (this.footerTimer !== undefined) { this.stopInterval(this.footerTimer); this.footerTimer = undefined; } if (this.footerAnimationTimer !== undefined) { this.cancelTimeout(this.footerAnimationTimer); this.footerAnimationTimer = undefined; } this.footerTransition = null; this.sessions.shutdown?.(); this.bridge.close?.(); this.input.off?.('data', this.onData); this.output.off?.('resize', this.onResize); this.input.setRawMode?.(false); this.input.pause?.(); this.output.write(`${terminalTitle(null, false)}${ESC}?1006l${ESC}?1000l${ESC}?25h${ESC}?1049l`); this.release(); }
}

module.exports = { ACTIONS, FOOTER_MESSAGES, availableActions, COLORS, width, fit, crop, softWrapLine, softWrap, railName, inputTokens, mouseEvent, isVerticalWheel, isToggleKey, sanitizeTerminalTitle, formatLocalDateTime, hasOpenAttention, terminalTitle, codedError, errorPageLines, Navigation, TerminalRenderer, TerminalSupervisor };
