'use strict';

const fs = require('node:fs'); const path = require('node:path');
const { WorkspaceStore } = require('../state/workspace'); const { SessionManager } = require('../sessions/manager');
const { WorkstreamWizard, display } = require('./wizard');

const ESC = '\u001b['; const COLORS = { yellow: `${ESC}38;5;220m`, cyan: `${ESC}38;5;81m`, green: `${ESC}38;5;114m`, red: `${ESC}38;5;203m`, white: `${ESC}38;5;255m`, black: `${ESC}38;5;16m`, bgYellow: `${ESC}48;5;220m`, bgCyan: `${ESC}48;5;81m`, bgGray: `${ESC}48;5;245m`, gray: `${ESC}38;5;245m`, reset: `${ESC}0m`, bold: `${ESC}1m`, underline: `${ESC}4m`, inverse: `${ESC}7m`, dim: `${ESC}2m` };
const ACTIONS = ['New', 'Plans', 'Sessions', 'Review', 'Close', 'Quit'];
const NATIVE_PAGES = new Set(['New', 'Plans', 'Sessions', 'Review']);
const FOOTER_MESSAGES = ['Tip: Press Ctrl+] to toggle focus between agents and BDFL.', 'Like BDFL? Star github.com/thisisnsh/bdfl'];
function availableActions(workspace) { const sessions = workspace.sessions || []; const active = workspace.workstreams?.some((stream) => stream.status !== 'closed'); return ACTIONS.filter((action) => action === 'New' || action === 'Quit' || action === 'Sessions' && workspace.workstreams?.length || action === 'Close' && active || action === 'Plans' && (workspace.planCount > 0 || sessions.some((session) => session.role === 'plan' && !session.explicitlyClosed)) || action === 'Review' && (workspace.reviewCount > 0 || sessions.some((session) => session.role === 'review' && !session.explicitlyClosed))); }
function characterWidth(character) { if (/\p{Mark}/u.test(character)) return 0; return /\p{Extended_Pictographic}|\p{Script=Han}|\p{Script=Hangul}|\p{Script=Hiragana}|\p{Script=Katakana}|[\uFF01-\uFF60\uFFE0-\uFFE6]/u.test(character) ? 2 : 1; }
function width(value) { return [...`${value}`.replace(/\u001b\][^\u0007]*(?:\u0007|\u001b\\)/g, '').replace(/\u001b\[[0-9;?]*[A-Za-z]/g, '')].reduce((sum, character) => sum + characterWidth(character), 0); }
function crop(value, columns, ellipsis = false) { if (columns <= 0) return ''; const result = []; let used = 0; const limit = ellipsis && width(value) > columns ? Math.max(0, columns - 1) : columns; for (const character of `${value}`) { const size = characterWidth(character); if (used + size > limit) break; result.push(character); used += size; } return `${result.join('')}${ellipsis && width(value) > columns && columns > 0 ? '…' : ''}`; }
function fit(value, columns) { const result = []; let used = 0; const tokens = `${value}`.match(/\u001b\[[0-9;?]*[A-Za-z]|./gu) || []; for (const token of tokens) { if (token.startsWith('\u001b[')) { result.push(token); continue; } const size = characterWidth(token); if (used + size > columns) break; result.push(token); used += size; } return result.join('') + ' '.repeat(Math.max(0, columns - used)); }
function railName(value) { return width(value) <= 16 ? `${value}` : crop(value, 16, true); }
const TOGGLE_KEYS = new Set(['\u001d', '\u001b[93;5u', '\u001b[29;5u']);
function isToggleKey(value) { return TOGGLE_KEYS.has(value); }
function inputTokens(value) { return `${value}`.match(/\u001b\[<[0-9]+;[0-9]+;[0-9]+[Mm]|\u001b\[[0-9]+(?:;[0-9]+)*u|\u001b\[[A-D]|./gsu) || []; }
function mouseEvent(value) { const match = /^\u001b\[<([0-9]+);([0-9]+);([0-9]+)([Mm])$/.exec(value); if (!match) return null; return { button: Number(match[1]), column: Number(match[2]), row: Number(match[3]), final: match[4] }; }
function isVerticalWheel(mouse) { return mouse?.final === 'M' && (mouse.button & 64) !== 0 && (mouse.button & 3) < 2; }
function sanitizeTerminalTitle(value) { return `${value ?? ''}`.replace(/[\u0000-\u001f\u007f-\u009f]/gu, ''); }
function hasOpenAttention(workspace) { const open = new Set((workspace.workstreams || []).filter((stream) => stream.status !== 'closed').map((stream) => stream.id)); return (workspace.sessions || []).some((session) => session.attention && !session.explicitlyClosed && open.has(session.workstreamId)); }
function terminalTitle(name = null, attention = false) { const safe = sanitizeTerminalTitle(name); return `\u001b]2;${attention ? '* ' : ''}bdfl${safe ? ` - ${safe}` : ''}\u0007`; }
function fallbackName(session, stream, workspace) { if (session?.name) return session.name; if (session?.role === 'worker') return `W ${session.roleSequence || Math.max(1, session.paneNumber - 1 || 1)}`; const provider = stream?.delegatorProfile?.provider || session?.profile?.provider || 'agent'; const label = provider === 'claude' ? 'Claude Code' : display(provider); const index = workspace.workstreams.indexOf(stream); const sequence = stream?.providerSequence || workspace.workstreams.slice(0, index + 1).filter((item) => item.delegatorProfile?.provider === provider).length || 1; return `${label} ${sequence}`; }
function agentSessions(workspace, stream) { return (workspace.sessions || []).filter((session) => session.workstreamId === stream.id && !session.explicitlyClosed && (session.role === 'delegator' || session.role === 'worker')).sort((a, b) => (a.paneNumber || 0) - (b.paneNumber || 0)); }

class Navigation {
  constructor(workspace) { this.workspace = workspace; this.rail = 'workstreams'; this.action = 0; this.workstream = 0; this.pane = 0; this.workstreamId = workspace.activeWorkstreamId || null; this.sessionId = null; this.activeAction = null; this.sync(workspace); }
  streams() { return (this.workspace.workstreams || []).filter((stream) => stream.status !== 'closed'); }
  agents() { return this.streams().flatMap((stream) => agentSessions(this.workspace, stream).map((session) => ({ stream, session }))); }
  sync(workspace) {
    this.workspace = workspace; const agents = this.agents(); let index = agents.findIndex(({ session }) => session.id === this.sessionId);
    if (index < 0) { index = agents.findIndex(({ stream, session }) => stream.id === this.workstreamId && session.role === 'delegator'); if (index < 0) index = agents.findIndex(({ stream }) => stream.id === workspace.activeWorkstreamId); if (index < 0) index = 0; }
    const selected = agents[index]; this.sessionId = selected?.session.id || null; this.workstreamId = selected?.stream.id || null; this.workstream = Math.max(0, this.streams().findIndex((stream) => stream.id === this.workstreamId)); const panes = this.panes(); this.pane = Math.max(0, panes.findIndex((session) => session.id === this.sessionId)); this.action = Math.min(this.action, Math.max(0, this.actions().length - 1)); return this;
  }
  currentAgent() { return this.agents().find(({ session }) => session.id === this.sessionId) || null; }
  currentStream() { return this.currentAgent()?.stream || this.streams().find((stream) => stream.id === this.workstreamId); }
  panes() { return this.currentStream() ? agentSessions(this.workspace, this.currentStream()) : []; }
  actions() { return availableActions(this.workspace); }
  selectedAction() { return this.actions()[this.action]; }
  selectSession(id) { this.sessionId = id; return this.sync(this.workspace); }
  key(name) {
    if (this.rail === 'workstreams') {
      const agents = this.agents(); const current = Math.max(0, agents.findIndex(({ session }) => session.id === this.sessionId));
      if ((name === 'right' || name === 'left') && agents.length) { const delta = name === 'right' ? 1 : -1; const selected = agents[(current + agents.length + delta) % agents.length]; this.sessionId = selected.session.id; this.workstreamId = selected.stream.id; this.sync(this.workspace); }
      else if (name === 'up') this.rail = 'actions';
    } else if (this.rail === 'actions') {
      if (name === 'left' && this.actions().length) this.action = (this.action + this.actions().length - 1) % this.actions().length;
      else if (name === 'right' && this.actions().length) this.action = (this.action + 1) % this.actions().length;
      else if (name === 'down') this.rail = 'workstreams';
    }
    return { rail: this.rail, action: this.selectedAction(), workstream: this.currentStream(), pane: this.currentAgent()?.session };
  }
}

class TerminalRenderer {
  constructor({ version = '0.1.0', reducedMotion = false } = {}) { this.version = version; this.reducedMotion = reducedMotion; }
  railItems(workspace, navigation) { let previousStream = null; return navigation.agents().map(({ stream, session }) => { const planning = session.role === 'delegator'; const prefix = planning ? previousStream === null ? '' : ' ' : '-'; previousStream = stream.id; const text = `${railName(fallbackName(session, stream, workspace))}${session.attention ? '*' : ''}`; return { session, prefix, open: planning ? '[' : '(', close: planning ? ']' : ')', plain: `${prefix}${planning ? '[' : '('}${text}${planning ? ']' : ')'}`, text }; }); }
  visibleRail(items, selectedId, budget) { if (!items.length) return []; const selected = Math.max(0, items.findIndex((item) => item.session.id === selectedId)); if (width(items[selected].plain) > budget) { const item = items[selected]; const fixed = width(`${item.prefix}${item.open}${item.close}${item.session.attention ? '*' : ''}`); const name = crop(item.text.replace(/\*$/, ''), Math.max(1, budget - fixed), true); return [{ ...item, text: `${name}${item.session.attention ? '*' : ''}`, plain: `${item.prefix}${item.open}${name}${item.session.attention ? '*' : ''}${item.close}` }]; } let start = selected; let end = selected + 1; let used = width(items[selected].plain); let changed = true; while (changed) { changed = false; if (start > 0 && used + width(items[start - 1].plain) <= budget) { start -= 1; used += width(items[start].plain); changed = true; } if (end < items.length && used + width(items[end].plain) <= budget) { used += width(items[end].plain); end += 1; changed = true; } } return items.slice(start, end); }
  footer(workspace, navigation, columns, message) { const available = Math.max(1, columns - 4); const ownsRail = navigation.rail === 'workstreams' && !navigation.activeAction; const selected = navigation.currentAgent(); const waiting = selected?.session.role === 'worker' ? 'Waiting for an assignment' : 'Waiting for a prompt'; const leftFull = ownsRail && selected ? `${fallbackName(selected.session, selected.stream, workspace)}: ${selected.session.taskSnippet || waiting}` : ''; let right = `${message || FOOTER_MESSAGES[0]}`; if (width(right) > available) return `${COLORS.dim}  ${crop(right, available, true).padEnd(available)}  ${COLORS.reset}`; const allowance = Math.max(0, available - width(right) - (leftFull ? 1 : 0)); const left = allowance ? crop(leftFull, allowance, width(leftFull) > allowance) : ''; const gap = ' '.repeat(Math.max(left ? 1 : 0, available - width(left) - width(right))); return `${COLORS.dim}  ${left}${gap}${right}  ${COLORS.reset}`; }
  render(workspace, navigation, { columns = 100, rows = 28, content = [], footerMessage = FOOTER_MESSAGES[0] } = {}) {
    const chromeFocused = navigation.rail !== 'content'; const color = chromeFocused ? COLORS.yellow : COLORS.gray; const inner = Math.max(1, columns - 2); const topLabel = ` bdfl ${this.version} `; const visibleActions = navigation.actions(); const plainActions = visibleActions.map((action) => `[${action}]`).join(' '); const topFill = inner - width(topLabel) - width(plainActions) - 2;
    let headerBody; if (topFill < 0) headerBody = `${fit(`─${topLabel}`, inner - 1)}─`; else { const actions = visibleActions.map((action, index) => { const active = navigation.activeAction === action; const hovered = navigation.rail === 'actions' && navigation.action === index; return active || hovered ? `${COLORS.bgYellow}${COLORS.black}${COLORS.bold}[${action}]${COLORS.reset}${color}` : `[${action}]`; }).join(' '); headerBody = `─${topLabel}${'─'.repeat(topFill)}${actions}─`; }
    const lines = [`${color}┌${headerBody}┐${COLORS.reset}`]; const contentRows = Math.max(1, rows - 3);
    for (let row = 0; row < contentRows; row += 1) { const contentLine = row === 0 ? '' : content[row - 1] || ''; lines.push(`${color}│${COLORS.reset}${fit(`  ${contentLine}`, inner)}${color}│${COLORS.reset}`); }
    const agentFocused = navigation.rail === 'content' && !navigation.activeAction; const visible = this.visibleRail(this.railItems(workspace, navigation), navigation.sessionId, inner - 1); const labels = visible.map((item) => { const label = `${item.prefix}${item.open}${item.text}${item.close}`; const selected = item.session.id === navigation.sessionId; if (navigation.activeAction) return `${COLORS.gray}${label}${COLORS.reset}${color}`; if (agentFocused) return selected ? `${COLORS.bgGray}${COLORS.black}${COLORS.bold}${label}${COLORS.reset}${color}` : `${COLORS.gray}${label}${COLORS.reset}${color}`; return selected ? `${COLORS.bgYellow}${COLORS.black}${COLORS.bold}${label}${COLORS.reset}${color}` : `${COLORS.yellow}${label}${COLORS.reset}${color}`; }); const rail = `─${labels.join('')}`; const bottomBody = width(rail) <= inner ? `${rail}${'─'.repeat(inner - width(rail))}` : fit(rail, inner);
    lines.push(`${color}└${bottomBody}┘${COLORS.reset}`); lines.push(this.footer(workspace, navigation, columns, footerMessage)); return lines.join('\n');
  }
}

class TerminalSupervisor {
  constructor(root, { input = process.stdin, output = process.stdout, store = new WorkspaceStore(root), sessions, version = '0.1.0', setInterval: startInterval = global.setInterval, clearInterval: stopInterval = global.clearInterval } = {}) { this.root = path.resolve(root); this.input = input; this.output = output; this.store = store; this.sessions = sessions || new SessionManager(root, store); this.sessions.onOutput = (sessionId, event) => { if (!event?.scroll || !this.drawScroll(sessionId, event.scroll)) this.scheduleDraw(); }; this.sessions.onAttention = (sessionId) => this.raiseAttention(sessionId); this.renderer = new TerminalRenderer({ version, reducedMotion: process.env.NO_COLOR === '1' }); this.lockFile = path.join(root, '.bdfl', 'run', 'supervisor.lock'); this.frame = 0; this.footerIndex = 0; this.startInterval = startInterval; this.stopInterval = stopInterval; }
  acquire() { fs.mkdirSync(path.dirname(this.lockFile), { recursive: true }); for (let attempt = 0; attempt < 2; attempt += 1) { try { this.lock = fs.openSync(this.lockFile, 'wx', 0o600); fs.writeFileSync(this.lock, `${process.pid}\n`); return; } catch (error) { if (error.code !== 'EEXIST') throw error; let owner; try { owner = Number.parseInt(fs.readFileSync(this.lockFile, 'utf8'), 10); } catch {} let alive = Number.isInteger(owner) && owner > 0; if (alive) { try { process.kill(owner, 0); } catch (probe) { if (probe.code === 'ESRCH') alive = false; } } if (alive || attempt) throw new Error('Another BDFL supervisor owns this workspace'); try { fs.unlinkSync(this.lockFile); } catch (remove) { if (remove.code !== 'ENOENT') throw remove; } } } }
  release() { if (this.lock === undefined) return; fs.closeSync(this.lock); this.lock = undefined; try { fs.unlinkSync(this.lockFile); } catch (error) { if (error.code !== 'ENOENT') throw error; } }
  dimensions() { return { columns: Math.max(20, (this.output.columns || 100) - 4), rows: Math.max(1, (this.output.rows || 28) - 4) }; }
  planItems() { const directory = path.join(this.root, '.bdfl', 'plans'); let entries; try { entries = fs.readdirSync(directory, { withFileTypes: true }); } catch { return []; } return entries.filter((entry) => entry.isDirectory()).flatMap((entry) => { try { return [JSON.parse(fs.readFileSync(path.join(directory, entry.name, 'lineage.json'), 'utf8'))]; } catch { return []; } }).sort((a, b) => `${b.updatedAt}`.localeCompare(`${a.updatedAt}`)); }
  reviewItems() { const directory = path.join(this.root, '.bdfl', 'executions'); let entries; try { entries = fs.readdirSync(directory, { withFileTypes: true }); } catch { return []; } return entries.filter((entry) => entry.isDirectory()).flatMap((entry) => { try { const execution = JSON.parse(fs.readFileSync(path.join(directory, entry.name, 'execution.json'), 'utf8')); return execution.chunks.filter((chunk) => chunk.status === 'review').map((chunk) => ({ ...chunk, executionId: execution.id, planId: execution.planId })); } catch { return []; } }); }
  decorateWorkspace(workspace) { return { ...workspace, planCount: this.planItems().length, reviewCount: this.reviewItems().length }; }
  sessionPickerItems(workspace = this.workspace || this.store.load()) { return workspace.workstreams.map((stream, index) => { const agents = workspace.sessions.filter((session) => session.workstreamId === stream.id); const modifiedAt = [stream.updatedAt, stream.createdAt, ...agents.flatMap((session) => [session.updatedAt, session.createdAt])].filter(Boolean).sort().at(-1) || ''; return { stream, index, modifiedAt }; }).sort((a, b) => b.modifiedAt.localeCompare(a.modifiedAt) || a.index - b.index).map(({ stream }) => stream); }
  sessionPickerRows(workspace = this.workspace || this.store.load()) { return this.sessionPickerItems(workspace).flatMap((stream) => { const sessions = workspace.sessions.filter((session) => session.workstreamId === stream.id && (session.role === 'delegator' || session.role === 'worker')).sort((a, b) => (a.paneNumber || 0) - (b.paneNumber || 0)); const planning = sessions.find((session) => session.role === 'delegator'); if (!planning) return []; return [{ stream, session: planning, header: true }, ...sessions.filter((session) => session.role === 'worker').map((session) => ({ stream, session, header: false }))]; }); }
  syncSessionPicker(rows) { let index = rows.findIndex(({ session }) => session.id === this.sessionPicker.sessionId); if (index < 0) index = Math.min(this.sessionPicker.index || 0, Math.max(0, rows.length - 1)); this.sessionPicker.index = Math.max(0, index); this.sessionPicker.sessionId = rows[index]?.session.id || null; return this.sessionPicker.index; }
  actionPageLines() { if (!this.topPage) return null; const plans = this.topPage.action === 'Plans'; const items = plans ? this.planItems() : this.reviewItems(); const title = plans ? 'Plans' : 'Ready for review'; const description = plans ? 'Browse durable implementation plans created in this workspace.' : 'Worker results waiting for your review and acceptance.'; return [`${COLORS.bold}${plans ? COLORS.cyan : COLORS.yellow}${title}${COLORS.reset}`, `${COLORS.gray}${description}${COLORS.reset}`, '', ...items.flatMap((item, index) => { const selected = index === this.topPage.index; const name = plans ? item.title || item.planId : `${item.id} · ${item.planId}`; const status = plans ? `${COLORS.green}Version ${item.currentVersion}${COLORS.reset}` : `${COLORS.yellow}Needs review${COLORS.reset}`; const detail = plans ? `Updated ${item.updatedAt || item.createdAt || 'recently'}` : item.summary || `${item.changedPaths?.length || 0} changed paths`; return [`${selected ? `${COLORS.inverse}${COLORS.bold} › ${name} ${COLORS.reset}` : `   ${COLORS.bold}${COLORS.white}${name}${COLORS.reset}`}  ${status}`, `${COLORS.gray}   ${detail}${COLORS.reset}`, '']; }), `${COLORS.cyan}↑/↓ choose${COLORS.reset}${COLORS.gray}  •  Ctrl+] back${COLORS.reset}`]; }
  sessionPickerLines() { const rows = this.sessionPickerRows(); this.syncSessionPicker(rows); const lines = [`${COLORS.bold}${COLORS.yellow}Your sessions${COLORS.reset}`, `${COLORS.gray}Open, resume, or rename an agent. Planning rows own permanent deletion.${COLORS.reset}`, '']; for (const [index, row] of rows.entries()) { const selected = index === this.sessionPicker.index; const editing = this.sessionPicker.edit?.sessionId === row.session.id; const deleting = row.header && this.sessionPicker.confirmDelete === row.stream.id; const provider = display(row.session.profile?.provider || row.stream.delegatorProfile?.provider || 'agent'); const status = row.session.status === 'running' ? 'Running' : row.session.explicitlyClosed ? 'Closed' : 'Saved'; const snippet = row.session.taskSnippet || (row.session.role === 'worker' ? 'Waiting for an assignment' : 'Waiting for a prompt'); const name = editing ? `${this.sessionPicker.edit.value}${COLORS.bgCyan}${COLORS.black} ${COLORS.reset}` : fallbackName(row.session, row.stream, this.workspace); const marker = row.session.attention ? '*' : ''; const prefix = row.header ? selected ? ' › ' : '   ' : selected ? '   › ' : '     '; const connector = row.header ? '' : '└─ '; const detail = deleting ? `${COLORS.red}${COLORS.bold}Delete permanently? Press Enter to confirm.${COLORS.reset}` : `${COLORS.bold}${COLORS.white}${name}${marker}${COLORS.reset} ${COLORS.gray}· ${provider} · ${status} · ${snippet}${COLORS.reset}`; lines.push(`${selected ? COLORS.inverse : ''}${prefix}${connector}${detail}${selected ? COLORS.reset : ''}`); } if (this.sessionPicker.edit?.error) lines.push('', `${COLORS.red}! ${this.sessionPicker.edit.error}${COLORS.reset}`); lines.push('', `${COLORS.cyan}↑/↓ choose${COLORS.reset}${COLORS.gray}  •  Enter open  •  r rename  •  d delete planning session  •  Esc/Ctrl+] back${COLORS.reset}`); return lines; }
  selectedSession() { return this.navigation?.currentAgent()?.session || null; }
  focusedSessionId() { if (this.navigation?.rail !== 'content' || this.wizard || this.sessionPicker || this.topPage) return null; return this.navigation.sessionId || null; }
  visibleSessionId() { if (!this.navigation || this.error || this.wizard || this.sessionPicker || this.topPage) return null; return this.navigation.sessionId || null; }
  raiseAttention(sessionId) { if (this.focusedSessionId() === sessionId) return false; this.store.setSessionAttention?.(sessionId, true); this.scheduleDraw(); return true; }
  clearFocusedAttention() { const sessionId = this.focusedSessionId(); if (sessionId) this.store.setSessionAttention?.(sessionId, false); return sessionId; }
  scheduleDraw() { if (!this.running || this.redrawScheduled) return; this.redrawScheduled = true; setImmediate(() => { this.redrawScheduled = false; if (this.running) this.draw(); }); }
  drawScroll(sessionId, lines) { if (!this.running || this.visibleSessionId() !== sessionId || !Number.isInteger(lines) || !lines) return false; const dimensions = this.dimensions(); const amount = Math.min(Math.abs(lines), dimensions.rows); const content = this.sessions.screen?.(sessionId, dimensions.rows, { cursor: this.navigation.rail === 'content' }) || []; const outerRows = this.output.rows || 28; const bottom = outerRows - 2; const color = this.navigation.rail === 'content' ? COLORS.gray : COLORS.yellow; const indexes = lines < 0 ? Array.from({ length: amount }, (_, index) => index) : Array.from({ length: amount }, (_, index) => dimensions.rows - amount + index); const output = [`${ESC}3;${bottom}r${ESC}3;1H${ESC}${amount}${lines > 0 ? 'S' : 'T'}${ESC}r`]; for (const index of indexes) output.push(`${ESC}${index + 3};1H${color}│${COLORS.reset}${fit(`  ${content[index] || ''}`, Math.max(20, (this.output.columns || 100) - 2))}${color}│${COLORS.reset}`); this.output.write(output.join('')); return true; }
  pageName() { if (this.wizard) return 'New'; if (this.sessionPicker) return 'Sessions'; if (this.topPage) return this.topPage.action; if (NATIVE_PAGES.has(this.navigation?.activeAction)) return this.navigation.activeAction; return null; }
  titleName() { const page = this.pageName(); if (page) return page; const current = this.navigation?.currentAgent(); if (!current) return null; const planning = this.workspace.sessions.find((session) => session.workstreamId === current.stream.id && session.role === 'delegator'); return fallbackName(planning || current.session, current.stream, this.workspace); }
  draw() { this.workspace = this.decorateWorkspace(this.store.load()); this.navigation ||= new Navigation(this.workspace); this.navigation.sync(this.workspace); const session = this.selectedSession(); const picker = this.sessionPicker ? this.sessionPickerLines() : null; const content = this.error ? [`${COLORS.bold}${COLORS.red}Something went wrong${COLORS.reset}`, `${COLORS.gray}${this.error}${COLORS.reset}`] : this.wizard ? this.wizard.render().split('\n') : picker || this.actionPageLines() || (session && this.sessions.screen ? this.sessions.screen(session.id, this.dimensions().rows, { cursor: this.navigation.rail === 'content' }) : []); this.output.write(`${terminalTitle(this.titleName(), hasOpenAttention(this.workspace))}${ESC}H${this.renderer.render(this.workspace, this.navigation, { columns: this.output.columns || 100, rows: this.output.rows || 28, content, footerMessage: FOOTER_MESSAGES[this.footerIndex] })}`); }
  start() {
    this.acquire(); this.running = true; this.workspace = this.decorateWorkspace(this.store.load()); const openWorkstreams = new Set(this.workspace.workstreams.filter((stream) => stream.status !== 'closed').map((stream) => stream.id)); const hasOpenSession = this.workspace.sessions.some((session) => !session.explicitlyClosed && openWorkstreams.has(session.workstreamId) && (session.role === 'delegator' || session.role === 'worker'));
    if (!hasOpenSession) { this.navigation = new Navigation(this.workspace); this.navigation.rail = 'content'; if (this.workspace.sessions.length) { const rows = this.sessionPickerRows(this.workspace); const selected = rows.find((row) => row.stream.id === this.workspace.activeWorkstreamId) || rows[0]; this.sessionPicker = { index: Math.max(0, rows.indexOf(selected)), sessionId: selected?.session.id || null }; this.navigation.activeAction = 'Sessions'; } else { this.wizard = new WorkstreamWizard({ lastUsed: this.store.loadConfig?.() }); this.navigation.activeAction = 'New'; } }
    this.footerTimer = this.startInterval(() => { this.footerIndex = (this.footerIndex + 1) % FOOTER_MESSAGES.length; this.scheduleDraw(); }, 5000); this.footerTimer?.unref?.(); this.output.write(`${ESC}?1049h${ESC}?25l${ESC}?1000h${ESC}?1006h`); this.input.setRawMode?.(true); this.input.resume?.(); if (!this.wizard && this.sessions.restore) { const restored = this.sessions.restore(this.dimensions()); if (restored?.errors?.length) this.error = restored.errors.map(({ sessionId, error }) => `${sessionId}: ${error.message}`).join(' · '); }
    const keys = { '\u001b[A': 'up', '\u001b[B': 'down', '\u001b[C': 'right', '\u001b[D': 'left' };
    const handle = (value) => {
      const mouse = mouseEvent(value); if (mouse) { const sessionId = this.visibleSessionId(); const columns = this.output.columns || 100; const rows = this.output.rows || 28; if (sessionId && isVerticalWheel(mouse) && mouse.column >= 4 && mouse.column <= columns - 1 && mouse.row >= 3 && mouse.row <= rows - 2) { const translated = { ...mouse, column: mouse.column - 3, row: mouse.row - 2 }; const lines = (mouse.button & 1) === 0 ? -3 : 3; this.sessions.scroll?.(sessionId, lines, translated); } return; }
      if (this.topPage) { const items = this.topPage.action === 'Plans' ? this.planItems() : this.reviewItems(); if (isToggleKey(value) || value === 'q' || value === '\u001b') { this.topPage = null; this.navigation.activeAction = null; this.navigation.rail = 'workstreams'; return this.draw(); } if (value === '\u001b[A' && items.length) this.topPage.index = (this.topPage.index + items.length - 1) % items.length; else if (value === '\u001b[B' && items.length) this.topPage.index = (this.topPage.index + 1) % items.length; return this.draw(); }
      if (this.sessionPicker) {
        let rows = this.sessionPickerRows(this.store.load()); this.syncSessionPicker(rows); const selected = () => rows[this.sessionPicker.index];
        if (this.sessionPicker.edit) { if (value === '\u001b') this.sessionPicker.edit = null; else if (value === '\r') { try { this.store.renameSession(this.sessionPicker.edit.sessionId, this.sessionPicker.edit.value); this.sessionPicker.edit = null; } catch (error) { this.sessionPicker.edit.error = error.message; } } else if (value === '\u007f' || value === '\b') { this.sessionPicker.edit.value = [...this.sessionPicker.edit.value].slice(0, -1).join(''); this.sessionPicker.edit.error = null; } else if (!/[\u0000-\u001f\u007f-\u009f]/u.test(value)) { this.sessionPicker.edit.value += value; this.sessionPicker.edit.error = null; } return this.draw(); }
        if (isToggleKey(value) || value === 'q') { this.sessionPicker = null; this.navigation.activeAction = null; this.navigation.rail = 'workstreams'; return this.draw(); }
        if (value === '\u001b') { if (this.sessionPicker.confirmDelete) this.sessionPicker.confirmDelete = null; else { this.sessionPicker = null; this.navigation.activeAction = null; this.navigation.rail = 'workstreams'; } return this.draw(); }
        if ((value === '\u001b[A' || value === '\u001b[B') && rows.length) { const movement = value === '\u001b[A' ? -1 : 1; this.sessionPicker.index = (this.sessionPicker.index + rows.length + movement) % rows.length; this.sessionPicker.sessionId = rows[this.sessionPicker.index].session.id; this.sessionPicker.confirmDelete = null; }
        else if (value === 'r' && selected()) this.sessionPicker.edit = { sessionId: selected().session.id, value: selected().session.name || fallbackName(selected().session, selected().stream, this.workspace), error: null };
        else if (value === 'd' && selected()?.header) this.sessionPicker.confirmDelete = selected().stream.id;
        else if (value === '\r' && selected()) { const row = selected(); if (row.header && this.sessionPicker.confirmDelete === row.stream.id) { const sessionIds = this.store.load().sessions.filter((item) => item.workstreamId === row.stream.id).map((item) => item.id); for (const sessionId of sessionIds) this.sessions.delete?.(sessionId); this.store.deleteWorkstream(row.stream.id); rows = this.sessionPickerRows(this.store.load()); if (!rows.length) { this.sessionPicker = null; this.wizard = new WorkstreamWizard({ lastUsed: this.store.loadConfig?.() }); this.navigation = new Navigation(this.store.load()); this.navigation.rail = 'content'; this.navigation.activeAction = 'New'; } else { this.sessionPicker.index = Math.min(this.sessionPicker.index, rows.length - 1); this.sessionPicker.sessionId = rows[this.sessionPicker.index].session.id; this.sessionPicker.confirmDelete = null; } } else { if (row.stream.status === 'closed') this.store.reopenWorkstream(row.stream.id); else this.store.activateWorkstream(row.stream.id); const state = this.store.load(); const errors = []; for (const session of state.sessions.filter((item) => item.workstreamId === row.stream.id && !item.explicitlyClosed)) { try { this.sessions.open(session.id, this.dimensions()); } catch (error) { errors.push(error.message); } } this.error = errors.length ? errors.join(' · ') : null; this.sessionPicker = null; this.navigation = new Navigation(this.store.load()); this.navigation.selectSession(row.session.id); this.navigation.rail = 'workstreams'; this.navigation.activeAction = null; } }
        return this.draw();
      }
      if (value === '\u0003' || value === 'q' && this.navigation.rail !== 'content') { this.stop(); return false; }
      if (isToggleKey(value)) { if (this.wizard && this.navigation.agents().length) { this.wizard = null; this.navigation.activeAction = null; this.navigation.rail = 'workstreams'; } else if (this.wizard) this.navigation.rail = this.navigation.rail === 'content' ? 'actions' : 'content'; else if (this.navigation.rail === 'content') this.navigation.rail = 'workstreams'; else { const selected = this.selectedSession(); if (selected) { try { this.sessions.open(selected.id, this.dimensions()); this.error = null; this.navigation.activeAction = null; this.navigation.rail = 'content'; this.clearFocusedAttention(); } catch (error) { this.error = error.message; } } } return this.draw(); }
      if (this.wizard && value === '\u001b') { this.wizard = null; this.navigation.activeAction = null; this.navigation.rail = 'workstreams'; return this.draw(); }
      if (this.wizard && this.navigation.rail === 'content') { const config = this.wizard.handle(value); if (config) { const stream = this.store.createWorkstream(config); const session = this.store.createSession(stream.id, 'delegator', config.delegatorProfile); this.wizard = null; this.navigation = null; try { this.sessions.open(session.id, this.dimensions()); } catch (error) { this.error = error.message; } } return this.draw(); }
      if (value === '\r' && this.navigation.rail === 'actions') return this.activate(this.navigation.selectedAction());
      if (value === '\r' && this.navigation.rail === 'workstreams') { const selected = this.selectedSession(); if (selected) { try { this.store.activateWorkstream?.(selected.workstreamId); this.sessions.open(selected.id, this.dimensions()); this.error = null; this.navigation.activeAction = null; this.navigation.rail = 'content'; this.clearFocusedAttention(); } catch (error) { this.error = error.message; } } return this.draw(); }
      if (keys[value] && this.navigation.rail !== 'content') { this.navigation.key(keys[value]); return this.draw(); }
      const session = this.selectedSession(); if (this.navigation.rail === 'content' && session) this.sessions.write(session.id, value);
    };
    this.onData = (data) => { for (const value of inputTokens(data)) if (handle(value) === false) break; }; this.input.on?.('data', this.onData); this.draw(); return this;
  }
  activate(action) {
    if (action === 'Quit') return this.stop();
    if (action === 'New') { this.sessionPicker = null; this.topPage = null; this.wizard = new WorkstreamWizard({ lastUsed: this.store.loadConfig?.() }); this.navigation.activeAction = 'New'; this.navigation.rail = 'content'; return this.draw(); }
    if (action === 'Sessions') { this.wizard = null; this.topPage = null; const rows = this.sessionPickerRows(this.store.load()); const current = rows.findIndex(({ session }) => session.id === this.navigation.sessionId); this.sessionPicker = { index: Math.max(0, current), sessionId: rows[Math.max(0, current)]?.session.id || rows[0]?.session.id || null }; this.navigation.activeAction = 'Sessions'; this.navigation.rail = 'content'; return this.draw(); }
    if (action === 'Close') { const streamId = this.navigation.workstreamId; const workspace = this.workspace || this.store.load(); if (streamId) { const sessionIds = workspace.sessions.filter((session) => session.workstreamId === streamId && !session.explicitlyClosed).map((session) => session.id); for (const sessionId of sessionIds) this.sessions.close?.(sessionId); if (this.store.closeWorkstream) this.store.closeWorkstream(streamId); else { const stream = workspace.workstreams.find((item) => item.id === streamId); if (stream) stream.status = 'closed'; } } this.navigation.activeAction = null; this.navigation.sessionId = null; this.navigation.workstreamId = null; this.navigation.rail = 'workstreams'; return this.draw(); }
    if (action === 'Plans' || action === 'Review') { const items = action === 'Plans' ? this.planItems() : this.reviewItems(); if (items.length) { this.wizard = null; this.sessionPicker = null; this.topPage = { action, index: 0 }; this.navigation.activeAction = action; this.navigation.rail = 'content'; return this.draw(); } const role = action === 'Plans' ? 'plan' : 'review'; const session = this.workspace.sessions.findLast((item) => item.workstreamId === this.navigation.workstreamId && item.role === role && !item.explicitlyClosed); if (session) { this.sessions.open(session.id, this.dimensions()); this.navigation.sessionId = session.id; this.navigation.activeAction = action; this.navigation.rail = 'content'; this.store.setSessionAttention?.(session.id, false); } return this.draw(); }
    return this.draw();
  }
  stop() { this.running = false; if (this.footerTimer !== undefined) { this.stopInterval(this.footerTimer); this.footerTimer = undefined; } this.sessions.shutdown?.(); this.input.off?.('data', this.onData); this.input.setRawMode?.(false); this.input.pause?.(); this.output.write(`${terminalTitle(null, false)}${ESC}?1006l${ESC}?1000l${ESC}?25h${ESC}?1049l`); this.release(); }
}

module.exports = { ACTIONS, FOOTER_MESSAGES, availableActions, COLORS, width, fit, crop, railName, inputTokens, mouseEvent, isVerticalWheel, isToggleKey, sanitizeTerminalTitle, hasOpenAttention, terminalTitle, Navigation, TerminalRenderer, TerminalSupervisor };
