'use strict';

const fs = require('node:fs'); const path = require('node:path');
const { WorkspaceStore } = require('../state/workspace'); const { SessionManager } = require('../sessions/manager');
const { WorkspaceCatalog, LineageCatalog } = require('../state/repositories');
const { LineageStore } = require('../plans/store'); const { WorkerScheduler } = require('../workers/scheduler'); const { IntegrationCoordinator } = require('../workers/integration'); const { ExecutionGit } = require('../worktrees/execution');
const { PlanService, WorkerService, ControlServer } = require('../mcp/bridge');
const { errorDetails, ISSUE_URL, openExternal } = require('../core/errors');
const { WorkstreamWizard, display } = require('./wizard');
const { ACTIONS, Chrome, createdOrder, childOrder, hitAt } = require('./chrome');
const { ReviewView, stateDescriptor } = require('./review-view');

const ESC = '\u001b['; const COLORS = { yellow: `${ESC}38;5;220m`, cyan: `${ESC}38;5;81m`, green: `${ESC}38;5;114m`, red: `${ESC}38;5;203m`, white: `${ESC}38;5;255m`, black: `${ESC}38;5;16m`, bgYellow: `${ESC}48;5;220m`, bgCyan: `${ESC}48;5;81m`, bgGray: `${ESC}48;5;245m`, gray: `${ESC}38;5;245m`, reset: `${ESC}0m`, bold: `${ESC}1m`, underline: `${ESC}4m`, inverse: `${ESC}7m`, dim: `${ESC}2m` };
const NATIVE_PAGES = new Set(['New', 'Plans', 'Sessions', 'Reviews']);
const STAR_MESSAGE = 'Tip: Star github.com/thisisnsh/bdfl to show support.';
const VERIFIER_CONTINUATION = 'The BDFL supervisor restarted while your execution-agent verification phase was incomplete. Retain this conversation context, re-read durable execution status and the existing verifier context, and finish one comprehensive review of the entire approved change. Do not edit during verification. If it fails, report every finding with evidence and a concrete remedy. Then call bdfl_workers complete with pass or fail.';
const INTEGRATION_CONTINUATION = 'The BDFL supervisor restarted while your execution-agent repair or reconciliation phase was incomplete. Retain this conversation context, re-read durable execution status and the active worktree, preserve every approved intent, and finish the assigned repair plus comprehensive internal audit before reporting pass. Then call bdfl_workers complete with pass or fail.';
const QUIT_MESSAGE = 'Press Ctrl+C again to quit.';
const QUIT_CONFIRMATION_TIMEOUT = 5000;
const FOOTER_MESSAGES = [
  '↑↓ scroll · Click badges to switch · Ctrl+C twice quits',
  'Click a plan section to inspect or approve it',
  'Click a session group to open its primary agent',
  'Select result lines before sending review feedback',
  'Choose a repository, agent type, then a setup'
];
function availableActions(workspace) { const active = workspace.sessions?.some((session) => !session.explicitlyClosed); return ACTIONS.filter((action) => action !== 'Close' || active); }
function characterWidth(character) { if (/\p{Mark}/u.test(character)) return 0; return /\p{Extended_Pictographic}|\p{Script=Han}|\p{Script=Hangul}|\p{Script=Hiragana}|\p{Script=Katakana}|[\uFF01-\uFF60\uFFE0-\uFFE6]/u.test(character) ? 2 : 1; }
function width(value) { return [...`${value}`.replace(/\u001b\][^\u0007]*(?:\u0007|\u001b\\)/g, '').replace(/\u001b\[[0-9;?]*[A-Za-z]/g, '')].reduce((sum, character) => sum + characterWidth(character), 0); }
function crop(value, columns, ellipsis = false) { if (columns <= 0) return ''; const result = []; let used = 0; const limit = ellipsis && width(value) > columns ? Math.max(0, columns - 1) : columns; for (const character of `${value}`) { const size = characterWidth(character); if (used + size > limit) break; result.push(character); used += size; } return `${result.join('')}${ellipsis && width(value) > columns && columns > 0 ? '…' : ''}`; }
function fit(value, columns) { const result = []; let used = 0; const tokens = `${value}`.match(/\u001b\[[0-9;?]*[A-Za-z]|./gu) || []; for (const token of tokens) { if (token.startsWith('\u001b[')) { result.push(token); continue; } const size = characterWidth(token); if (used + size > columns) break; result.push(token); used += size; } return result.join('') + ' '.repeat(Math.max(0, columns - used)); }
function softWrapLine(value, columns) { const line = `${value}`; if (!line || width(line) <= columns) return [line]; const indent = line.match(/^\s*(?:[-*+]\s+|\d+[.)]\s+|>\s*)?/u)?.[0] || ''; const continuation = ' '.repeat(Math.min(width(indent), Math.max(0, columns - 1))); const words = line.slice(indent.length).split(/(\s+)/u); const lines = []; let current = indent; const push = () => { lines.push(current.trimEnd()); current = continuation; }; for (const word of words) { if (!word) continue; if (/^\s+$/u.test(word)) { if (current && !current.endsWith(' ')) current += ' '; continue; } if (width(current) + width(word) <= columns) { current += word; continue; } if (current.trim()) push(); let remainder = word; while (width(current) + width(remainder) > columns) { const budget = Math.max(1, columns - width(current)); let piece = ''; for (const character of remainder) { if (width(piece) + characterWidth(character) > budget) break; piece += character; } current += piece; remainder = remainder.slice(piece.length); push(); } current += remainder; } if (current.trim() || !lines.length) lines.push(current.trimEnd()); return lines; }
function softWrap(lines, columns) { return lines.flatMap((line) => softWrapLine(line, Math.max(8, columns))); }
function diffViewLines(lines, columns) { return lines.flatMap((line) => { const prefix = line.type === 'addition' ? '+' : line.type === 'removal' ? '-' : ' '; const color = line.type === 'addition' ? COLORS.green : line.type === 'removal' ? COLORS.red : ''; return softWrapLine(`${prefix} ${line.text}`, Math.max(8, columns)).map((row) => color ? `${color}${row}${COLORS.reset}` : row); }); }
function patchViewLines(value, columns) { return `${value}`.split('\n').flatMap((line) => { const addition = line.startsWith('+') && !line.startsWith('+++'); const removal = line.startsWith('-') && !line.startsWith('---'); const color = addition ? COLORS.green : removal ? COLORS.red : ''; return softWrapLine(line, Math.max(8, columns)).map((row) => color ? `${color}${row}${COLORS.reset}` : row); }); }
function railName(value) { return width(value) <= 16 ? `${value}` : crop(value, 16, true); }
function promptPreview(value) { const characters = [...`${value || ''}`]; return characters.length <= 75 ? characters.join('') : `${characters.slice(0, 74).join('')}…`; }
function inputTokens(value) { return `${value}`.match(/\u001b\][^\u0007]*(?:\u0007|\u001b\\)|\u001b\[[0-?]*[ -/]*[@-~]|\u001bO.|\u001b.|./gsu) || []; }
function mouseEvent(value) { const match = /^\u001b\[<([0-9]+);([0-9]+);([0-9]+)([Mm])$/.exec(value); if (!match) return null; return { button: Number(match[1]), column: Number(match[2]), row: Number(match[3]), final: match[4] }; }
function isVerticalWheel(mouse) { return mouse?.final === 'M' && (mouse.button & 64) !== 0 && (mouse.button & 3) < 2; }
function isPrimaryClick(mouse) { return mouse?.final === 'M' && mouse.button === 0; }
function sanitizeTerminalTitle(value) { return `${value ?? ''}`.replace(/[\u0000-\u001f\u007f-\u009f]/gu, ''); }
function formatLocalDateTime(value) { if (!value) return ''; const date = new Date(value); return Number.isNaN(date.getTime()) ? '' : date.toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' }); }
function hasOpenAttention(workspace) { const open = new Set((workspace.workstreams || []).filter((stream) => stream.status !== 'closed').map((stream) => stream.id)); return (workspace.sessions || []).some((session) => session.attention && !session.explicitlyClosed && open.has(session.workstreamId)); }
function terminalTitle(name = null, attention = false) { const safe = sanitizeTerminalTitle(name); return `\u001b]2;${attention ? '* ' : ''}bdfl${safe ? ` - ${safe}` : ''}\u0007`; }
function primaryRole(role) { return role === 'delegator' || role === 'direct'; }
function fallbackName(session, stream, workspace) { if (session?.name) return session.name; if (session?.role === 'worker') return `W ${session.roleSequence || Math.max(1, session.paneNumber - 1 || 1)}`; const provider = stream?.sessionType === 'direct' ? stream.directProfile?.provider : stream?.delegatorProfile?.provider || session?.profile?.provider || 'agent'; const label = provider === 'claude' ? 'Claude Code' : display(provider); const index = workspace.workstreams.indexOf(stream); const sequence = stream?.providerSequence || workspace.workstreams.slice(0, index + 1).filter((item) => (item.sessionType === 'direct' ? item.directProfile : item.delegatorProfile)?.provider === provider).length || 1; return `${label} ${sequence}`; }
function agentSessions(workspace, stream) { return childOrder((workspace.sessions || []).filter((session) => session.workstreamId === stream.id && (primaryRole(session.role) || ['worker', 'verifier', 'integration'].includes(session.role)))); }
function pausedSession(session) { return session?.status === 'paused'; }
function terminalSession(session) { return Boolean(session?.explicitlyClosed || session?.accepted || session?.completed || session?.superseded || ['accepted', 'cancelled', 'closed', 'complete', 'completed', 'done', 'integrated', 'rejected', 'superseded'].includes(session?.status)); }
function resumableSession(session) { if (!session || session.accepted || session.completed || session.superseded || ['accepted', 'cancelled', 'complete', 'completed', 'done', 'integrated', 'rejected', 'superseded'].includes(session.status)) return false; return session.status === 'paused' || Boolean(session.explicitlyClosed && (!session.status || session.status === 'closed')); }
function codedError(code, message) { const error = new Error(message); error.code = code; return error; }
function errorPageLines(error) { const details = errorDetails(error); return [`${COLORS.bold}${COLORS.red}BDFL encountered an error${COLORS.reset}`, '', `${COLORS.bold}Code${COLORS.reset}     ${COLORS.yellow}${details.code}${COLORS.reset}`, `${COLORS.bold}Message${COLORS.reset}  ${details.message}`, '', `${COLORS.gray}Please open an issue and include the code and message:${COLORS.reset}`, `${COLORS.cyan}${ISSUE_URL}${COLORS.reset}`]; }
function emptyStateLines() { const logo = ['██████╗ ██████╗ ███████╗██╗', '██╔══██╗██╔══██╗██╔════╝██║', '██████╔╝██║  ██║█████╗  ██║', '██╔══██╗██║  ██║██╔══╝  ██║', '██████╔╝██████╔╝██║     ███████╗', '╚═════╝ ╚═════╝ ╚═╝     ╚══════╝']; return [...logo.map((line) => `${COLORS.bold}${COLORS.yellow}${line}${COLORS.reset}`), '', `${COLORS.white}Benevolent Delegator for LLMs${COLORS.reset}`, `${COLORS.gray}Created by Nishant Hada${COLORS.reset}`]; }

class Navigation {
  constructor(workspace) { this.workspace = workspace; this.rail = 'content'; this.action = 0; this.workstream = 0; this.pane = 0; this.workstreamId = workspace.activeWorkstreamId || null; this.sessionId = null; this.activeAction = null; this.sync(workspace); }
  streams() { return createdOrder((this.workspace.workstreams || []).filter((stream) => stream.status !== 'closed')); }
  agents() { return this.streams().flatMap((stream) => agentSessions(this.workspace, stream).map((session) => ({ stream, session }))); }
  sync(workspace) {
    this.workspace = workspace; const agents = this.agents(); let index = agents.findIndex(({ session }) => session.id === this.sessionId);
    if (index < 0) { const open = ({ session }) => !pausedSession(session) && !terminalSession(session); index = agents.findIndex(({ stream, session }) => stream.id === this.workstreamId && primaryRole(session.role) && open({ session })); if (index < 0) index = agents.findIndex(({ stream, session }) => stream.id === this.workstreamId && open({ session })); if (index < 0) index = agents.findIndex(({ stream, session }) => stream.id === workspace.activeWorkstreamId && open({ session })); if (index < 0) index = agents.findIndex(open); if (index < 0) index = agents.findIndex(({ stream, session }) => stream.id === this.workstreamId && primaryRole(session.role)); if (index < 0) index = 0; }
    const selected = agents[index]; this.sessionId = selected?.session.id || null; this.workstreamId = selected?.stream.id || null; this.workstream = Math.max(0, this.streams().findIndex((stream) => stream.id === this.workstreamId)); const panes = this.panes(); this.pane = Math.max(0, panes.findIndex((session) => session.id === this.sessionId)); this.action = Math.min(this.action, Math.max(0, this.actions().length - 1)); return this;
  }
  currentAgent() { return this.agents().find(({ session }) => session.id === this.sessionId) || null; }
  currentStream() { return this.currentAgent()?.stream || this.streams().find((stream) => stream.id === this.workstreamId); }
  panes() { return this.currentStream() ? agentSessions(this.workspace, this.currentStream()) : []; }
  actions() { return availableActions(this.workspace).filter((action) => action !== 'Close' || !this.activeAction); }
  selectedAction() { return this.actions()[this.action]; }
  selectSession(id) { this.sessionId = id; return this.sync(this.workspace); }
  key(name) {
    if (this.rail === 'workstreams') {
      const agents = this.agents(); const current = Math.max(0, agents.findIndex(({ session }) => session.id === this.sessionId));
      if ((name === 'right' || name === 'left') && agents.length) { const delta = name === 'right' ? 1 : -1; const selected = agents[(current + agents.length + delta) % agents.length]; this.sessionId = selected.session.id; this.workstreamId = selected.stream.id; this.sync(this.workspace); }
      else if (name === 'up') this.rail = 'actions';
    } else if (this.rail === 'actions') {
      if (name === 'left' && this.actions().length) this.action = (this.action + this.actions().length - 1) % this.actions().length;
      else if (name === 'right' && this.actions().length) this.action = (this.action + 1) % this.actions().length;
      else if (name === 'down') this.rail = 'workstreams';
    }
    return { rail: this.rail, action: this.selectedAction(), workstream: this.currentStream(), pane: this.currentAgent()?.session };
  }
}

class TerminalRenderer {
  constructor({ version = '0.1.0', reducedMotion = false } = {}) { this.version = version; this.reducedMotion = reducedMotion; this.chrome = new Chrome({ version, reducedMotion }); }
  chromeWorkspace(workspace) { return { ...workspace, workstreams: (workspace.workstreams || []).map((stream) => { const primary = (workspace.sessions || []).find((session) => session.workstreamId === stream.id && primaryRole(session.role)); return { ...stream, name: stream.name || primary && fallbackName(primary, stream, workspace) || stream.title }; }) }; }
  options(workspace, navigation, options = {}) { const current = navigation.currentAgent()?.session; return { columns: options.columns, rows: options.rows, expandedWorkstreamId: navigation.workstreamId, activeAction: navigation.activeAction, activeSessionId: navigation.activeAction ? null : navigation.sessionId, showClose: Boolean(current && !terminalSession(current) && !navigation.activeAction), isRunning: options.isRunning, phase: options.phase, tip: options.footerMessage || FOOTER_MESSAGES[0] }; }
  layout(workspace, navigation, options = {}) { return this.chrome.layout(this.chromeWorkspace(workspace), this.options(workspace, navigation, options)); }
  render(workspace, navigation, { columns = 100, rows = 28, content = [], footerMessage = FOOTER_MESSAGES[0], showBack = false, isRunning } = {}) {
    const layout = this.layout(workspace, navigation, { columns, rows, footerMessage, isRunning }); const lines = [...layout.lines]; const inner = Math.max(1, columns - 2); const bodyRows = Math.max(1, rows - 3); const values = showBack ? [`${COLORS.yellow}[Back]${COLORS.reset}`, '', ...content] : content;
    for (let index = 0; index < bodyRows; index += 1) lines[index + 1] = `${COLORS.yellow}│${COLORS.reset}${fit(`  ${values[index] || ''}`, inner)}${COLORS.yellow}│${COLORS.reset}`;
    if (showBack) layout.hits.push({ type: 'back', row: 2, start: 4, end: 9 });
    if (layout.tipRow) { const tip = crop(footerMessage, Math.max(0, inner - 4), true); const padding = ' '.repeat(Math.max(0, inner - width(tip) - 2)); lines[layout.tipRow - 1] = `${COLORS.yellow}│${COLORS.reset}${padding}${COLORS.gray}${tip}${COLORS.reset}  ${COLORS.yellow}│${COLORS.reset}`; }
    layout.lines = lines; layout.output = lines.join('\n'); this.lastLayout = layout; return layout.output;
  }
}

class TerminalSupervisor {
  constructor(root, { input = process.stdin, output = process.stdout, store = null, sessions, lineage, git, scheduler, integration, bridge, version = '0.1.0', dangerous = false, linkOpener = openExternal, setInterval: startInterval = global.setInterval, clearInterval: stopInterval = global.clearInterval, setTimeout: scheduleTimeout = global.setTimeout, clearTimeout: cancelTimeout = global.clearTimeout } = {}) {
    this.input = input; this.output = output; this.store = store || new WorkspaceCatalog(root); this.root = this.store.coordinatorRoot?.() || path.resolve(root); this.dangerous = dangerous; this.lineage = lineage || (this.store.repositoryRoots ? new LineageCatalog(this.store) : new LineageStore(this.root)); this.git = git || new ExecutionGit(this.root);
    this.scheduler = scheduler || new WorkerScheduler(this.root, { store: this.store, lineage: this.lineage, worktrees: this.git, launcher: (value) => this.launchWorker(value), validator: (value) => this.validateWorker(value) });
    this.integration = integration || new IntegrationCoordinator({ scheduler: this.scheduler, git: this.git, lineage: this.lineage, agentLauncher: (value) => this.launchExecutionAgent(value) });
    if (!scheduler) this.scheduler.onAllAccepted = (executionId) => { try { this.integration.prepare(executionId); } catch (error) { this.error = codedError('INTEGRATION_PREPARE_FAILED', error.message); this.scheduleDraw(); } };
    this.workerService = new WorkerService({ scheduler: this.scheduler, integration: this.integration, sender: (executionId, chunkId, message) => this.sendWorker(executionId, chunkId, message) }); this.bridge = bridge || new ControlServer({ planService: new PlanService(this.lineage), workerService: this.workerService }); this.bridge.setToolSuccessHandler?.((event) => this.handleToolSuccess(event));
    this.sessions = sessions || new SessionManager(this.root, this.store, { bridge: this.bridge, requireBridge: true, dangerous }); this.sessions.onOutput = (sessionId, event) => { if (this.visibleSessionId() !== sessionId) return; if (event?.scroll || event?.activity) this.scheduleDraw(); else this.scheduleOutputDraw(sessionId); }; this.sessions.onAttention = (sessionId) => this.raiseAttention(sessionId); this.sessions.onBridgeError = (_sessionId, error) => { this.error = codedError('BRIDGE_RECOVERY_FAILED', error.message); this.scheduleDraw(); }; this.sessions.onExit = (session, result) => { if (!session?.executionId || !['verifier', 'integration'].includes(session.role)) return; try { const execution = this.scheduler.load?.(session.executionId); const activeAgent = execution?.integration?.agent?.sessionId || (execution?.status === 'verifying' ? execution?.integration?.verifier?.sessionId : execution?.integration?.worker?.sessionId); if (activeAgent !== session.id) return; const reason = `Execution agent exited before reporting (exit ${result.exitCode ?? 'unknown'}, signal ${result.signal ?? 'none'})`; if (execution.status === 'verifying') this.integration.retryVerification?.(session.executionId, { sessionId: session.id, reason }); else if (execution.status === 'integration-conflict') this.integration.repaired?.(session.executionId, { state: 'fail', summary: reason }); } catch (error) { this.error = codedError('EXECUTION_AGENT_RECOVERY_FAILED', error.message); } this.scheduleDraw(); };
    this.renderer = new TerminalRenderer({ version, reducedMotion: process.env.NO_COLOR === '1' }); this.reviewView = new ReviewView(); this.linkOpener = linkOpener; this.lastFocused = new Map(); this.previousSurface = null; this.lockFile = path.join(this.root, '.bdfl', 'run', 'supervisor.lock'); this.locks = []; this.quitPending = false; this.quitTimer = undefined; this.outputDrawTimer = undefined; this.lastFrameLines = null; this.lastTerminalTitle = null; this.startInterval = startInterval; this.stopInterval = stopInterval; this.scheduleTimeout = scheduleTimeout; this.cancelTimeout = cancelTimeout;
    const reconcile = () => { let errors; try { errors = this.reconcileManagedSessions(); } catch (error) { errors = [{ sessionId: 'managed sessions', error }]; } if (errors.length) this.error = codedError('SESSION_RECONCILE_FAILED', errors.map(({ sessionId, error }) => `${sessionId}: ${error.message}`).join(' · ')); this.scheduleDraw(); }; const schedulerChange = this.scheduler.onChange; this.scheduler.onChange = (...args) => { schedulerChange?.(...args); reconcile(); }; const integrationChange = this.integration.onChange; this.integration.onChange = (...args) => { integrationChange?.(...args); reconcile(); };
  }
  createWizard() { if (!this.store.selectableRepositories) return new WorkstreamWizard({ repositories: [{ root: this.root, label: '.', lastUsed: this.store.loadConfig?.() }] }); return new WorkstreamWizard({ repositories: this.store.selectableRepositories(), rememberedRepositoryRoot: this.store.rememberedRepositoryRoot?.() }); }
  finishWizard(config) { const stream = this.store.createWorkstream(config, undefined, config.repositoryRoot); const direct = config.sessionType === 'direct'; const session = this.store.createSession(stream.id, direct ? 'direct' : 'delegator', direct ? config.directProfile : config.delegatorProfile, { turnState: 'working', turnStateReason: 'new session' }); this.wizard = null; this.navigation = new Navigation(this.store.load()); this.navigation.selectSession(session.id); try { this.sessions.open(session.id, this.dimensions()); this.clearFocusedAttention(); } catch (error) { this.error = error; } return session; }
  markTurn(sessionId, state, reason) { if (!sessionId) return; try { this.store.setSessionTurnState?.(sessionId, state, reason); } catch {} }
  handleToolSuccess({ capability, name, arguments: args }) { if (name === 'bdfl_plan' && args.action === 'publish') this.markTurn(capability.sessionId, 'idle', 'plan published'); else if (name === 'bdfl_workers' && args.action === 'complete') this.markTurn(capability.sessionId, 'idle', `reported ${args.state}`); else if (name === 'bdfl_workers' && ['feedback', 'send'].includes(args.action)) { const chunk = this.scheduler.load?.(args.executionId || capability.executionId)?.chunks?.find((item) => item.id === (args.chunkId || capability.chunkId)); this.markTurn(chunk?.attempts?.at(-1)?.sessionId, 'working', args.action); } else if (name === 'bdfl_workers' && args.action === 'remedy') { const execution = this.scheduler.load?.(args.executionId || capability.executionId); this.markTurn(execution?.integration?.agent?.sessionId || execution?.integration?.worker?.sessionId, 'working', 'accepted remedy'); } this.scheduleDraw(); }
  workerPrompt(execution, chunk, context) { return `You are a BDFL-managed worker for “${chunk.title || chunk.taskSnippet || chunk.id}”. Work only in your isolated worktree and only within the approved paths: ${chunk.paths.join(', ')}. Read the clean context at ${context}. Implement the chunk, run useful checks, then call bdfl_workers complete with a concise summary. Do not create subagents, publish plans, start executions, or integrate branches.`; }
  launchWorker({ execution, chunk, attempt, context, profile, taskSnippet }) { const worktree = this.git.createWorker(execution.id, chunk.id, attempt.number, attempt.base, execution.repositoryRoot); const session = this.store.createSession(execution.workstreamId, 'worker', profile, { executionId: execution.id, chunkId: chunk.id, worktree: worktree.worktree, taskSnippet, turnState: 'working', turnStateReason: 'implementation started', roleInstruction: this.workerPrompt(execution, chunk, context) }); this.sessions.open(session.id, this.dimensions()); return { ...worktree, sessionId: session.id, context }; }
  validateWorker({ execution, chunk, attempt }) { const head = this.git.checkpoint(attempt.worktree, `BDFL ${execution.planId} ${chunk.id}`); return this.git.verifyResult({ base: attempt.base, head, ownedPaths: chunk.paths, checks: chunk.checks || [], worktree: attempt.worktree }); }
  sendWorker(executionId, chunkId, message) { const chunk = this.scheduler.load(executionId).chunks.find((item) => item.id === chunkId); const sessionId = chunk?.attempts.at(-1)?.sessionId; if (!sessionId) throw new Error(`No active worker session for ${chunkId}`); const session = this.store.load().sessions.find((item) => item.id === sessionId); const open = this.sessions.isOpen?.(sessionId) ?? Boolean(session && !session.explicitlyClosed && session.status === 'running'); if (!open) { if (!session) throw new Error(`Worker session is unavailable: ${sessionId}`); if (this.sessions.resume) this.sessions.resume(sessionId, this.dimensions()); else this.sessions.open(sessionId, this.dimensions()); } this.markTurn(sessionId, 'working', 'feedback'); this.sessions.write(sessionId, `\u001b[200~${message}\u001b[201~`); this.sessions.write(sessionId, '\r'); }
  nextManagedName(workstreamId, prefix) { const expression = new RegExp(`^${prefix} ([0-9]+)$`); const used = this.store.load().sessions.filter((session) => session.workstreamId === workstreamId).map((session) => expression.exec(session.name)?.[1]).filter(Boolean).map(Number); return `${prefix} ${Math.max(0, ...used) + 1}`; }
  executionAgentBasePrompt(execution) { return `You are the single durable BDFL execution agent for ${execution.planId}. You retain this provider conversation across verification, explicitly accepted repairs, consolidation conflict repair, and final target reconciliation. Only implementation workers are isolated. BDFL will send one phase instruction at a time. Verification phases are read-only; repair and reconciliation phases may edit only the named generated worktree and approved paths. Never modify the target checkout directly, never infer or start a phase transition yourself, and call bdfl_workers complete with state pass or fail only when the current phase instruction is finished.`; }
  executionAgentPrompt({ integration, result, allowedPaths = [], phase, context }) { const paths = allowedPaths.length ? allowedPaths.join(', ') : 'the approved plan path union'; if (['verification', 'verification-retry'].includes(phase)) { const repaired = integration.verificationPurpose === 'remedy-verification'; const stage = repaired ? 'This verification follows an accepted repair.' : integration.verificationPurpose === 'target-reconciliation' ? 'This verifies the reconciled target result immediately before integration completes.' : 'This is the initial consolidated verification.'; return `Execution phase: verification. ${stage} This phase is read-only. Do not edit files. Inspect the active result in ${integration.worktree}, its entire diff, and every approved plan section at ${context}. Perform one comprehensive audit and do not stop after the first defect. If anything fails, report all findings together with numbered evidence, affected chunk IDs, and a concrete remedy for each. If verification fails, wait in this same conversation for the user's remedy decision; do not start repairs until BDFL sends an accepted-remedy continuation.`; } if (phase === 'verification-remedy') return `Execution phase: accepted verification remedy. The user accepted verifier remedies. Work only in ${integration.worktree}; changes are restricted to ${paths}.\n\n${result?.message || 'Inspect the recorded verifier failure.'}\n\nRead the full verifier context at ${context || integration.context}. Implement every remedy with regression coverage, then audit the entire consolidated change and all acceptance conditions. Fix additional defects you find, rerun focused checks, and repeat until clean. Do not report pass merely because existing tests pass. BDFL runs global validation after your report.`; if (phase === 'target' || phase === 'target-validation') return `Execution phase: target reconciliation. Work only in the active reconciliation worktree ${integration.worktree}; changes are restricted to ${paths}. ${phase === 'target-validation' ? 'Repair the failed reconciled validation while preserving both committed intents.' : 'Resolve the target conflict by preserving both the committed target changes and the approved BDFL result.'}\n\n${result?.message || ''}\n\nInspect the approved plan, your earlier verification/repair decisions, and Git history. Run focused checks, then report only when the reconciled tree is clean.`; return `Execution phase: consolidation repair. Resolve the worker consolidation conflict in ${integration.worktree}; changes are restricted to ${paths}.\n\n${result?.message || ''}\n\nPreserve the approved plan intent and your full execution context. BDFL runs global checks after you report.`; }
  launchExecutionAgent(value) { const { execution, agent, profile } = value; const prompt = this.executionAgentPrompt(value); const roleInstruction = this.executionAgentBasePrompt(execution); const workspaceRoot = path.join(execution.repositoryRoot || this.root, '.bdfl', 'worktrees'); const existing = agent?.sessionId && this.store.load().sessions.find((session) => session.id === agent.sessionId); if (existing?.role === 'integration') { this.store.update?.((state) => { const current = state.sessions.find((session) => session.id === existing.id); if (current) current.roleInstruction = roleInstruction; return state; }); this.markTurn(existing.id, 'working', `managed ${value.phase || 'phase'}`); if (!(this.sessions.isOpen?.(existing.id) ?? (!existing.explicitlyClosed && existing.status === 'running'))) this.sessions.open(existing.id, this.dimensions()); this.sessions.continueWhenReady?.(existing.id, prompt); return { sessionId: existing.id }; } const session = this.store.createSession(execution.workstreamId, 'integration', profile, { name: this.nextManagedName(execution.workstreamId, 'Execution'), executionId: execution.id, worktree: workspaceRoot, taskSnippet: `Execute and verify ${execution.planId}`, turnState: 'working', turnStateReason: `managed ${value.phase || 'phase'}`, roleInstruction }); this.sessions.open(session.id, this.dimensions()); this.sessions.continueWhenReady?.(session.id, prompt); return { sessionId: session.id, ...(existing ? { replacesSessionId: existing.id } : {}) }; }
  launchVerifier(value) { return this.launchExecutionAgent({ ...value, phase: value.phase || 'verification' }); }
  launchIntegrationWorker(value) { return this.launchExecutionAgent(value); }
  recoverIncompleteVerifications() { const errors = []; for (const execution of this.scheduler.list?.().filter((item) => item.status === 'verifying') || []) { const sessionId = execution.integration?.agent?.sessionId || execution.integration?.verifier?.sessionId; const session = this.store.load().sessions.find((item) => item.id === sessionId); const open = sessionId && (this.sessions.isOpen?.(sessionId) ?? Boolean(session && !session.explicitlyClosed && session.status === 'running')); try { if (open) this.sessions.continueWhenReady?.(sessionId, VERIFIER_CONTINUATION); else { if (session && !session.explicitlyClosed) this.sessions.close?.(sessionId, true); this.integration.retryVerification?.(execution.id, { sessionId, reason: 'Execution agent was unavailable when the BDFL supervisor restored verification' }); } } catch (error) { errors.push({ executionId: execution.id, error }); } } return errors; }
  recoverIncompleteIntegrations() { const errors = []; for (const execution of this.scheduler.list?.().filter((item) => item.status === 'integration-conflict') || []) { const sessionId = execution.integration?.agent?.sessionId || execution.integration?.worker?.sessionId; const session = this.store.load().sessions.find((item) => item.id === sessionId); const open = sessionId && (this.sessions.isOpen?.(sessionId) ?? Boolean(session && !session.explicitlyClosed && session.status === 'running')); try { if (open) this.sessions.continueWhenReady?.(sessionId, INTEGRATION_CONTINUATION); else if (session?.role === 'integration') { try { this.sessions.open?.(sessionId, this.dimensions()); this.sessions.continueWhenReady?.(sessionId, INTEGRATION_CONTINUATION); } catch { this.integration.repaired?.(execution.id, { state: 'fail', summary: 'Execution agent was unavailable when the BDFL supervisor restored repair or reconciliation' }); } } else { if (session && !session.explicitlyClosed) this.sessions.close?.(sessionId, true); this.integration.repaired?.(execution.id, { state: 'fail', summary: 'Conflict-resolution agent was unavailable when the BDFL supervisor restored the execution' }); } } catch (error) { errors.push({ executionId: execution.id, error }); } } return errors; }
  reconcileManagedSessions() {
    if (!this.scheduler.list) return [];
    const active = new Set(); const interactiveWorkerStates = new Set(['running', 'waiting', 'review', 'failed']);
    for (const execution of this.scheduler.list() || []) {
      if (!['complete', 'cancelled'].includes(execution.status)) for (const chunk of execution.chunks || []) { const attempt = chunk.attempts?.at(-1); if (attempt?.sessionId && interactiveWorkerStates.has(chunk.status)) active.add(attempt.sessionId); }
      const agentId = execution.integration?.agent?.sessionId; if (agentId && !['complete', 'cancelled'].includes(execution.status)) active.add(agentId);
      const verifierId = execution.integration?.verifier?.sessionId; const verifierAttempt = execution.integration?.verifierAttempts?.findLast((attempt) => attempt.sessionId === verifierId); if (execution.status === 'verifying' && verifierId && (!verifierAttempt || !verifierAttempt.completedAt && !verifierAttempt.result)) active.add(verifierId);
      const workerId = execution.integration?.worker?.sessionId; const repairAttempt = execution.integration?.repairAttempts?.findLast((attempt) => attempt.sessionId === workerId); if (execution.status === 'integration-conflict' && workerId && (!repairAttempt || !repairAttempt.completedAt && !repairAttempt.result)) active.add(workerId);
    }
    const errors = [];
    for (const session of this.store.load().sessions.filter((item) => ['worker', 'verifier', 'integration'].includes(item.role) && item.executionId && !item.explicitlyClosed && !active.has(item.id))) { try { this.sessions.close?.(session.id, true); } catch (error) { errors.push({ executionId: session.executionId, sessionId: session.id, error }); } }
    return errors;
  }
  closeInactiveManagedAgents() { return this.reconcileManagedSessions(); }
  closeInactiveIntegrationAgents() { return this.reconcileManagedSessions(); }
  lockFiles() { return [...new Set([this.root, ...(this.store.lockRoots?.() || [])].map((directory) => path.join(directory, '.bdfl', 'run', 'supervisor.lock')))].sort(); }
  acquireFile(file) { fs.mkdirSync(path.dirname(file), { recursive: true }); for (let attempt = 0; attempt < 2; attempt += 1) { try { const descriptor = fs.openSync(file, 'wx', 0o600); fs.writeFileSync(descriptor, `${process.pid}\n`); return descriptor; } catch (error) { if (error.code !== 'EEXIST') throw error; let owner; try { owner = Number.parseInt(fs.readFileSync(file, 'utf8'), 10); } catch {} let alive = Number.isInteger(owner) && owner > 0; if (alive) { try { process.kill(owner, 0); } catch (probe) { if (probe.code === 'ESRCH') alive = false; } } if (alive || attempt) { const conflict = new Error(`Another BDFL supervisor owns ${path.dirname(path.dirname(path.dirname(file)))}`); conflict.code = 'WORKSPACE_LOCKED'; throw conflict; } try { fs.unlinkSync(file); } catch (remove) { if (remove.code !== 'ENOENT') throw remove; } } } }
  acquire() { try { for (const file of this.lockFiles()) this.locks.push({ file, descriptor: this.acquireFile(file) }); this.lock = this.locks[0]?.descriptor; } catch (error) { this.release(); throw error; } }
  release() { for (const { file, descriptor } of this.locks.splice(0).reverse()) { try { fs.closeSync(descriptor); } catch {} try { fs.unlinkSync(file); } catch (error) { if (error.code !== 'ENOENT') throw error; } } this.lock = undefined; }
  dimensions() { return { columns: Math.max(20, (this.output.columns || 100) - 4), rows: Math.max(1, (this.output.rows || 28) - 3) }; }
  planItems() { return createdOrder(this.lineage.list?.() || []); }
  planAgentLines(lineage, prefix = '') { const workspace = this.workspace || this.store.load(); const planning = workspace.sessions.find((session) => session.id === lineage.originSessionId); const stream = workspace.workstreams.find((item) => item.id === lineage.workstreamId); const planningText = planning?.name || 'Unavailable'; const profile = stream?.workerProfile; const workerText = stream && profile ? `${display(profile.provider)}${profile.model ? ` ${profile.model}` : ''}${profile.effort ? ` · ${profile.effort} effort` : ''} · max ${stream.workerCapacity}` : 'Unavailable'; const row = (connector, label, detail) => `${COLORS.gray}${prefix}${connector}${COLORS.reset} ${COLORS.bold}${COLORS.white}${label}${COLORS.reset}${COLORS.gray} · ${detail}${COLORS.reset}`; return [row('├─', 'Planning agent', planningText), row('└─', 'Worker agent', workerText)]; }
  versionExecution(planId, version) { return (this.scheduler.list?.() || []).find((execution) => execution.planId === planId && execution.version === version) || null; }
  reviewItems(workspace = this.workspace || this.store.load()) {
    let executions = this.scheduler.list?.();
    if (!executions) { const directory = path.join(this.root, '.bdfl', 'executions'); let entries; try { entries = fs.readdirSync(directory, { withFileTypes: true }); } catch { entries = []; } executions = entries.filter((entry) => entry.isDirectory()).flatMap((entry) => { try { return [JSON.parse(fs.readFileSync(path.join(directory, entry.name, 'execution.json'), 'utf8'))]; } catch { return []; } }); }
    const lineages = new Map((this.lineage.list?.() || []).map((lineage) => [lineage.planId, lineage]));
    const decorate = (execution, item, sessionId) => {
      const lineage = lineages.get(execution.planId); const workstreamId = execution.workstreamId || lineage?.workstreamId; const planning = workspace.sessions.find((session) => session.id === lineage?.originSessionId) || workspace.sessions.find((session) => session.workstreamId === workstreamId && session.role === 'delegator'); const agent = workspace.sessions.find((session) => session.id === sessionId); const planningName = planning ? fallbackName(planning, workspace.workstreams.find((stream) => stream.id === workstreamId), workspace) : 'Planning agent unavailable'; const agentName = agent?.name; return { ...item, executionId: execution.id, planId: execution.planId, planTitle: lineage?.title || 'Untitled plan', agentLabel: agentName ? `${planningName} (${agentName})` : planningName, repositoryRoot: execution.repositoryRoot };
    };
    return executions.flatMap((execution) => {
      const chunks = (execution.chunks || []).filter((chunk) => { const sessionId = chunk.attempts?.at(-1)?.sessionId; const session = workspace.sessions.find((item) => item.id === sessionId); return ['review', 'waiting', 'failed', 'accepted'].includes(chunk.status) || chunk.status === 'running' && session?.attention || chunk.summary || chunk.diff || chunk.commit || chunk.feedback?.length; }).map((chunk) => { const sessionId = chunk.attempts?.at(-1)?.sessionId; const session = workspace.sessions.find((item) => item.id === sessionId); let diff = chunk.diff; try { diff = this.git.resultDiff?.(chunk, execution.repositoryRoot || this.root) || diff; } catch {} return decorate(execution, { ...chunk, attention: Boolean(session?.attention), diff, kind: 'chunk' }, sessionId); });
      if (execution.integration) { const sessionId = execution.integration?.agent?.sessionId || (execution.status === 'integration-conflict' ? execution.integration?.worker?.sessionId : execution.integration?.verifier?.sessionId); chunks.push(decorate(execution, { id: 'combined-result', kind: 'final', status: execution.status, summary: execution.status === 'integration-checking' ? 'Running bounded global validation in the background.' : execution.verification?.summary, diff: execution.integration?.finalDiff, checks: execution.integration?.checkResults || [], verification: execution.verification }, sessionId)); }
      return chunks;
    });
  }
  decorateWorkspace(workspace) {
    const visual = new Map(); const mark = (sessionId, values) => { if (sessionId) visual.set(sessionId, { ...(visual.get(sessionId) || {}), ...values }); };
    for (const execution of this.scheduler.list?.() || []) {
      for (const chunk of execution.chunks || []) { const attempts = chunk.attempts || []; attempts.forEach((attempt, index) => mark(attempt.sessionId, index < attempts.length - 1 ? { superseded: true, chunkTitle: chunk.title || chunk.taskSnippet || chunk.id } : { chunkTitle: chunk.title || chunk.taskSnippet || chunk.id, attemptStatus: chunk.status, accepted: chunk.status === 'accepted', completed: ['complete', 'completed'].includes(chunk.status) })); }
      const verifierAttempts = execution.integration?.verifierAttempts || []; verifierAttempts.forEach((attempt, index) => mark(attempt.sessionId, index < verifierAttempts.length - 1 || attempt.result ? { superseded: index < verifierAttempts.length - 1, completed: Boolean(attempt.result), workerPhase: 'Review', executionStatus: execution.status } : { workerPhase: 'Review', attemptStatus: execution.status, executionStatus: execution.status }));
      const repairAttempts = execution.integration?.repairAttempts || []; repairAttempts.forEach((attempt, index) => mark(attempt.sessionId, index < repairAttempts.length - 1 || attempt.result ? { superseded: index < repairAttempts.length - 1, completed: Boolean(attempt.result), workerPhase: 'Integration', executionStatus: execution.status } : { workerPhase: 'Integration', attemptStatus: execution.status, executionStatus: execution.status }));
    }
    const published = new Set(this.planItems().map((lineage) => lineage.originSessionId).filter(Boolean)); const decorated = { ...workspace, sessions: (workspace.sessions || []).map((session) => { const metadata = visual.get(session.id) || {}; let turnState = session.turnState; if (!turnState) { const completedTurn = metadata.accepted || metadata.completed || metadata.superseded || ['waiting', 'review', 'failed'].includes(metadata.attemptStatus) || published.has(session.id) || session.role === 'direct' && session.attention; turnState = completedTurn ? 'idle' : !session.explicitlyClosed && session.status === 'running' ? 'working' : undefined; } return { ...session, ...metadata, ...(turnState ? { turnState } : {}) }; }) }; return { ...decorated, planCount: this.planItems().length, reviewCount: this.reviewItems(decorated).length };
  }
  sessionPickerItems(workspace = this.workspace || this.store.load()) { return createdOrder(workspace.workstreams || []); }
  sessionPickerRows(workspace = this.workspace || this.store.load()) { return this.sessionPickerItems(workspace).flatMap((stream) => { const sessions = workspace.sessions.filter((session) => session.workstreamId === stream.id && (primaryRole(session.role) || ['worker', 'verifier', 'integration'].includes(session.role))).sort((a, b) => (a.paneNumber || 0) - (b.paneNumber || 0)); const primary = sessions.find((session) => primaryRole(session.role)); if (!primary) return []; return [{ stream, session: primary, header: true }, ...sessions.filter((session) => session.id !== primary.id).map((session) => ({ stream, session, header: false }))]; }); }
  syncSessionPicker(rows) { let index = rows.findIndex(({ session }) => session.id === this.sessionPicker.sessionId); if (index < 0) index = Math.min(this.sessionPicker.index || 0, Math.max(0, rows.length - 1)); this.sessionPicker.index = Math.max(0, index); this.sessionPicker.sessionId = rows[index]?.session.id || null; return this.sessionPicker.index; }
  actionPageLines() {
    if (!this.topPage) return null; const plans = this.topPage.action === 'Plans'; const items = plans ? this.planItems() : this.reviewItems();
    if (this.topPage.detail && plans) {
      const detail = this.topPage.detail; const lineage = this.lineage.load(detail.planId); const version = Math.min(detail.version, lineage.currentVersion); const manifest = this.lineage.readManifest(lineage.planId, version); const sections = [manifest.shared, ...manifest.chunks, manifest.globalValidation]; const selected = Math.min(detail.sectionIndex || 0, sections.length - 1); const section = sections[selected]; const approved = manifest.approvals[section.id]?.sectionSha === section.sha; const approvedCount = sections.filter((item) => manifest.approvals[item.id]?.sectionSha === item.sha).length; const latest = version === lineage.currentVersion; const versionLabel = latest ? lineage.currentVersion === 1 ? 'Latest' : `v${version} of ${lineage.currentVersion} · Latest` : `Older version — v${lineage.currentVersion} is latest`; const execution = this.versionExecution(lineage.planId, version); const columns = this.dimensions().columns; let content = [];
      if (detail.reader) content = this.lineage.readSection(lineage.planId, version, section.id).trimEnd().split('\n');
      else if (detail.diff && version > 1) { const before = fs.readFileSync(path.join(this.lineage.versionDirectory(lineage.planId, version - 1), 'consolidated.md'), 'utf8'); const after = fs.readFileSync(path.join(this.lineage.versionDirectory(lineage.planId, version), 'consolidated.md'), 'utf8'); content = diffViewLines(require('../core/plans').diffLines(before, after), columns); }
      else content = sections.map((item, index) => { const status = manifest.approvals[item.id]?.sectionSha === item.sha ? `${COLORS.green}Approved${COLORS.reset}` : 'Needs approval'; const kind = item.id === 'shared' ? 'Shared decisions' : item.id === 'global-validation' ? 'Global validation' : `Worker chunk · ${item.id}`; return `${index === selected ? '›' : ' '} ${kind} · ${status}`; });
      if (!detail.diff) content = softWrap(content, columns); const scrollable = detail.reader || detail.diff; const bodyRows = Math.max(1, this.dimensions().rows - 9); const maxScroll = Math.max(0, content.length - bodyRows); detail.scroll = Math.min(detail.scroll || 0, maxScroll); const visible = scrollable ? content.slice(detail.scroll, detail.scroll + bodyRows) : content; const contextual = approved ? 'a remove approval' : 'a approve'; let actions = detail.reader ? `↑/↓ scroll  •  ${contextual}` : detail.diff ? `↑/↓ scroll  •  ←/→ version  •  d close diff` : `↑/↓ section  •  ←/→ version  •  Enter read  •  ${contextual}`;
      if (!detail.reader && !detail.diff) { if (version > 1) actions += `  •  d diff v${version - 1} → v${version}`; if (execution) actions += `  •  Execution ${execution.status}`; else if (approvedCount === sections.length) actions += `  •  e execute v${version}`; }
      const approvalStatus = approved ? `${COLORS.green}Approved${COLORS.reset}` : `${COLORS.gray}Needs approval${COLORS.reset}`; const summary = detail.reader ? `${COLORS.gray}${versionLabel} · ${selected + 1} of ${sections.length} approval sections · ${COLORS.reset}${approvalStatus}` : `${COLORS.gray}${versionLabel} · ${sections.length} approval sections · ${manifest.chunks.length} isolated implementation worker${manifest.chunks.length === 1 ? '' : 's'} + 1 execution agent${COLORS.reset}`; const header = [`${COLORS.yellow}${manifest.title} · v${version} of ${lineage.currentVersion}${COLORS.reset}`, summary, ''];
      if (detail.diff) header.push(`${COLORS.white}Diff v${version - 1} → v${version}${COLORS.reset}`, '');
      if (detail.confirmExecute) return [...header, `${COLORS.red}Execute v${version} even though v${lineage.currentVersion} is newer?${COLORS.reset}`, `${COLORS.cyan}Enter confirms · Esc cancels${COLORS.reset}`];
      const actionLines = softWrapLine(`${actions}  •  Esc back`, columns).map((line) => `${COLORS.cyan}${line}${COLORS.reset}`); const tipLines = detail.reader || detail.diff ? [] : softWrapLine('Tip: Approve all sections to execute the plan', columns).map((line) => `${COLORS.gray}${line}${COLORS.reset}`); return [...header, ...visible, scrollable && maxScroll ? `${COLORS.gray}${detail.scroll + 1}–${Math.min(content.length, detail.scroll + bodyRows)} of ${content.length}${COLORS.reset}` : '', '', ...actionLines, ...tipLines];
    }
    if (this.topPage.detail && !plans) {
      const detail = this.topPage.detail; const item = items.find((candidate) => candidate.executionId === detail.executionId && candidate.id === detail.id); if (!item) return ['No review item is available.'];
      const columns = this.dimensions().columns; this.reviewView.update(item); const requestedScroll = this.reviewView.state().scroll; const descriptor = stateDescriptor(item); const header = [...softWrapLine(`${item.agentLabel} · ${item.planTitle}`, columns).map((line) => `${COLORS.yellow}${line}${COLORS.reset}`), `${descriptor.tone === 'red' ? COLORS.red : descriptor.tone === 'green' ? COLORS.green : COLORS.gray}${descriptor.label}${COLORS.reset}`, '']; let controls;
      const confirmation = this.reviewView.state().confirmation;
      if (this.topPage.feedback) { const label = this.topPage.feedback.kind === 'remedy' ? 'Repair guidance' : 'Feedback'; controls = ['', ...softWrapLine(`${label}: ${this.topPage.feedback.value}`, columns).map((line) => `${COLORS.yellow}${line}${COLORS.reset}`), ...(this.topPage.feedback.error ? softWrapLine(`! ${this.topPage.feedback.error}`, columns).map((line) => `${COLORS.red}${line}${COLORS.reset}`) : []), `${COLORS.cyan}Enter ${this.topPage.feedback.error ? 'retry' : 'send'} • Esc cancel${COLORS.reset}`]; }
      else if (confirmation) { const prompt = confirmation === 'integrate' ? 'Integrate this verified result into the frozen target?' : confirmation === 'override' ? 'Override failed global verification and integrate anyway?' : 'Continue the execution agent with the accepted verifier remedies?'; controls = ['', `${confirmation === 'remedy' ? COLORS.yellow : COLORS.red}${prompt}${COLORS.reset}`, `${COLORS.cyan}Enter confirms • Esc cancels${COLORS.reset}`]; }
      else { const actions = descriptor.actions.map((action) => action === 'accept' ? 'a accept' : action === 'feedback' ? item.kind === 'final' ? 'f suggest repair' : 'f feedback' : action === 'integrate' ? 'i integrate' : action === 'override' ? 'o override' : action === 'remedy' ? 'r accept remedies' : action); if (this.reviewView.selections().length) actions.push('u remove last selection', 'c clear selections'); controls = ['', ...softWrapLine(`↑/↓ scroll • ${actions.length ? actions.join(' • ') : descriptor.label} • Esc back`, columns).map((line) => `${COLORS.cyan}${line}${COLORS.reset}`)]; }
      const availableRows = Math.max(0, this.dimensions().rows - header.length - controls.length); let bodyRows = availableRows; let position = false; if (bodyRows > 0) { this.reviewView.resize(columns, bodyRows); if (this.reviewView.maximumScroll() > 0 && bodyRows > 1) { bodyRows -= 1; position = true; this.reviewView.resize(columns, bodyRows); } } else this.reviewView.resize(columns, 1); this.reviewView.scrollTo(requestedScroll); const frame = bodyRows > 0 ? this.reviewView.render({ bodyTop: 3 + header.length, bodyLeft: 4, bodyWidth: columns }) : { lines: [], offset: this.reviewView.scrollTo(0), maxScroll: this.reviewView.maximumScroll() }; detail.scroll = frame.offset; const bodyLength = this.reviewView.bodyRows().length; return [...header, ...frame.lines, ...(position ? [`${COLORS.gray}${frame.offset + 1}–${Math.min(bodyLength, frame.offset + bodyRows)} of ${bodyLength}${COLORS.reset}`] : []), ...controls];
    }
    const title = plans ? 'Plans' : 'Ready for review'; const description = plans ? 'Browse durable implementation plans created in this workspace.' : 'Review worker results, questions, failures, and combined output.'; const columns = this.dimensions().columns; const notice = [];
    if (plans && this.topPage.deleteConfirmation) { const deletion = this.topPage.deleteConfirmation; notice.push(`${COLORS.red}${COLORS.bold}Delete ${deletion.count} plan${deletion.count === 1 ? '' : 's'} permanently?${COLORS.reset}`, `${COLORS.red}Only BDFL plan lineage and versions are removed. Executions, sessions, Git history, worktrees, and provider transcripts are preserved.${COLORS.reset}`, `${COLORS.cyan}Enter confirms · Esc cancels${COLORS.reset}`, ''); }
    else if (plans && this.topPage.deleteError) notice.push(`${COLORS.red}! ${this.topPage.deleteError}${COLORS.reset}`, '');
    const controls = plans ? '↑/↓ choose  •  Enter open  •  d delete  •  D delete all  •  Esc back' : '↑/↓ choose  •  Enter open  •  Esc back'; return [`${COLORS.yellow}${title}${COLORS.reset}`, `${COLORS.gray}${description}${COLORS.reset}`, '', ...notice, ...items.flatMap((item, index) => { const selected = index === this.topPage.index; const name = plans ? item.title || item.planId : `${item.agentLabel} · ${item.planTitle}`; const plainStatus = plans ? `Latest v${item.currentVersion}` : item.status || 'Needs review'; const status = plans || item.status === 'accepted' ? `${COLORS.green}${plainStatus}${COLORS.reset}` : `${COLORS.yellow}${plainStatus}${COLORS.reset}`; const relativeRepository = item.repositoryRoot ? path.relative(this.root, item.repositoryRoot) : null; const repository = item.repository && item.repository !== '.' ? item.repository : relativeRepository || null; const detail = plans ? [repository, `Created at: ${formatLocalDateTime(item.createdAt) || 'recently'}`].filter(Boolean).join(' · ') : [repository, item.summary || `${item.changedPaths?.length || 0} changed paths`].filter(Boolean).join(' · '); if (plans) return [`${selected ? `${COLORS.inverse}${COLORS.bold} › ${name} ${COLORS.reset}` : `   ${COLORS.bold}${COLORS.white}${name}${COLORS.reset}`}  ${status}`, `${COLORS.gray}   ${detail}${COLORS.reset}`, ...(selected ? this.planAgentLines(item, '   ') : []), '']; const headingRows = softWrapLine(`${selected ? ' ›' : '  '} ${name}`, columns); const appendStatus = width(headingRows.at(-1)) + width(plainStatus) + 2 <= columns; const heading = headingRows.map((line) => selected ? `${COLORS.inverse}${COLORS.bold}${line}${COLORS.reset}` : `${COLORS.bold}${COLORS.white}${line}${COLORS.reset}`); if (appendStatus) heading[heading.length - 1] += `  ${status}`; else heading.push(`   ${status}`); const details = softWrapLine(`   ${detail}`, columns).map((line) => `${COLORS.gray}${line}${COLORS.reset}`); return [...heading, ...details, '']; }), `${COLORS.cyan}${controls}${COLORS.reset}`];
  }
  sessionPickerLines() {
    this.contentHits ||= []; const rows = this.sessionPickerRows(); this.syncSessionPicker(rows); const streams = this.sessionPickerItems();
    const lines = [`${COLORS.yellow}Your sessions${COLORS.reset}`, `${COLORS.gray}Open a running session or resume one you closed earlier.${COLORS.reset}`, ''];
    if (this.sessionPicker.confirmDelete === 'all') { const state = this.store.load(); lines.push(`${COLORS.red}${COLORS.bold}Delete all ${state.workstreams.length} workstream${state.workstreams.length === 1 ? '' : 's'} and ${state.sessions.length} session${state.sessions.length === 1 ? '' : 's'} permanently?${COLORS.reset}`, `${COLORS.red}Saved configuration, plans, executions, Git history, worktrees, and provider-retained transcripts are preserved.${COLORS.reset}`, `${COLORS.cyan}Enter confirms · Esc cancels${COLORS.reset}`, ''); }
    else if (this.sessionPicker.deleteError) lines.push(`${COLORS.red}! ${this.sessionPicker.deleteError}${COLORS.reset}`, '');
    for (const stream of streams) {
      const group = rows.filter((row) => row.stream.id === stream.id); const planning = group.find((row) => row.header); if (!planning) continue;
      const selected = group.find((row) => row.session.id === this.sessionPicker.sessionId); const planningSelected = selected?.header; const deleting = planningSelected && this.sessionPicker.confirmDelete === stream.id; const editingPlanning = this.sessionPicker.edit?.workstreamId === stream.id;
      const planningName = editingPlanning ? `${this.sessionPicker.edit.value}${COLORS.bgCyan}${COLORS.black} ${COLORS.reset}` : stream.name || fallbackName(planning.session, stream, this.workspace);
      const deletingCount = this.workspace.sessions.filter((session) => session.workstreamId === stream.id).length; const groupStatus = deleting ? `${COLORS.red}${COLORS.bold}Delete ${deletingCount} session${deletingCount === 1 ? '' : 's'} permanently?${COLORS.reset}` : stream.status === 'closed' ? `${COLORS.yellow}Ready to resume${COLORS.reset}` : `${COLORS.green}Running${COLORS.reset}`;
      const created = formatLocalDateTime(stream.createdAt); const location = stream.repository && stream.repository !== '.' ? stream.repository : stream.title || path.basename(stream.repositoryRoot || this.root); const summary = [location, created ? `Created at: ${created}` : ''].filter(Boolean).join(' · ');
      const description = deleting ? `${COLORS.red}Press Enter to confirm · Esc to keep this workstream${COLORS.reset}` : `${COLORS.gray}${summary}${COLORS.reset}`;
      const headerRow = lines.length + 1; lines.push(`${planningSelected ? `${COLORS.inverse}${COLORS.bold} › ${planningName} ${COLORS.reset}` : `   ${COLORS.bold}${COLORS.white}${planningName}${COLORS.reset}`}  ${groupStatus}${planningSelected && !deleting && !editingPlanning ? `  ${COLORS.yellow}[Rename] [Delete]${COLORS.reset}` : ''}`, `   ${description}`); this.contentHits.push({ type: 'session-row', row: headerRow, start: 4, end: Math.max(4, width(planningName) + 3), sessionId: planning.session.id, workstreamId: stream.id, index: rows.indexOf(planning) }); if (planningSelected && !deleting && !editingPlanning) { const plain = lines.at(-2).replace(/\u001b\[[0-?]*[ -/]*[@-~]/gu, ''); for (const [type, text] of [['session-rename', '[Rename]'], ['session-delete', '[Delete]']]) { const start = plain.indexOf(text) + 1; this.contentHits.push({ type, row: headerRow, start, end: start + text.length - 1, workstreamId: stream.id }); } }
      for (const [index, row] of group.entries()) {
        const childSelected = !row.header && row.session.id === this.sessionPicker.sessionId; const connector = index === group.length - 1 ? '└─' : '├─'; const provider = display(row.session.profile?.provider || stream.delegatorProfile?.provider || stream.directProfile?.provider || 'agent'); const status = row.session.status === 'running' ? row.session.turnState === 'idle' ? `${COLORS.gray}Idle${COLORS.reset}` : `${COLORS.yellow}Working${COLORS.reset}` : row.session.status === 'bridge-reconnecting' ? `${COLORS.yellow}Bridge reconnecting${COLORS.reset}` : row.session.status === 'bridge-error' ? `${COLORS.red}Bridge error${COLORS.reset}` : row.session.explicitlyClosed ? `${COLORS.gray}Closed${COLORS.reset}` : `${COLORS.yellow}Saved${COLORS.reset}`; const name = row.header ? row.session.role === 'direct' ? 'Direct agent' : 'Planning agent' : fallbackName(row.session, stream, this.workspace); const task = row.session.taskSnippet ? ` ${COLORS.gray}· Last Prompt: ${promptPreview(row.session.taskSnippet)}${COLORS.reset}` : '';
        const body = `${COLORS.bold}${COLORS.white}${name}${COLORS.reset} ${COLORS.gray}· ${provider}${COLORS.reset}  ${status}${task}`; const childRow = lines.length + 1; lines.push(`${COLORS.gray}   ${connector}${COLORS.reset} ${childSelected ? `${COLORS.inverse} ${body} ${COLORS.reset}` : body}`); if (!row.header) this.contentHits.push({ type: 'session-row', row: childRow, start: 4, end: Math.max(4, Math.min(this.dimensions().columns, width(lines.at(-1)))), sessionId: row.session.id, workstreamId: stream.id, index: rows.indexOf(row) });
      }
      lines.push('');
    }
    if (this.sessionPicker.edit?.error) lines.push(`${COLORS.red}! ${this.sessionPicker.edit.error}${COLORS.reset}`, '');
    const controls = `${COLORS.cyan}↑/↓ scroll  •  Click open  •  Group rename/delete  •  D delete all  •  Esc back${COLORS.reset}`; const body = lines.slice(3); const available = Math.max(1, this.dimensions().rows - 5); const maximum = Math.max(0, body.length - available); this.sessionPicker.scroll = Math.min(this.sessionPicker.scroll || 0, maximum); const start = this.sessionPicker.scroll; const end = start + available; const visibleHits = this.contentHits.filter((hit) => hit.row <= 3 || hit.row - 4 >= start && hit.row - 4 < end).map((hit) => hit.row <= 3 ? hit : { ...hit, row: hit.row - start }); this.contentHits.splice(0, this.contentHits.length, ...visibleHits); return [...lines.slice(0, 3), ...body.slice(start, end), ...(maximum ? [`${COLORS.gray}${start + 1}–${Math.min(body.length, end)} of ${body.length}${COLORS.reset}`] : []), controls];
  }
  selectedSession() { return this.navigation?.currentAgent()?.session || null; }
  focusedSessionId() { if (this.navigation?.rail !== 'content' || this.wizard || this.sessionPicker || this.topPage) return null; return this.navigation.sessionId || null; }
  visibleSessionId() { if (!this.navigation || this.error || this.wizard || this.sessionPicker || this.topPage) return null; return this.navigation.sessionId || null; }
  raiseAttention(sessionId) { const session = this.store.load().sessions.find((item) => item.id === sessionId); if (session?.role === 'direct') this.markTurn(sessionId, 'idle', 'provider completed'); if (this.focusedSessionId() === sessionId) { this.scheduleDraw(); return false; } this.store.setSessionAttention?.(sessionId, true); this.scheduleDraw(); return true; }
  clearFocusedAttention() { const sessionId = this.focusedSessionId(); if (sessionId) { this.store.setSessionAttention?.(sessionId, false); this.sessions.acknowledgeAttention?.(sessionId); } return sessionId; }
  focusAgent(sessionId, { draw = true } = {}) { this.workspace = this.decorateWorkspace(this.store.load()); this.navigation ||= new Navigation(this.workspace); this.navigation.sync(this.workspace); const agents = this.navigation.agents(); const selected = agents.find(({ session }) => session.id === sessionId); if (!selected) { if (draw) this.draw(); return false; } try { this.store.activateWorkstream?.(selected.stream.id); if (resumableSession(selected.session)) { if (this.sessions.resume) this.sessions.resume(selected.session.id, this.dimensions()); else this.sessions.open(selected.session.id, this.dimensions()); } else if (!terminalSession(selected.session)) this.sessions.open(selected.session.id, this.dimensions()); this.error = null; this.wizard = null; this.sessionPicker = null; this.topPage = null; this.workspace = this.decorateWorkspace(this.store.load()); this.navigation.sync(this.workspace); this.navigation.selectSession(selected.session.id); this.navigation.activeAction = null; this.navigation.rail = 'content'; this.lastFocused.set(selected.stream.id, selected.session.id); if (this.sessions.focus) this.sessions.focus(selected.session.id); else this.store.markSessionViewed?.(selected.session.id); this.store.setSessionAttention?.(selected.session.id, false); this.sessions.acknowledgeAttention?.(selected.session.id); } catch (error) { this.error = error; } if (draw) this.draw(); return !this.error; }
  focusParent(workstreamId) { const workspace = this.decorateWorkspace(this.store.load()); const stream = workspace.workstreams.find((item) => item.id === workstreamId); if (!stream) return this.draw(); const selected = agentSessions(workspace, stream).find((session) => primaryRole(session.role)); this.navigation.workstreamId = workstreamId; if (selected) return this.focusAgent(selected.id); return this.activate('Sessions'); }
  exitNative() { const wasWizard = Boolean(this.wizard); const previous = wasWizard ? this.previousSurface : null; const sessionId = previous?.sessionId || this.navigation?.sessionId; this.wizard = null; this.sessionPicker = null; this.topPage = null; this.navigation.activeAction = null; this.navigation.rail = 'content'; this.previousSurface = null; if (previous?.action && previous.action !== 'New') return this.activate(previous.action); if (sessionId && this.navigation.agents().some(({ session }) => session.id === sessionId)) return this.focusAgent(sessionId); if (wasWizard && (this.workspace?.sessions || []).length) return this.activate('Sessions'); return this.draw(); }
  openLink(url) { try { Promise.resolve(this.linkOpener(url)).catch((error) => { this.error = codedError('OPEN_EXTERNAL_FAILED', error.message); this.scheduleDraw(); }); } catch (error) { this.error = codedError('OPEN_EXTERNAL_FAILED', error.message); this.scheduleDraw(); } }
  activePlanExecutions(planIds) { const affected = new Set(planIds); return (this.scheduler.list?.() || []).filter((execution) => affected.has(execution.planId) && !['complete', 'cancelled'].includes(execution.status)); }
  deletePlans(deletion) { const blockers = this.activePlanExecutions(deletion.planIds); if (blockers.length) { const count = blockers.length; throw new Error(`Cannot delete: ${count} affected execution${count === 1 ? ' is' : 's are'} still active.`); } return deletion.scope === 'all' ? this.lineage.deleteAll() : this.lineage.delete(deletion.planIds[0]); }
  scheduleDraw() { if (!this.running || this.redrawScheduled) return; this.redrawScheduled = true; setImmediate(() => { this.redrawScheduled = false; if (this.running) this.draw(); }); }
  scheduleOutputDraw(sessionId) { if (!this.running || this.visibleSessionId() !== sessionId || this.outputDrawTimer !== undefined) return; this.outputDrawTimer = this.scheduleTimeout(() => { this.outputDrawTimer = undefined; if (this.running && this.visibleSessionId() === sessionId) this.draw(); }, 50); this.outputDrawTimer?.unref?.(); }
  drawScroll() { return false; }
  pageName() { if (this.wizard) return 'New'; if (this.sessionPicker) return 'Sessions'; if (this.topPage) return this.topPage.action; if (NATIVE_PAGES.has(this.navigation?.activeAction)) return this.navigation.activeAction; return null; }
  titleName() { const page = this.pageName(); if (page) return page; const current = this.navigation?.currentAgent(); if (!current) return null; const primary = this.workspace.sessions.find((session) => session.workstreamId === current.stream.id && primaryRole(session.role)); return fallbackName(primary || current.session, current.stream, this.workspace); }
  footerPresentation() { if (this.quitPending) return { message: QUIT_MESSAGE }; const page = this.pageName(); const index = page === 'Plans' ? 1 : page === 'Sessions' ? 2 : page === 'Reviews' ? 3 : page === 'New' ? 4 : 0; return { message: FOOTER_MESSAGES[index] }; }
  runningSessionIds() { return new Set((this.workspace?.sessions || []).filter((session) => this.sessions.isSessionActive?.(session.id) || this.sessions.isActive?.(session.id)).map((session) => session.id)); }
  draw() { this.workspace = this.decorateWorkspace(this.store.load()); this.navigation ||= new Navigation(this.workspace); this.navigation.sync(this.workspace); this.contentHits = []; const session = this.selectedSession(); const providerFocused = this.navigation.rail === 'content' && !this.navigation.activeAction; const picker = this.sessionPicker ? this.sessionPickerLines() : null; let presentation = null; if (session && !this.error && !this.wizard && !picker && !this.topPage) presentation = this.sessions.presentation?.(session.id, this.dimensions().rows, { cursor: providerFocused }) || { lines: this.sessions.screen?.(session.id, this.dimensions().rows, { cursor: providerFocused }) || [], cursor: null }; const content = this.error ? errorPageLines(this.error) : this.wizard ? this.wizard.render().split('\n') : picker || this.actionPageLines() || presentation?.lines || emptyStateLines(); const footer = this.footerPresentation(); const rendered = this.renderer.render(this.workspace, this.navigation, { columns: this.output.columns || 100, rows: this.output.rows || 28, content, footerMessage: footer.message, showBack: Boolean(this.wizard), isRunning: (id) => this.runningSessionIds().has(id) }); const relativeHits = this.wizard ? this.wizard.lastHits.map((hit) => ({ ...hit, row: hit.row + 3, start: hit.start + 3, end: hit.end + 3 })) : this.contentHits.map((hit) => ({ ...hit, row: hit.row + 1, start: hit.start + 3, end: hit.end + 3 })); this.renderer.lastLayout.hits.push(...relativeHits); const lines = rendered.split('\n'); const title = terminalTitle(this.titleName(), hasOpenAttention(this.workspace)); const output = []; if (!this.lastFrameLines || this.lastFrameLines.length !== lines.length) output.push(title, `${ESC}H`, rendered); else { if (title !== this.lastTerminalTitle) output.push(title); for (let index = 0; index < lines.length; index += 1) if (lines[index] !== this.lastFrameLines[index]) output.push(`${ESC}${index + 1};1H${lines[index]}`); } if (presentation?.cursor) output.push(`${ESC}?25h${ESC}${presentation.cursor.row + 2};${presentation.cursor.column + 4}H`); else output.push(`${ESC}?25l`); this.lastFrameLines = lines; this.lastTerminalTitle = title; if (output.length) this.output.write(output.join('')); }
  start() {
    this.acquire(); this.bridge.start?.(); if (this.bridge.error) throw codedError('BRIDGE_START_FAILED', this.bridge.error.message); this.running = true; this.scheduler.resume?.(); const preRestoreErrors = this.reconcileManagedSessions(); this.workspace = this.decorateWorkspace(this.store.load()); const openWorkstreams = new Set(this.workspace.workstreams.filter((stream) => stream.status !== 'closed').map((stream) => stream.id)); const hasOpenSession = this.workspace.workstreams.some((stream) => openWorkstreams.has(stream.id) && agentSessions(this.workspace, stream).some((session) => !pausedSession(session) && !terminalSession(session)));
    if (!hasOpenSession) { this.navigation = new Navigation(this.workspace); this.navigation.rail = 'content'; if (this.workspace.sessions.length) { const rows = this.sessionPickerRows(this.workspace); const selected = rows.find((row) => row.stream.id === this.workspace.activeWorkstreamId) || rows[0]; this.sessionPicker = { index: Math.max(0, rows.indexOf(selected)), sessionId: selected?.session.id || null }; this.navigation.activeAction = 'Sessions'; } else { this.wizard = this.createWizard(); this.navigation.activeAction = 'New'; } } else { this.navigation ||= new Navigation(this.workspace); this.navigation.rail = 'content'; }
    this.output.write(`${ESC}?1049h${ESC}?25l${ESC}?1000h${ESC}?1006h`); this.input.setRawMode?.(true); this.input.resume?.(); let restoreErrors = []; if (!this.wizard && this.sessions.restore) { const restored = this.sessions.restore(this.dimensions()); restoreErrors = restored?.errors || []; if (!restoreErrors.length) { const focused = this.clearFocusedAttention(); if (focused) { this.lastFocused.set(this.navigation.workstreamId, focused); if (this.sessions.focus) this.sessions.focus(focused); else this.store.markSessionViewed?.(focused); } } } const managedErrors = [...preRestoreErrors]; try { this.integration.resumeIntegrationQueue?.(); managedErrors.push(...this.reconcileManagedSessions()); } catch (error) { managedErrors.push({ executionId: 'integration-queue', error }); } managedErrors.push(...this.recoverIncompleteVerifications(), ...this.recoverIncompleteIntegrations()); if (restoreErrors.length || managedErrors.length) this.error = codedError('SESSION_RESTORE_FAILED', [...restoreErrors.map(({ sessionId, error }) => `${sessionId}: ${error.message}`), ...managedErrors.map(({ executionId, error }) => `${executionId}: ${error.message}`)].join(' · '));
    const handle = (value) => {
      if (value === '\u0003') { if (this.quitPending) { this.stop(); return false; } this.quitPending = true; this.quitTimer = this.scheduleTimeout(() => { this.quitTimer = undefined; if (!this.running || !this.quitPending) return; this.quitPending = false; this.draw(); }, QUIT_CONFIRMATION_TIMEOUT); this.quitTimer?.unref?.(); return this.draw(); }
      const shortcutLocked = Boolean(this.sessionPicker?.edit || this.sessionPicker?.confirmDelete || this.topPage?.feedback || this.topPage?.deleteConfirmation || this.topPage?.detail?.confirmExecute);
      const mouse = mouseEvent(value); if (mouse) { const sessionId = this.focusedSessionId(); const columns = this.output.columns || 100; const rows = this.output.rows || 28; const layout = this.renderer.lastLayout || this.renderer.layout(this.workspace, this.navigation, { columns, rows }); const hit = hitAt(layout, mouse.row, mouse.column); if (!shortcutLocked && isPrimaryClick(mouse) && hit) { if (hit.type === 'action') return this.activate(hit.action); if (hit.type === 'child') return this.focusAgent(hit.sessionId); if (hit.type === 'parent') return this.focusParent(hit.workstreamId); if (hit.type === 'link') { this.openLink(hit.url); return; } if (hit.type === 'back') return this.exitNative(); if (hit.type === 'wizard-option' && this.wizard) { this.wizard.selection = hit.index; const config = this.wizard.choose(); if (config) this.finishWizard(config); return this.draw(); } if (hit.type === 'session-row' && this.sessionPicker) { this.sessionPicker.index = hit.index; this.sessionPicker.sessionId = hit.sessionId; return handle('\r'); } if (hit.type === 'session-rename' && this.sessionPicker) { const stream = this.store.load().workstreams.find((item) => item.id === hit.workstreamId); this.sessionPicker.edit = { workstreamId: hit.workstreamId, value: stream?.name || 'Session', error: null }; return this.draw(); } if (hit.type === 'session-delete' && this.sessionPicker) { this.sessionPicker.confirmDelete = hit.workstreamId; return this.draw(); } } if (!shortcutLocked && this.topPage?.action === 'Reviews' && this.topPage.detail) { if (isVerticalWheel(mouse)) { this.reviewView.scroll((mouse.button & 1) === 0 ? -3 : 3); return this.draw(); } if (this.reviewView.handleMouse(mouse)) return this.draw(); } if (isVerticalWheel(mouse) && this.topPage?.detail && (this.topPage.detail.reader || this.topPage.detail.diff)) { this.topPage.detail.scroll = Math.max(0, (this.topPage.detail.scroll || 0) + ((mouse.button & 1) === 0 ? -3 : 3)); this.draw(); } else if (sessionId && isVerticalWheel(mouse) && mouse.column >= 4 && mouse.column <= columns - 1 && mouse.row >= 2 && mouse.row <= rows - 2) { const translated = { ...mouse, column: mouse.column - 3, row: mouse.row - 1 }; const lines = (mouse.button & 1) === 0 ? -3 : 3; this.sessions.scroll?.(sessionId, lines, translated); } return; }
      if (this.topPage) {
        const plans = this.topPage.action === 'Plans'; const items = plans ? this.planItems() : this.reviewItems();
        if (this.topPage.feedback) { if (value === '\u001b') this.topPage.feedback = null; else if (value === '\r') { try { const detail = this.topPage.detail; if (this.topPage.feedback.kind === 'remedy') this.integration.remedy(detail.executionId, this.topPage.feedback.value); else { const payload = this.reviewView.feedback(this.topPage.feedback.value); this.scheduler.feedback(detail.executionId, detail.id, payload, (executionId, chunkId, message) => this.sendWorker(executionId, chunkId, message)); } this.topPage.feedback = null; } catch (error) { this.topPage.feedback.error = error.message; } } else if (value === '\u007f' || value === '\b') this.topPage.feedback.value = [...this.topPage.feedback.value].slice(0, -1).join(''); else if (!/[\u0000-\u001f\u007f-\u009f]/u.test(value)) this.topPage.feedback.value += value; return this.draw(); }
        if (plans && this.topPage.deleteConfirmation) { if (value === '\u001b') this.topPage.deleteConfirmation = null; else if (value === '\r') { const deletion = this.topPage.deleteConfirmation; try { this.deletePlans(deletion); this.topPage.deleteConfirmation = null; this.topPage.deleteError = null; const remaining = this.planItems(); if (!remaining.length) return this.exitNative(); this.topPage.index = Math.min(this.topPage.index, remaining.length - 1); } catch (error) { this.topPage.deleteConfirmation = null; this.topPage.deleteError = error.message; } } return this.draw(); }
        if (this.topPage.detail) {
          if (plans) {
            const detail = this.topPage.detail; const lineage = this.lineage.load(detail.planId); const manifest = this.lineage.readManifest(detail.planId, detail.version); const count = manifest.chunks.length + 2;
            if (detail.confirmExecute) { if (value === '\u001b') detail.confirmExecute = false; else if (value === '\r') { try { this.scheduler.freeze(detail.planId, detail.version, manifest.workstreamId || this.navigation.workstreamId); detail.confirmExecute = false; } catch {} } return this.draw(); }
            if (value === 'q') { this.topPage.detail = null; return this.draw(); }
            if (value === '\u001b') { if (detail.reader || detail.diff) { detail.reader = false; detail.diff = false; detail.scroll = 0; } else this.topPage.detail = null; return this.draw(); }
            const scrolling = detail.reader || detail.diff;
            if (value === '\u001b[A') { if (scrolling) detail.scroll = Math.max(0, (detail.scroll || 0) - 1); else detail.sectionIndex = (detail.sectionIndex + count - 1) % count; }
            else if (value === '\u001b[B') { if (scrolling) detail.scroll = (detail.scroll || 0) + 1; else detail.sectionIndex = (detail.sectionIndex + 1) % count; }
            else if (value === '\u001b[5~' && scrolling) detail.scroll = Math.max(0, (detail.scroll || 0) - Math.max(1, this.dimensions().rows - 10));
            else if (value === '\u001b[6~' && scrolling) detail.scroll = (detail.scroll || 0) + Math.max(1, this.dimensions().rows - 10);
            else if (value === '\u001b[D') { detail.version = Math.max(1, detail.version - 1); detail.sectionIndex = 0; detail.scroll = 0; detail.diff = false; }
            else if (value === '\u001b[C') { detail.version = Math.min(lineage.currentVersion, detail.version + 1); detail.sectionIndex = 0; detail.scroll = 0; detail.diff = false; }
            else if (value === '\r' && !detail.reader && !detail.diff) { detail.reader = true; detail.scroll = 0; }
            else if (value === 'd' && !detail.reader && detail.version > 1) { detail.diff = !detail.diff; detail.scroll = 0; }
            else if (value === 'a' && !detail.diff) { const currentManifest = this.lineage.readManifest(detail.planId, detail.version); const section = [currentManifest.shared, ...currentManifest.chunks, currentManifest.globalValidation][detail.sectionIndex]; if (section) { const approved = currentManifest.approvals[section.id]?.sectionSha === section.sha; if (approved) this.lineage.removeApproval(detail.planId, detail.version, section.id); else this.lineage.approve(detail.planId, detail.version, section.id); } }
            else if (value === 'e' && !detail.reader && !detail.diff && !this.versionExecution(detail.planId, detail.version) && this.lineage.executable(detail.planId, detail.version)) { if (detail.version < lineage.currentVersion) detail.confirmExecute = true; else try { this.scheduler.freeze(detail.planId, detail.version, manifest.workstreamId || this.navigation.workstreamId); } catch {} }
          }
          else { const detail = this.topPage.detail; const item = items.find((candidate) => candidate.executionId === detail.executionId && candidate.id === detail.id); this.reviewView.update(item || { executionId: detail.executionId, id: detail.id, status: 'missing' }); const confirmation = this.reviewView.state().confirmation; if (confirmation) { if (value === '\u001b') this.reviewView.cancelConfirmation(); else if (value === '\r') { const action = this.reviewView.confirmAction().action; try { if (action === 'integrate' || action === 'override') this.integration.finalize(detail.executionId, {}, { override: action === 'override' }); else if (action === 'remedy') this.integration.remedy(detail.executionId); } catch (error) { this.error = error; } } return this.draw(); } if (value === 'q' || value === '\u001b') { this.topPage.detail = null; return this.draw(); } if (value === '\u001b[A') this.reviewView.scroll(-1); else if (value === '\u001b[B') this.reviewView.scroll(1); else if (value === '\u001b[5~') this.reviewView.page(-1); else if (value === '\u001b[6~') this.reviewView.page(1); else if (value === 'u') this.reviewView.removeLastSelection(); else if (value === 'c') this.reviewView.clearSelections(); else if (value === 'a' && item?.kind === 'chunk' && item.status === 'review') this.scheduler.accept(item.executionId, item.id); else if (value === 'f' && stateDescriptor(item).actions.includes('feedback')) this.topPage.feedback = { kind: item?.kind === 'final' ? 'remedy' : 'feedback', value: '', error: null }; else if (value === 'i' && item?.kind === 'final') this.reviewView.requestAction('integrate'); else if (value === 'o' && item?.kind === 'final') this.reviewView.requestAction('override'); else if (value === 'r' && item?.kind === 'final') this.reviewView.requestAction('remedy'); }
          return this.draw();
        }
        if (value === 'q' || value === '\u001b') return this.exitNative();
        if (value === '\u001b[A' && items.length) { this.topPage.index = (this.topPage.index + items.length - 1) % items.length; this.topPage.deleteError = null; } else if (value === '\u001b[B' && items.length) { this.topPage.index = (this.topPage.index + 1) % items.length; this.topPage.deleteError = null; } else if (plans && value === 'd' && items.length) { const item = items[this.topPage.index]; this.topPage.deleteConfirmation = { scope: 'selected', count: 1, planIds: [item.planId] }; this.topPage.deleteError = null; } else if (plans && value === 'D' && items.length) { this.topPage.deleteConfirmation = { scope: 'all', count: items.length, planIds: items.map((item) => item.planId) }; this.topPage.deleteError = null; } else if (value === '\r' && items.length) { const item = items[this.topPage.index]; this.topPage.detail = plans ? { planId: item.planId, version: item.currentVersion, sectionIndex: 0, reader: false, diff: false, scroll: 0 } : { executionId: item.executionId, id: item.id, scroll: 0 }; }
        return this.draw();
      }
      if (this.sessionPicker) {
        let rows = this.sessionPickerRows(this.decorateWorkspace(this.store.load())); this.syncSessionPicker(rows); const selected = () => rows[this.sessionPicker.index];
        if (this.sessionPicker.edit) { if (value === '\u001b') this.sessionPicker.edit = null; else if (value === '\r') { try { this.store.renameWorkstream(this.sessionPicker.edit.workstreamId, this.sessionPicker.edit.value); this.sessionPicker.edit = null; } catch (error) { this.sessionPicker.edit.error = error.message; } } else if (value === '\u007f' || value === '\b') { this.sessionPicker.edit.value = [...this.sessionPicker.edit.value].slice(0, -1).join(''); this.sessionPicker.edit.error = null; } else if (!/[\u0000-\u001f\u007f-\u009f]/u.test(value)) { this.sessionPicker.edit.value += value; this.sessionPicker.edit.error = null; } return this.draw(); }
        if (this.sessionPicker.confirmDelete && value !== '\u001b' && value !== '\r') return this.draw();
        if (value === 'q') return this.exitNative();
        if (value === '\u001b') { if (this.sessionPicker.confirmDelete) this.sessionPicker.confirmDelete = null; else return this.exitNative(); return this.draw(); }
        if ((value === '\u001b[A' || value === '\u001b[B') && rows.length) this.sessionPicker.scroll = Math.max(0, (this.sessionPicker.scroll || 0) + (value === '\u001b[A' ? -1 : 1));
        else if (value === 'r' && selected()?.header) this.sessionPicker.edit = { workstreamId: selected().stream.id, value: selected().stream.name || fallbackName(selected().session, selected().stream, this.workspace), error: null };
        else if (value === 'd' && selected()?.header) { this.sessionPicker.confirmDelete = selected().stream.id; this.sessionPicker.deleteError = null; }
        else if (value === 'D' && rows.length) { this.sessionPicker.confirmDelete = 'all'; this.sessionPicker.deleteError = null; }
        else if (value === '\r' && this.sessionPicker.confirmDelete === 'all') { const state = this.store.load(); try { for (const session of state.sessions) this.sessions.delete?.(session.id); this.store.deleteAllWorkstreams(); this.sessionPicker = null; this.wizard = this.createWizard(); this.navigation = new Navigation(this.store.load()); this.navigation.activeAction = 'New'; } catch (error) { this.sessionPicker.confirmDelete = null; this.sessionPicker.deleteError = `Nothing was removed from the session catalog: ${error.message}`; } }
        else if (value === '\r' && selected()) { const row = selected(); if (row.header && this.sessionPicker.confirmDelete === row.stream.id) { const sessionIds = this.store.load().sessions.filter((item) => item.workstreamId === row.stream.id).map((item) => item.id); try { for (const sessionId of sessionIds) this.sessions.delete?.(sessionId); this.store.deleteWorkstream(row.stream.id); rows = this.sessionPickerRows(this.decorateWorkspace(this.store.load())); if (!rows.length) { this.sessionPicker = null; this.wizard = this.createWizard(); this.navigation = new Navigation(this.store.load()); this.navigation.activeAction = 'New'; } else { this.sessionPicker.index = Math.min(this.sessionPicker.index, rows.length - 1); this.sessionPicker.sessionId = rows[this.sessionPicker.index].session.id; this.sessionPicker.confirmDelete = null; } } catch (error) { this.sessionPicker.confirmDelete = null; this.sessionPicker.deleteError = `Nothing was removed from the session catalog: ${error.message}`; } } else { if (row.stream.status === 'closed') this.store.reopenWorkstream(row.stream.id); else this.store.activateWorkstream(row.stream.id); try { if (resumableSession(row.session)) { if (this.sessions.resume) this.sessions.resume(row.session.id, this.dimensions()); else this.sessions.open(row.session.id, this.dimensions()); } else if (!terminalSession(row.session)) this.sessions.open(row.session.id, this.dimensions()); this.error = null; } catch (error) { this.error = codedError('SESSION_RESTORE_FAILED', error.message); } this.sessionPicker = null; this.navigation = new Navigation(this.decorateWorkspace(this.store.load())); this.navigation.selectSession(row.session.id); this.navigation.rail = 'content'; this.navigation.activeAction = null; this.lastFocused.set(row.stream.id, row.session.id); if (this.sessions.focus) this.sessions.focus(row.session.id); else this.store.markSessionViewed?.(row.session.id); this.clearFocusedAttention(); } }
        return this.draw();
      }
      if (this.wizard && value === '\u001b') { if (this.navigation.agents().length) return this.exitNative(); return this.draw(); }
      if (this.wizard && this.navigation.rail === 'content') { const config = this.wizard.handle(value); if (config) this.finishWizard(config); return this.draw(); }
      const session = this.selectedSession(); if (this.navigation.rail === 'content' && session) { if (value === '\u001b[A') this.sessions.scroll?.(session.id, -1); else if (value === '\u001b[B') this.sessions.scroll?.(session.id, 1); else if (value !== '\u001b[D' && value !== '\u001b[C') { this.store.setSessionTurnState?.(session.id, 'working', 'user input'); this.sessions.write?.(session.id, value); } }
    };
    this.onData = (data) => { for (const value of inputTokens(data)) if (handle(value) === false) break; }; this.onResize = () => { const dimensions = this.dimensions(); for (const sessionId of this.sessions.processes?.keys?.() || []) this.sessions.resize?.(sessionId, dimensions.columns, dimensions.rows); this.draw(); }; this.input.on?.('data', this.onData); this.output.on?.('resize', this.onResize); this.draw(); return this;
  }
  activate(action) {
    if (action === 'New') { if (!this.wizard) this.previousSurface = this.navigation.activeAction ? { action: this.navigation.activeAction } : { sessionId: this.navigation.sessionId }; this.sessionPicker = null; this.topPage = null; this.wizard = this.createWizard(); this.navigation.activeAction = 'New'; this.navigation.rail = 'content'; return this.draw(); }
    if (action === 'Sessions') { this.wizard = null; this.topPage = null; const rows = this.sessionPickerRows(this.store.load()); const current = rows.findIndex(({ session }) => session.id === this.navigation.sessionId); this.sessionPicker = { index: Math.max(0, current), sessionId: rows[Math.max(0, current)]?.session.id || rows[0]?.session.id || null }; this.navigation.activeAction = 'Sessions'; this.navigation.rail = 'content'; return this.draw(); }
    if (action === 'Close') { const session = this.selectedSession(); if (session) { if (this.sessions.pause) this.sessions.pause(session.id); else this.sessions.close?.(session.id); const current = this.store.load().sessions.find((item) => item.id === session.id); if (current && !current.explicitlyClosed) this.store.pauseSession?.(session.id); } this.workspace = this.decorateWorkspace(this.store.load()); this.navigation.activeAction = null; this.navigation.sessionId = null; this.navigation.rail = 'content'; this.navigation.sync(this.workspace); const openAgents = this.navigation.agents().filter(({ session: candidate }) => !pausedSession(candidate) && !terminalSession(candidate)); const sameParent = openAgents.find(({ stream }) => stream.id === session?.workstreamId); const fallback = sameParent || openAgents[0]; if (fallback) return this.focusAgent(fallback.session.id); return this.activate('Sessions'); }
    if (action === 'Plans' || action === 'Reviews') { this.wizard = null; this.sessionPicker = null; this.topPage = { action, index: 0 }; this.navigation.activeAction = action; this.navigation.rail = 'content'; return this.draw(); }
    return this.draw();
  }
  stop() { this.running = false; this.quitPending = false; if (this.quitTimer !== undefined) { this.cancelTimeout(this.quitTimer); this.quitTimer = undefined; } if (this.outputDrawTimer !== undefined) { this.cancelTimeout(this.outputDrawTimer); this.outputDrawTimer = undefined; } this.git.cancelChecks?.(); this.sessions.shutdown?.(); this.bridge.close?.(); this.input.off?.('data', this.onData); this.output.off?.('resize', this.onResize); this.input.setRawMode?.(false); this.input.pause?.(); this.output.write(`${terminalTitle(null, false)}${ESC}?1006l${ESC}?1000l${ESC}?25h${ESC}?1049l`); this.release(); }
}

module.exports = { ACTIONS, FOOTER_MESSAGES, availableActions, COLORS, width, fit, crop, softWrapLine, softWrap, railName, promptPreview, inputTokens, mouseEvent, isVerticalWheel, isPrimaryClick, sanitizeTerminalTitle, formatLocalDateTime, hasOpenAttention, terminalTitle, codedError, errorPageLines, Navigation, TerminalRenderer, TerminalSupervisor };
