'use strict';

const fs = require('node:fs'); const path = require('node:path'); const { execFileSync, spawnSync } = require('node:child_process');
const { pathsOverlap, validateChecks } = require('../plans/format'); const { atomicWrite } = require('../core/plans');

class ExecutionGit {
  constructor(root, { git = execFileSync, io = fs } = {}) { this.root = path.resolve(root); this.gitCommand = git; this.io = io; this.directory = path.join(this.root, '.bdfl', 'worktrees'); }
  git(args, cwd = this.root, options = {}) { return `${this.gitCommand('git', args, { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], ...options })}`.trim(); }
  baseline(reference = 'HEAD') { return this.git(['rev-parse', reference]); }
  target() { const branch = this.git(['branch', '--show-current']); const head = this.baseline(); this.assertTarget(branch, head); return { branch, head }; }
  assertTarget(expectedBranch, expectedHead) { const branch = this.git(['branch', '--show-current']); const head = this.baseline(); const dirty = this.git(['status', '--porcelain=v1', '--untracked-files=all']).split('\n').filter((line) => line && !line.slice(3).startsWith('.bdfl/')).join('\n'); if (branch !== expectedBranch || head !== expectedHead || dirty) { const error = new Error('Original target changed or is dirty; final integration stopped'); error.code = 'TARGET_CHANGED'; throw error; } }
  createWorker(executionId, chunkId, attempt, base) { const safe = `${executionId}-${chunkId}-${attempt}`.replace(/[^a-zA-Z0-9._-]/g, '-'); const branch = `bdfl/${safe}`; const worktree = path.join(this.directory, 'workers', safe); this.io.mkdirSync(path.dirname(worktree), { recursive: true }); const commit = this.baseline(base); this.git(['worktree', 'add', '-b', branch, worktree, commit]); return { branch, worktree, base: commit }; }
  checkpoint(worktree, message) { this.git(['add', '-A'], worktree); if (this.git(['diff', '--cached', '--name-only'], worktree)) this.git(['commit', '-m', message], worktree); return this.git(['rev-parse', 'HEAD'], worktree); }
  changed(base, head, cwd = this.root) { const output = this.git(['diff', '--name-only', '--diff-filter=ACMRTUXB', `${base}..${head}`], cwd); return output ? output.split('\n') : []; }
  patch(base, head, cwd = this.root) { return this.git(['diff', '--no-ext-diff', `${base}..${head}`], cwd); }
  runChecks(checks, cwd) { const results = []; for (const command of validateChecks(checks)) { const result = spawnSync(command[0], command.slice(1), { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }); results.push({ command, ok: result.status === 0, output: `${result.stdout || result.stderr || ''}`.slice(0, 4000) }); if (result.status !== 0) break; } return results; }
  verifyResult({ base, head, ownedPaths, checks = [], worktree }) { const changedPaths = this.changed(base, head); const violations = changedPaths.filter((file) => !ownedPaths.some((owned) => pathsOverlap(file, owned))); if (violations.length) throw new Error(`Worker changed paths outside ownership: ${violations.join(', ')}`); const results = this.runChecks(checks, worktree); return { state: results.some((result) => !result.ok) ? 'fail' : 'pass', commit: head, changedPaths, checks: results, diff: this.patch(base, head, worktree) }; }
  composeBase(executionId, chunkId, attempt, baseline, commits) { const safe = `${executionId}-${chunkId}-${attempt}`.replace(/[^a-zA-Z0-9._-]/g, '-'); const branch = `bdfl/base-${safe}`; const worktree = path.join(this.directory, 'bases', safe); this.io.mkdirSync(path.dirname(worktree), { recursive: true }); this.git(['worktree', 'add', '-b', branch, worktree, baseline]); for (const commit of commits) this.git(['cherry-pick', commit], worktree); return this.git(['rev-parse', 'HEAD'], worktree); }
  createIntegration(executionId, base) { const safe = executionId.replace(/[^a-zA-Z0-9._-]/g, '-'); const branch = `bdfl/integration-${safe}`; const worktree = path.join(this.directory, 'integration', safe); this.io.mkdirSync(path.dirname(worktree), { recursive: true }); this.git(['worktree', 'add', '-b', branch, worktree, base]); return { branch, worktree, base }; }
  consolidate(integration, chunks) { const ordered = [...chunks].sort((left, right) => left.order - right.order); for (const chunk of ordered) { try { this.git(['cherry-pick', chunk.commit], integration.worktree); } catch (error) { return { state: 'conflict', chunkIds: ordered.slice(0, ordered.indexOf(chunk) + 1).map((item) => item.id), pendingChunkIds: ordered.slice(ordered.indexOf(chunk) + 1).map((item) => item.id), message: `${error.stderr || error.message}`.slice(0, 800) }; } } return { state: 'pass', head: this.git(['rev-parse', 'HEAD'], integration.worktree), changedPaths: this.changed(integration.base, 'HEAD', integration.worktree) }; }
  verifierContext(execution, integration, lineage) { const directory = path.join(this.root, '.bdfl', 'workers', execution.id, 'verifier', 'context'); this.io.mkdirSync(path.join(directory, 'chunks'), { recursive: true }); atomicWrite(path.join(directory, 'shared.md'), lineage.readSection(execution.planId, execution.version, 'shared')); for (const chunk of execution.chunks) atomicWrite(path.join(directory, 'chunks', `${chunk.id}.md`), lineage.readSection(execution.planId, execution.version, chunk.id)); atomicWrite(path.join(directory, 'global-validation.md'), lineage.readSection(execution.planId, execution.version, 'global-validation')); atomicWrite(path.join(directory, 'diff.patch'), this.git(['diff', '--no-ext-diff', `${integration.base}..HEAD`], integration.worktree)); atomicWrite(path.join(directory, 'checks.json'), `${JSON.stringify({ chunks: execution.chunks.map(({ id, checks, checkResults }) => ({ id, approved: checks, results: checkResults || [] })), global: { approved: execution.globalValidation.checks || [], results: integration.checkResults || [] } }, null, 2)}\n`); return directory; }
  integrate(integration, { targetBranch, targetHead, message }) { this.assertTarget(targetBranch, targetHead); const tree = this.git(['rev-parse', `${integration.branch}^{tree}`]); const commit = this.git(['commit-tree', tree, '-p', targetHead, '-m', message]); this.git(['merge', '--ff-only', commit]); return commit; }
}

module.exports = { ExecutionGit };
