'use strict';

const readline = require('node:readline');
const ACTIONS = ['status', 'execute', 'wait', 'complete', 'feedback', 'send'];
const TOOL = { name: 'bdfl_workers', title: 'Coordinate approved BDFL workers', description: 'Execute and monitor only an approved BDFL plan.', inputSchema: { type: 'object', properties: { action: { type: 'string', enum: ACTIONS }, planId: { type: 'string' }, version: { type: 'integer' }, workstreamId: { type: 'string' }, executionId: { type: 'string' }, chunkId: { type: 'string' }, cursor: { type: 'integer' }, state: { type: 'string', enum: ['pass', 'blocked', 'fail'] }, summary: { type: 'string', maxLength: 800 }, message: { type: 'string', maxLength: 800 } }, required: ['action'], additionalProperties: false } };
function result(value) { return { content: [{ type: 'text', text: value.message || 'BDFL worker state updated.' }], structuredContent: value }; }
class WorkersMcpServer {
  constructor({ input = process.stdin, output = process.stdout, scheduler, executionId = null, sender = null } = {}) { this.input = input; this.output = output; this.scheduler = scheduler; this.executionId = executionId; this.sender = sender; }
  respond(id, value) { this.output.write(`${JSON.stringify({ jsonrpc: '2.0', id, result: value })}\n`); }
  async call(args) { const id = args.executionId || this.executionId; if (args.action === 'execute') { const execution = this.scheduler.freeze(args.planId, args.version, args.workstreamId); this.executionId = execution.id; return result({ executionId: execution.id, message: 'Approved plan execution started.' }); } if (!id) throw new Error('executionId is required'); if (args.action === 'status') return result(this.scheduler.status(id)); if (args.action === 'wait') { const value = await this.scheduler.wait(id, args.cursor || 0); return result({ ...value, message: value.events.length ? `${value.events.length} worker event(s).` : 'No new worker events.' }); } if (args.action === 'complete') return result({ chunk: this.scheduler.complete(id, args.chunkId, args), message: 'Worker completion recorded.' }); if (args.action === 'send') { this.sender?.(id, args.chunkId, args.message); return result({ executionId: id, chunkId: args.chunkId, queued: true, message: 'Message queued at the next safe provider boundary.' }); } throw new Error(`Unknown action: ${args.action}`); }
  async handle(message) { if (message.method === 'initialize') return this.respond(message.id, { protocolVersion: message.params?.protocolVersion || '2025-11-25', capabilities: { tools: {} }, serverInfo: { name: 'bdfl-workers', version: '0.1.0' } }); if (message.method === 'tools/list') return this.respond(message.id, { tools: [TOOL] }); if (message.method === 'tools/call') { try { return this.respond(message.id, await this.call(message.params?.arguments || {})); } catch (error) { return this.respond(message.id, { ...result({ message: error.message }), isError: true }); } } }
  start() { const lines = readline.createInterface({ input: this.input, crlfDelay: Infinity }); lines.on('line', (line) => { if (line.trim()) void this.handle(JSON.parse(line)); }); return lines; }
}
module.exports = { ACTIONS, TOOL, WorkersMcpServer, result };
