'use strict';

const fs = require('node:fs'); const path = require('node:path'); const crypto = require('node:crypto');
const { atomicWrite } = require('../core/plans'); const { validateWorkstreamConfig } = require('../core/profiles');

function defaultWorkspace() { return { schema: 1, workstreams: [], sessions: [], activeWorkstreamId: null, nextPaneNumber: 1 }; }

class WorkspaceStore {
  constructor(root, { io = fs, now = () => new Date(), id = () => crypto.randomUUID() } = {}) { this.root = path.resolve(root); this.io = io; this.now = now; this.id = id; this.directory = path.join(this.root, '.bdfl'); this.file = path.join(this.directory, 'workspace.json'); this.configFile = path.join(this.directory, 'config.json'); this.events = path.join(this.directory, 'events.ndjson'); }
  load() { if (!this.io.existsSync(this.file)) return defaultWorkspace(); const value = JSON.parse(this.io.readFileSync(this.file, 'utf8')); if (value.schema !== 1) { const error = new Error('Previous unreleased BDFL state requires reset or export'); error.code = 'RESET_REQUIRED'; throw error; } return value; }
  loadConfig() { if (!this.io.existsSync(this.configFile)) return null; const value = JSON.parse(this.io.readFileSync(this.configFile, 'utf8')); return validateWorkstreamConfig({ version: 1, delegatorProfile: value.profiles.delegator, workerProfile: value.profiles.worker, workerCapacity: value.workerCapacity }); }
  activateWorkstream(id) { return this.update((state) => { if (!state.workstreams.some((stream) => stream.id === id && stream.status !== 'closed')) throw new Error(`Unknown active session: ${id}`); state.activeWorkstreamId = id; return state; }); }
  save(value) { atomicWrite(this.file, `${JSON.stringify(value, null, 2)}\n`, this.io); return value; }
  update(mutator) { const value = this.load(); return this.save(mutator(structuredClone(value)) || value); }
  event(type, data = {}) { this.io.mkdirSync(this.directory, { recursive: true }); this.io.appendFileSync(this.events, `${JSON.stringify({ id: this.id(), type, at: this.now().toISOString(), ...data })}\n`, { mode: 0o600 }); }
  createWorkstream(config, title = path.basename(this.root)) { const validated = validateWorkstreamConfig(config); let workstream; this.update((state) => { const provider = validated.delegatorProfile.provider; const providerSequence = Math.max(0, ...state.workstreams.map((item, index) => item.delegatorProfile?.provider === provider ? item.providerSequence || state.workstreams.slice(0, index + 1).filter((candidate) => candidate.delegatorProfile?.provider === provider).length : 0)) + 1; const createdAt = this.now().toISOString(); workstream = { id: `workstream-${this.id()}`, title, ...validated, providerSequence, status: 'active', createdAt, updatedAt: createdAt }; state.workstreams.push(workstream); state.activeWorkstreamId = workstream.id; return state; }); atomicWrite(this.configFile, `${JSON.stringify({ schema: 1, profiles: { delegator: validated.delegatorProfile, worker: validated.workerProfile }, workerCapacity: validated.workerCapacity }, null, 2)}\n`, this.io); this.event('workstream.created', { workstreamId: workstream.id }); return workstream; }
  setCapacity(id, capacity) { if (!Number.isInteger(capacity) || capacity < 1 || capacity > 5) throw new Error('Worker capacity must be an integer from 1 to 5'); let active = 0; const state = this.update((value) => { const stream = value.workstreams.find((item) => item.id === id); if (!stream) throw new Error(`Unknown session: ${id}`); stream.workerCapacity = capacity; stream.updatedAt = this.now().toISOString(); active = value.sessions.filter((session) => session.workstreamId === id && session.role !== 'delegator' && session.status === 'running').length; return value; }); this.event('workstream.capacity', { workstreamId: id, capacity, active }); return { workstream: state.workstreams.find((item) => item.id === id), active, canStart: Math.max(0, capacity - active) }; }
  closeWorkstream(id) { const state = this.update((value) => { const stream = value.workstreams.find((item) => item.id === id); if (!stream) throw new Error(`Unknown workstream: ${id}`); const updatedAt = this.now().toISOString(); stream.status = 'closed'; stream.updatedAt = updatedAt; for (const session of value.sessions.filter((item) => item.workstreamId === id)) { session.status = 'closed'; session.explicitlyClosed = true; session.updatedAt = updatedAt; delete session.pid; } if (value.activeWorkstreamId === id) value.activeWorkstreamId = value.workstreams.find((item) => item.status !== 'closed')?.id || null; return value; }); this.event('workstream.closed', { workstreamId: id }); return state.workstreams.find((item) => item.id === id); }
  reopenWorkstream(id) { const state = this.update((value) => { const index = value.workstreams.findIndex((item) => item.id === id); if (index < 0) throw new Error(`Unknown workstream: ${id}`); const [stream] = value.workstreams.splice(index, 1); const updatedAt = this.now().toISOString(); stream.status = 'active'; stream.updatedAt = updatedAt; value.workstreams.push(stream); for (const session of value.sessions.filter((item) => item.workstreamId === id)) { session.explicitlyClosed = false; session.updatedAt = updatedAt; } value.activeWorkstreamId = id; return value; }); this.event('workstream.reopened', { workstreamId: id }); return state.workstreams.find((item) => item.id === id); }
  deleteWorkstream(id) { const state = this.update((value) => { if (!value.workstreams.some((item) => item.id === id)) throw new Error(`Unknown workstream: ${id}`); value.workstreams = value.workstreams.filter((item) => item.id !== id); value.sessions = value.sessions.filter((item) => item.workstreamId !== id); if (value.activeWorkstreamId === id) value.activeWorkstreamId = value.workstreams.find((item) => item.status !== 'closed')?.id || null; return value; }); this.event('workstream.deleted', { workstreamId: id }); return state; }
  createSession(workstreamId, role, profile, fields = {}) { let session; this.update((state) => { const stream = state.workstreams.find((item) => item.id === workstreamId); if (!stream) throw new Error(`Unknown workstream: ${workstreamId}`); const paneNumber = Math.max(0, ...state.sessions.filter((item) => item.workstreamId === workstreamId).map((item) => item.paneNumber || 0)) + 1; const createdAt = this.now().toISOString(); session = { id: `session-${this.id()}`, workstreamId, role, paneNumber, profile: structuredClone(profile), status: 'closed', explicitlyClosed: false, createdAt, updatedAt: createdAt, ...fields }; stream.updatedAt = session.updatedAt; state.sessions.push(session); state.nextPaneNumber = Math.max(state.nextPaneNumber || 1, paneNumber + 1); return state; }); this.event('session.created', { sessionId: session.id, workstreamId, role }); return session; }
  setSessionAttention(id, attention) { const value = this.load(); const session = value.sessions.find((item) => item.id === id); if (!session) throw new Error(`Unknown session: ${id}`); const next = Boolean(attention); if (Boolean(session.attention) === next) return value; session.attention = next; return this.save(value); }
  touchSession(id) { return this.update((state) => { const session = state.sessions.find((item) => item.id === id); if (!session) throw new Error(`Unknown session: ${id}`); const updatedAt = this.now().toISOString(); session.updatedAt = updatedAt; const stream = state.workstreams.find((item) => item.id === session.workstreamId); if (stream) stream.updatedAt = updatedAt; return state; }); }
}

module.exports = { WorkspaceStore, defaultWorkspace };
