'use strict';
const { EventEmitter } = require('node:events'); const test = require('node:test'); const assert = require('node:assert/strict');
const pkg = require('../../package.json'); const { run } = require('../../src/cli'); const { ISSUE_URL, RESTORE_TERMINAL, errorDetails, formatErrorReport, installFatalErrorHandlers } = require('../../src/core/errors');

function io() { const processLike = new EventEmitter(); processLike.env = { NO_COLOR: '1' }; processLike.stdin = { isTTY: true }; processLike.stdout = { isTTY: true, value: '', write(value) { this.value += value; } }; processLike.stderr = { isTTY: false, value: '', write(value) { this.value += value; } }; return processLike; }

test('parses coded and unexpected errors into safe one-line details', () => { const coded = new Error('Reset\nthis workspace\u001b[31m'); coded.code = 'RESET_REQUIRED'; assert.deepEqual(errorDetails(coded), { code: 'RESET_REQUIRED', message: 'Reset this workspace' }); assert.deepEqual(errorDetails(new TypeError('bad input')), { code: 'TYPE_ERROR', message: 'bad input' }); assert.deepEqual(errorDetails('broken'), { code: 'UNEXPECTED_ERROR', message: 'broken' }); });
test('formats errors with code, message, environment, and the repository issue link but no stack', () => { const error = new Error('Readable failure'); error.code = 'READABLE_FAILURE'; const report = formatErrorReport(error, { version: '1.2.3', nodeVersion: 'v24.1.0' }); assert.match(report, /BDFL encountered an error/); assert.match(report, /Code\s+READABLE_FAILURE/); assert.match(report, /Message\s+Readable failure/); assert.match(report, /BDFL 1\.2\.3 · Node v24\.1\.0/); assert.match(report, new RegExp(ISSUE_URL.replaceAll('/', '\\/'))); assert.doesNotMatch(report, /at .*\.js:/); });
test('the CLI catches startup errors, restores the terminal, and exits without a raw stack', () => { const streams = io(); const error = new Error('Remove this repository\'s .bdfl directory.'); error.code = 'RESET_REQUIRED'; const code = run([], streams, '/tmp/workspace', () => ({ start() { throw error; } }), () => Promise.resolve()); assert.equal(code, 1); assert.equal(streams.stdout.value, RESTORE_TERMINAL); assert.match(streams.stderr.value, /RESET_REQUIRED/); assert.match(streams.stderr.value, /Remove this repository's \.bdfl directory\./); assert.match(streams.stderr.value, new RegExp(ISSUE_URL.replaceAll('/', '\\/'))); assert.match(streams.stderr.value, new RegExp(`BDFL ${pkg.version.replaceAll('.', '\\.')}`)); assert.doesNotMatch(streams.stderr.value, /WorkspaceStore\.load|at .*\.js:/); });
test('fatal exception handlers use the same report before exiting', () => { const streams = io(); const exits = []; const remove = installFatalErrorHandlers(streams, { version: 'test', exit(code) { exits.push(code); } }); const error = new Error('Async failure'); error.code = 'ASYNC_FAILURE'; streams.emit('unhandledRejection', error); assert.deepEqual(exits, [1]); assert.match(streams.stderr.value, /ASYNC_FAILURE/); assert.equal(streams.stdout.value, RESTORE_TERMINAL); remove(); });
