'use strict';

const test = require('node:test'); const assert = require('node:assert/strict'); const { IntegrationCoordinator } = require('../../src/workers/integration');

function fixture(consolidation = { state: 'pass', head: 'combined' }) { let execution = { id: 'e', planId: 'p', baseline: 'base', targetBranch: 'main', targetHead: 'base', repositoryRoot: '/tmp/repository', profile: { provider: 'codex' }, status: 'running', globalValidation: { checks: [['npm', 'test']] }, chunks: [{ id: 'a', order: 0, status: 'accepted', commit: 'a', paths: ['src/a/**'] }, { id: 'b', order: 1, status: 'accepted', commit: 'b', paths: ['src/b/**'] }] }; const launches = []; const repairLaunches = []; const verifiedResults = []; let verifierNumber = 0; const scheduler = { load: () => structuredClone(execution), save(value) { execution = structuredClone(value); return value; } }; const git = { root: '/tmp/repository', createIntegration: () => ({ branch: 'private', worktree: '/tmp/private', base: 'base' }), consolidate: () => consolidation, runChecks: () => [{ command: ['npm', 'test'], ok: true }], verifierContext: () => '/tmp/context', patch: () => 'final diff', checkpoint: () => 'repaired', verifyResult(value) { verifiedResults.push(value); return { state: 'pass' }; }, git: () => 'head', stageIntegration(_integration, target) { launches.push(['stage', target]); return { state: 'ready', advanced: false, commit: 'final', targetHead: 'base', worktree: '/tmp/private' }; }, completeIntegration(_staged, target) { launches.push(['integrate', target]); return 'final'; }, cleanupReconciliation() {} }; const coordinator = new IntegrationCoordinator({ scheduler, git, lineage: { load: () => ({ title: 'Named Plan' }) }, verifierLauncher(value) { launches.push(['verifier', value.readOnly]); verifierNumber += 1; return { sessionId: `v${verifierNumber}` }; }, integrationLauncher(value) { repairLaunches.push(value); launches.push(['repair', value.allowedPaths]); return { sessionId: 'i' }; }, now: () => new Date('2026-01-01') }); return { coordinator, scheduler, git, launches, repairLaunches, verifiedResults, state: () => execution };
}

test('runs global checks, records verifier failure/pass, and integrates exactly once after pass', async () => { const value = fixture(); value.coordinator.prepare('e'); assert.equal(value.state().status, 'integration-checking'); await value.coordinator.waitForChecks('e'); assert.equal(value.state().status, 'verifying'); assert.deepEqual(value.launches[0], ['verifier', true]); value.coordinator.verification('e', { state: 'fail', summary: 'bad', affectedChunkIds: ['a'] }); assert.equal(value.state().status, 'verification-failed'); assert.throws(() => value.coordinator.finalize('e'), /Passing global verification/); assert.equal(value.coordinator.finalize('e', {}, { override: true }), 'final'); assert.deepEqual(value.state().integrationOverride, { at: '2026-01-01T00:00:00.000Z', verificationState: 'fail', verificationSummary: 'bad', failedChecks: [] }); assert.equal(value.launches.find(([kind]) => kind === 'stage')[1].message, 'Integrate Named Plan'); const passing = fixture(); passing.coordinator.prepare('e'); await passing.coordinator.waitForChecks('e'); passing.coordinator.verification('e', { state: 'pass', summary: 'good' }); assert.equal(passing.coordinator.finalize('e'), 'final'); assert.equal(passing.state().status, 'complete'); assert.equal(passing.state().integrationOverride, undefined); assert.equal(passing.launches.filter(([kind]) => kind === 'integrate').length, 1); assert.equal(passing.launches.find(([kind]) => kind === 'stage')[1].message, 'Integrate Named Plan'); });

test('launches conflict repair with only the approved path union and then verifies', async () => { const value = fixture({ state: 'conflict', chunkIds: ['a'], pendingChunkIds: [], message: 'conflict' }); value.coordinator.prepare('e'); assert.equal(value.state().status, 'integration-conflict'); assert.deepEqual(value.launches[0], ['repair', ['src/a/**', 'src/b/**']]); assert.throws(() => value.coordinator.finalize('e', {}, { override: true }), /consolidated result/); value.coordinator.repaired('e', { state: 'pass', summary: 'fixed' }); assert.equal(value.state().status, 'integration-checking'); await value.coordinator.waitForChecks('e'); assert.equal(value.state().status, 'verifying'); assert.deepEqual(value.launches.at(-1), ['verifier', true]); });

test('hands failed verifier findings to a scoped repair agent and launches a fresh verifier', async () => {
  const value = fixture(); value.coordinator.prepare('e'); await value.coordinator.waitForChecks('e'); const fullFindings = `Fix the stale callback. ${'Detailed verifier evidence. '.repeat(50)}`; value.coordinator.verification('e', { state: 'fail', summary: fullFindings, affectedChunkIds: ['a'] }); assert.equal(value.state().verification.summary, fullFindings);
  const remedy = value.coordinator.remedy('e', 'Also retain the active terminal'); assert.equal(value.state().status, 'integration-conflict'); assert.equal(remedy.kind, 'verification'); assert.deepEqual(remedy.chunkIds, ['a']); assert.deepEqual(value.repairLaunches.at(-1).allowedPaths, ['src/a/**']); assert.deepEqual(value.state().integration.repairPaths, ['src/a/**']); assert.deepEqual(value.state().integration.allowedPaths, ['src/a/**', 'src/b/**']); assert.equal(value.repairLaunches.at(-1).phase, 'verification-remedy'); assert.match(value.repairLaunches.at(-1).result.message, /Fix the stale callback/); assert.match(value.repairLaunches.at(-1).result.message, /Also retain the active terminal/);
  value.coordinator.repaired('e', { state: 'pass', summary: 'fixed' }); assert.deepEqual(value.verifiedResults.at(-1).ownedPaths, ['src/a/**', 'src/b/**']); await value.coordinator.waitForChecks('e'); assert.equal(value.state().status, 'verifying'); assert.equal(value.state().integration.verifier.sessionId, 'v2'); assert.deepEqual(value.state().integration.verifierAttempts.map((attempt) => [attempt.number, attempt.sessionId, attempt.result || null]), [[1, 'v1', 'fail'], [2, 'v2', null]]); assert.equal(value.state().integration.remedyAttempts.length, 1); assert.throws(() => value.coordinator.remedy('e'), /failed verification state/);
});

test('retries interrupted verifiers durably and fails explicitly instead of remaining stuck', async () => { const value = fixture(); value.coordinator.prepare('e'); await value.coordinator.waitForChecks('e'); assert.equal(value.state().integration.verifier.sessionId, 'v1'); assert.equal(value.coordinator.retryVerification('e', { sessionId: 'stale', reason: 'stale exit' }), null); assert.equal(value.state().integration.verifier.sessionId, 'v1'); value.coordinator.retryVerification('e', { sessionId: 'v1', reason: 'first exit' }); assert.equal(value.state().integration.verifier.sessionId, 'v2'); assert.equal(value.state().integration.verifierAttempts[0].result, 'interrupted'); value.coordinator.retryVerification('e', { sessionId: 'v2', reason: 'second exit' }); assert.equal(value.state().integration.verifier.sessionId, 'v3'); value.coordinator.retryVerification('e', { sessionId: 'v3', reason: 'third exit' }); assert.equal(value.state().status, 'verification-failed'); assert.match(value.state().verification.summary, /after 3 attempts: third exit/); assert.equal(value.state().integration.verifierAttempts.length, 3); });

test('serializes target integration through conflict repair and fresh verification', async () => {
  const makeExecution = (id) => ({ id, planId: `plan-${id}`, repositoryRoot: '/tmp/queue-repository', targetBranch: 'main', targetHead: 'base', profile: { provider: 'codex' }, status: 'integration-review', verification: { state: 'pass', summary: 'approved' }, globalValidation: { checks: [['npm', 'test']] }, chunks: [{ id: `${id}-chunk`, paths: ['src/**'] }], integration: { branch: `branch-${id}`, worktree: `/tmp/${id}`, base: 'base', checkResults: [] } });
  const executions = new Map([['one', makeExecution('one')], ['two', makeExecution('two')]]); const events = []; let verifier = 0;
  const scheduler = { load(id) { return structuredClone(executions.get(id)); }, save(value) { executions.set(value.id, structuredClone(value)); return value; }, list() { return [...executions.values()].map((value) => structuredClone(value)); } };
  const git = {
    root: '/tmp/queue-repository',
    stageIntegration(integration) { events.push(`stage:${integration.branch}`); if (integration.branch === 'branch-one') return { state: 'conflict', advanced: true, source: 'source-one', targetHead: 'parallel', worktree: '/tmp/reconcile-one', message: 'conflict' }; return { state: 'ready', advanced: false, commit: 'commit-two', targetHead: 'commit-one', worktree: integration.worktree }; },
    finishReconciliation(staged) { events.push('repair:one'); return { ...staged, state: 'ready', commit: 'commit-one', checkResults: [{ command: ['npm', 'test'], ok: true }] }; },
    runChecks() { return [{ command: ['npm', 'test'], ok: true }]; }, verifierContext() { return '/tmp/context'; }, patch() { return 'combined diff'; }, cleanupReconciliation() { events.push('cleanup'); },
    completeIntegration(staged) { events.push(`integrate:${staged.commit}`); return staged.commit; }
  };
  const coordinator = new IntegrationCoordinator({ scheduler, git, lineage: { load: (id) => ({ title: id }) }, verifierLauncher() { verifier += 1; events.push(`verify:v${verifier}`); return { sessionId: `v${verifier}` }; }, integrationLauncher() { events.push('agent:repair'); return { sessionId: 'repair-agent' }; }, now: () => new Date('2026-01-01') });
  coordinator.finalize('one'); assert.equal(executions.get('one').status, 'integration-conflict'); coordinator.finalize('two'); assert.equal(executions.get('two').status, 'integration-queued'); assert.deepEqual(events, ['stage:branch-one', 'agent:repair']);
  coordinator.repaired('one', { state: 'pass', summary: 'merged both intents' }); assert.equal(executions.get('one').status, 'integration-checking'); assert.equal(executions.get('two').status, 'integration-queued'); assert.deepEqual(events, ['stage:branch-one', 'agent:repair', 'repair:one']); await coordinator.waitForChecks('one'); assert.equal(executions.get('one').status, 'verifying'); assert.deepEqual(events, ['stage:branch-one', 'agent:repair', 'repair:one', 'verify:v1']);
  coordinator.verification('one', { state: 'pass', summary: 'combined result passes' }); assert.equal(executions.get('one').status, 'complete'); assert.equal(executions.get('two').status, 'complete'); assert.deepEqual(events, ['stage:branch-one', 'agent:repair', 'repair:one', 'verify:v1', 'integrate:commit-one', 'stage:branch-two', 'integrate:commit-two']);
});

test('recovers a resolved reconciliation that was interrupted before checks were recorded', async () => {
  let execution = { id: 'e', planId: 'p', repositoryRoot: '/tmp/repository', targetBranch: 'main', targetHead: 'base', profile: { provider: 'codex' }, status: 'integration-conflict', globalValidation: { checks: [['npm', 'test']] }, chunks: [{ id: 'a', paths: ['src/**'] }], integration: { branch: 'original', worktree: '/tmp/reconcile', base: 'parallel', queue: { requestedAt: '2026-01-01T00:00:00.000Z', active: true, message: 'Integrate p' }, queueSource: { branch: 'original', worktree: '/tmp/original', base: 'base' }, conflict: { state: 'conflict', kind: 'target' }, reconciliation: { state: 'conflict', advanced: true, source: 'source', targetHead: 'parallel', worktree: '/tmp/reconcile' } } };
  const events = []; const scheduler = { load: () => structuredClone(execution), save(value) { execution = structuredClone(value); }, list: () => [structuredClone(execution)] }; const git = { root: '/tmp/repository', reconciliationResolved: () => true, finishReconciliation(staged) { events.push('recovered'); return { ...staged, state: 'ready', commit: 'resolved' }; }, async runChecksAsync() { events.push('checks'); return [{ command: ['npm', 'test'], ok: true }]; }, verifierContext: () => '/tmp/context', patch: () => 'diff' };
  const coordinator = new IntegrationCoordinator({ scheduler, git, lineage: {}, verifierLauncher() { events.push('verify'); return { sessionId: 'v' }; } }); coordinator.resumeIntegrationQueue(); assert.equal(execution.status, 'integration-checking'); assert.deepEqual(events, ['recovered']); await coordinator.waitForChecks('e'); assert.equal(execution.status, 'verifying'); assert.deepEqual(events, ['recovered', 'checks', 'verify']);
});

test('requeues an interrupted reconciliation when an earlier integration advanced the target', () => {
  let execution = { id: 'e', planId: 'p', repositoryRoot: '/tmp/repository', targetBranch: 'main', targetHead: 'base', profile: { provider: 'codex' }, status: 'integration-conflict', chunks: [{ id: 'a', paths: ['src/**'] }], integration: { branch: 'reconcile', worktree: '/tmp/reconcile', base: 'parallel', queue: { requestedAt: '2026-01-01T00:00:00.000Z', active: true, message: 'Integrate p' }, queueSource: { branch: 'original', worktree: '/tmp/original', base: 'base' }, conflict: { state: 'conflict', kind: 'target' }, reconciliation: { state: 'conflict', advanced: true, source: 'source', targetHead: 'parallel', worktree: '/tmp/reconcile' } } };
  const events = []; const scheduler = { load: () => structuredClone(execution), save(value) { execution = structuredClone(value); }, list: () => [structuredClone(execution)] }; const git = { root: '/tmp/repository', reconciliationResolved: () => true, baseline: () => 'new-head', cleanupReconciliation() { events.push('cleanup:stale'); }, stageIntegration(integration) { events.push(`stage:${integration.branch}`); return { state: 'ready', advanced: false, commit: 'fresh', targetHead: 'new-head', worktree: integration.worktree }; }, completeIntegration(staged) { events.push(`integrate:${staged.commit}`); return staged.commit; } };
  const coordinator = new IntegrationCoordinator({ scheduler, git, lineage: {} }); coordinator.resumeIntegrationQueue(); assert.equal(execution.status, 'complete'); assert.equal(execution.finalCommit, 'fresh'); assert.equal(execution.integration.lastReconciliation.targetHead, 'parallel'); assert.match(execution.integration.queue.retryReason, /Target advanced/); assert.deepEqual(events, ['cleanup:stale', 'stage:original', 'integrate:fresh']);
});

test('keeps a failed reconciled tree and launches a visible validation-repair agent', async () => {
  let execution = { id: 'e', planId: 'p', repositoryRoot: '/tmp/repository', targetBranch: 'main', targetHead: 'base', profile: { provider: 'codex' }, status: 'integrating', globalValidation: { checks: [['npm', 'test']] }, chunks: [{ id: 'a', paths: ['src/**'] }], integration: { branch: 'reconcile', worktree: '/tmp/reconcile', base: 'parallel', head: 'combined', queue: { requestedAt: '2026-01-01T00:00:00.000Z', active: true, message: 'Integrate p' }, queueSource: { branch: 'original', worktree: '/tmp/original', base: 'base' }, reconciliation: { state: 'ready', advanced: true, source: 'source', targetHead: 'parallel', worktree: '/tmp/reconcile', commit: 'combined' } } };
  const events = []; let checks = 0; const scheduler = { load: () => structuredClone(execution), save(value) { execution = structuredClone(value); }, list: () => [structuredClone(execution)] }; const git = { root: '/tmp/repository', async runChecksAsync() { checks += 1; return checks === 1 ? [{ command: ['npm', 'test'], ok: false, output: 'Expected planning sessionType' }] : [{ command: ['npm', 'test'], ok: true, output: 'pass' }]; }, finishReconciliation(staged) { events.push('checkpoint'); return { ...staged, state: 'ready', commit: 'repaired' }; }, baseline: () => 'parallel', verifierContext: () => '/tmp/context', patch: () => 'diff', cleanupReconciliation() { events.push('cleanup'); } };
  const coordinator = new IntegrationCoordinator({ scheduler, git, lineage: {}, integrationLauncher({ result, phase }) { events.push(`${phase}:${result.message.includes('Expected planning sessionType')}`); return { sessionId: 'repair' }; }, verifierLauncher() { events.push('verify'); return { sessionId: 'v' }; } }); coordinator.startChecks(execution, execution.integration, 'combined', { purpose: 'target-reconciliation' }); await coordinator.waitForChecks('e'); assert.equal(execution.status, 'integration-conflict'); assert.equal(execution.integration.queue.active, true); assert.equal(execution.integration.validationRepairAttempts, 1); assert.deepEqual(events, ['target-validation:true']); coordinator.repaired('e', { state: 'pass', summary: 'updated inherited assertion' }); await coordinator.waitForChecks('e'); assert.equal(execution.status, 'verifying'); assert.deepEqual(events, ['target-validation:true', 'checkpoint', 'verify']);
});

test('requeues a legacy reconciled validation failure once after restart', () => {
  let execution = { id: 'e', planId: 'p', repositoryRoot: '/tmp/repository', targetBranch: 'main', targetHead: 'base', profile: { provider: 'codex' }, status: 'verification-failed', verification: { state: 'fail', summary: 'Reconciled target validation failed: npm test' }, chunks: [{ id: 'a', paths: ['src/**'] }], integration: { branch: 'original', worktree: '/tmp/original', base: 'base', queue: { requestedAt: '2026-01-01T00:00:00.000Z', active: false, message: 'Integrate p' }, lastReconciliation: { state: 'ready', advanced: true, targetHead: 'parallel', commit: 'failed' } } };
  const events = []; const scheduler = { load: () => structuredClone(execution), save(value) { execution = structuredClone(value); }, list: () => [structuredClone(execution)] }; const git = { root: '/tmp/repository', stageIntegration() { events.push('stage'); return { state: 'conflict', advanced: true, source: 'source', targetHead: 'current', worktree: '/tmp/new-reconcile', message: 'new target conflict' }; } };
  const coordinator = new IntegrationCoordinator({ scheduler, git, lineage: {}, integrationLauncher() { events.push('repair'); return { sessionId: 'repair' }; } }); coordinator.resumeIntegrationQueue(); assert.equal(execution.status, 'integration-conflict'); assert.equal(execution.integration.queue.active, true); assert.match(execution.integration.queue.retryReason, /visible repair agent/); assert.deepEqual(events, ['stage', 'repair']);
});
