'use strict';

const test = require('node:test'); const assert = require('node:assert/strict'); const { IntegrationCoordinator } = require('../../src/workers/integration');

function fixture(consolidation = { state: 'pass', head: 'combined' }) { let execution = { id: 'e', planId: 'p', baseline: 'base', targetBranch: 'main', targetHead: 'base', profile: { provider: 'codex' }, status: 'running', globalValidation: { checks: [['npm', 'test']] }, chunks: [{ id: 'a', order: 0, status: 'accepted', commit: 'a', paths: ['src/a/**'] }, { id: 'b', order: 1, status: 'accepted', commit: 'b', paths: ['src/b/**'] }] }; const launches = []; const scheduler = { load: () => structuredClone(execution), save(value) { execution = structuredClone(value); return value; } }; const git = { createIntegration: () => ({ branch: 'private', worktree: '/tmp/private', base: 'base' }), consolidate: () => consolidation, runChecks: () => [{ command: ['npm', 'test'], ok: true }], verifierContext: () => '/tmp/context', patch: () => 'final diff', checkpoint: () => 'repaired', verifyResult: () => ({ state: 'pass' }), git: () => 'head', integrate(_integration, target) { launches.push(['integrate', target]); return 'final'; } }; const coordinator = new IntegrationCoordinator({ scheduler, git, lineage: { load: () => ({ title: 'Named Plan' }) }, verifierLauncher(value) { launches.push(['verifier', value.readOnly]); return { sessionId: 'v' }; }, integrationLauncher(value) { launches.push(['repair', value.allowedPaths]); return { sessionId: 'i' }; }, now: () => new Date('2026-01-01') }); return { coordinator, scheduler, git, launches, state: () => execution };
}

test('runs global checks, records verifier failure/pass, and integrates exactly once after pass', () => { const value = fixture(); value.coordinator.prepare('e'); assert.equal(value.state().status, 'verifying'); assert.deepEqual(value.launches[0], ['verifier', true]); value.coordinator.verification('e', { state: 'fail', summary: 'bad', affectedChunkIds: ['a'] }); assert.equal(value.state().status, 'verification-failed'); assert.throws(() => value.coordinator.finalize('e'), /Passing global verification/); assert.equal(value.coordinator.finalize('e', {}, { override: true }), 'final'); assert.deepEqual(value.state().integrationOverride, { at: '2026-01-01T00:00:00.000Z', verificationState: 'fail', verificationSummary: 'bad', failedChecks: [] }); assert.equal(value.launches.find(([kind]) => kind === 'integrate')[1].message, 'Integrate Named Plan'); const passing = fixture(); passing.coordinator.prepare('e'); passing.coordinator.verification('e', { state: 'pass', summary: 'good' }); assert.equal(passing.coordinator.finalize('e'), 'final'); assert.equal(passing.state().status, 'complete'); assert.equal(passing.state().integrationOverride, undefined); assert.equal(passing.launches.filter(([kind]) => kind === 'integrate').length, 1); assert.equal(passing.launches.find(([kind]) => kind === 'integrate')[1].message, 'Integrate Named Plan'); });

test('launches conflict repair with only the approved path union and then verifies', () => { const value = fixture({ state: 'conflict', chunkIds: ['a'], pendingChunkIds: [], message: 'conflict' }); value.coordinator.prepare('e'); assert.equal(value.state().status, 'integration-conflict'); assert.deepEqual(value.launches[0], ['repair', ['src/a/**', 'src/b/**']]); assert.throws(() => value.coordinator.finalize('e', {}, { override: true }), /consolidated result/); value.coordinator.repaired('e', { state: 'pass', summary: 'fixed' }); assert.equal(value.state().status, 'verifying'); assert.deepEqual(value.launches.at(-1), ['verifier', true]); });
