'use strict';
const test = require('node:test'); const assert = require('node:assert/strict'); const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path');
const { LineageStore } = require('../../src/plans/store');
function chunk(id, implementation = 'Build.') { return `<!-- bdfl-chunk:{"id":"${id}","paths":["src/${id}/**"],"dependsOn":[],"locks":[]} -->\n## ${id}\n### Outcome\nDone.\n### Implementation\n${implementation}\n### Local validation\nnpm test\n### Acceptance conditions\nPass.\n<!-- bdfl-chunk:end -->`; }
function source() { return `<!-- bdfl-plan:{"schema":1,"title":"Ship"} -->\n# Ship\n<!-- bdfl-shared:start -->\n## Shared decisions\nA.\n<!-- bdfl-shared:end -->\n${chunk('api')}\n${chunk('ui')}\n<!-- bdfl-global:start -->\n## Global validation\nnpm test\n<!-- bdfl-global:end -->\n<!-- bdfl-plan:end -->`; }
function fixture(t) { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'bdfl-lineage-')); t.after(() => fs.rmSync(root, { recursive: true, force: true })); return new LineageStore(root, { id: () => 'plan-1', now: () => new Date('2026-01-01T00:00:00Z') }); }
test('materializes clean immutable plan files and gates execution on all approvals', (t) => { const store = fixture(t); store.create(source()); const base = path.join(store.root, '.bdfl/plans/plan-1/versions/v0001'); assert.match(fs.readFileSync(path.join(base, 'source.md'), 'utf8'), /bdfl-plan/); assert.doesNotMatch(fs.readFileSync(path.join(base, 'consolidated.md'), 'utf8'), /bdfl-/); for (const id of ['shared', 'api', 'ui', 'global-validation']) store.approve('plan-1', 1, id); assert.equal(store.executable('plan-1', 1), true); });
test('patch preserves unchanged bytes and exact approvals while blocking direct approved changes', (t) => { const store = fixture(t); store.create(source()); for (const id of ['shared', 'api', 'ui', 'global-validation']) store.approve('plan-1', 1, id); const originalSha = store.readManifest('plan-1', 1).approvals.api.sectionSha; const patch = `<!-- bdfl-plan-patch:{"schema":1,"planId":"plan-1","baseVersion":1} -->\n${chunk('ui', 'Build better.')}\n<!-- bdfl-plan-patch:end -->`; assert.throws(() => store.revise('plan-1', patch), /Remove approval before publishing: ui/); store.removeApproval('plan-1', 1, 'ui'); const result = store.revise('plan-1', patch); assert.equal(result.manifest.approvals.shared.sectionSha, store.readManifest('plan-1', 1).shared.sha); assert.equal(result.manifest.approvals.api.sectionSha, originalSha); assert.equal(result.manifest.approvals.ui, undefined); assert.ok(result.manifest.approvals['global-validation']); assert.equal(store.readSection('plan-1', 1, 'api'), store.readSection('plan-1', 2, 'api')); });
test('rejects ownership through repository symlinks', (t) => { const store = fixture(t); fs.symlinkSync(os.tmpdir(), path.join(store.root, 'src')); assert.throws(() => store.create(source()), /Unsafe symlink ownership/); });
test('invalidates approved dependents when an accepted prerequisite section changes', (t) => { const store = fixture(t); const dependent = source().replace('"id":"ui","paths":["src/ui/**"],"dependsOn":[]', '"id":"ui","paths":["src/ui/**"],"dependsOn":["api"]'); store.create(dependent); for (const id of ['shared', 'api', 'ui', 'global-validation']) store.approve('plan-1', 1, id); store.unlock('plan-1', 1, 'api'); const patch = `<!-- bdfl-plan-patch:{"schema":1,"planId":"plan-1","baseVersion":1} -->\n${chunk('api', 'Build a changed prerequisite.')}\n<!-- bdfl-plan-patch:end -->`; const revised = store.revise('plan-1', patch); assert.equal(revised.manifest.approvals.api, undefined); assert.equal(revised.manifest.approvals.ui, undefined); assert.ok(revised.manifest.approvals.shared); });
test('rejects plan IDs that could escape durable state', (t) => { const store = fixture(t); assert.throws(() => store.create(source(), { planId: '../outside' }), /Invalid plan ID/); });
test('historical approvals are isolated and can make an older immutable version executable', (t) => { const store = fixture(t); store.create(source()); const patch = `<!-- bdfl-plan-patch:{"schema":1,"planId":"plan-1","baseVersion":1} -->\n${chunk('ui', 'Build v2.')}\n<!-- bdfl-plan-patch:end -->`; store.revise('plan-1', patch); for (const id of ['shared', 'api', 'ui', 'global-validation']) store.approve('plan-1', 1, id); assert.equal(store.executable('plan-1', 1), true); assert.equal(store.readManifest('plan-1', 2).approvals.ui, undefined); store.removeApproval('plan-1', 1, 'shared'); assert.equal(store.readManifest('plan-1', 2).approvals.shared, undefined); });
test('changing Shared conservatively drops every carried approval', (t) => { const store = fixture(t); store.create(source()); for (const id of ['shared', 'api', 'ui', 'global-validation']) store.approve('plan-1', 1, id); store.removeApproval('plan-1', 1, 'shared'); const patch = '<!-- bdfl-plan-patch:{"schema":1,"planId":"plan-1","baseVersion":1} -->\n<!-- bdfl-shared:start -->\n## Shared decisions\nB.\n<!-- bdfl-shared:end -->\n<!-- bdfl-plan-patch:end -->'; const revised = store.revise('plan-1', patch); assert.deepEqual(revised.manifest.approvals, {}); });
