'use strict';
const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path'); const test = require('node:test'); const assert = require('node:assert/strict');
const { WorkspaceStore, defaultWorkspace, normalizeTaskSnippet } = require('../../src/state/workspace'); const { SessionManager, substantivePlanningPrompt } = require('../../src/sessions/manager');

function fixture(t) { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'bdfl-named-')); t.after(() => fs.rmSync(root, { recursive: true, force: true })); let number = 0; const store = new WorkspaceStore(root, { id: () => `${++number}`, now: () => new Date('2026-01-01T00:00:00.000Z') }); const config = { version: 1, delegatorProfile: { provider: 'claude', model: 'opus', effort: 'high' }, workerProfile: { provider: 'codex', model: 'gpt-5', effort: 'medium', permissionMode: 'workspace-write' }, workerCapacity: 5 }; return { root, store, config }; }

test('uses schema 2 for workspace and saved configuration and rejects development schema 1 state', (t) => { const { root, store, config } = fixture(t); assert.equal(defaultWorkspace().schema, 2); store.createWorkstream(config); assert.equal(JSON.parse(fs.readFileSync(path.join(root, '.bdfl/config.json'))).schema, 2); const oldWorkspace = { schema: 1, workstreams: [], sessions: [] }; fs.writeFileSync(path.join(root, '.bdfl/workspace.json'), JSON.stringify(oldWorkspace)); assert.throws(() => store.load(), (error) => error.code === 'RESET_REQUIRED' && /remove this repository's \.bdfl/.test(error.message)); fs.writeFileSync(path.join(root, '.bdfl/workspace.json'), JSON.stringify(defaultWorkspace())); fs.writeFileSync(path.join(root, '.bdfl/config.json'), JSON.stringify({ schema: 1 })); assert.throws(() => store.loadConfig(), (error) => error.code === 'RESET_REQUIRED'); });
test('assigns provider-local planning names and non-recycled worker names', (t) => { const { store, config } = fixture(t); const first = store.createWorkstream(config); const second = store.createWorkstream(config); const planningOne = store.createSession(first.id, 'delegator', config.delegatorProfile); const planningTwo = store.createSession(second.id, 'delegator', config.delegatorProfile); const workerOne = store.createSession(first.id, 'worker', config.workerProfile); const workerTwo = store.createSession(first.id, 'worker', config.workerProfile); store.closeWorkstream(first.id); store.reopenWorkstream(first.id); const workerThree = store.createSession(first.id, 'worker', config.workerProfile); assert.deepEqual([planningOne.name, planningTwo.name], ['Claude 1', 'Claude 2']); assert.deepEqual([workerOne.name, workerTwo.name, workerThree.name], ['W 1', 'W 2', 'W 3']); assert.deepEqual([workerOne.roleSequence, workerTwo.roleSequence, workerThree.roleSequence], [1, 2, 3]); });
test('renames exact sessions with printable length and case-insensitive workstream uniqueness', (t) => { const { store, config } = fixture(t); const stream = store.createWorkstream(config); const planning = store.createSession(stream.id, 'delegator', config.delegatorProfile); const worker = store.createSession(stream.id, 'worker', config.workerProfile); assert.equal(store.renameSession(planning.id, 'Lead Planner').name, 'Lead Planner'); assert.throws(() => store.renameSession(worker.id, 'lead planner'), /unique/); for (const invalid of ['', ' leading', 'trailing ', 'bad\nname', '1234567890123456789012345']) assert.throws(() => store.renameSession(worker.id, invalid), /1–24 printable/); assert.equal(store.load().sessions.find((session) => session.id === planning.id).name, 'Lead Planner'); });
test('normalizes snippets to one printable 200-character line and persists metadata through close and reopen', (t) => { const { store, config } = fixture(t); const stream = store.createWorkstream(config); const planning = store.createSession(stream.id, 'delegator', config.delegatorProfile); const raw = `  Build\n\t the\u001b rail ${'x'.repeat(250)}  `; const updated = store.setSessionTaskSnippet(planning.id, raw); assert.equal(updated.taskSnippet, normalizeTaskSnippet(raw)); assert.equal([...updated.taskSnippet].length, 200); store.setSessionAttention(planning.id, true); store.closeWorkstream(stream.id); store.reopenWorkstream(stream.id); const restored = store.load().sessions[0]; assert.equal(restored.name, 'Claude 1'); assert.equal(restored.taskSnippet, updated.taskSnippet); assert.equal(restored.roleSequence, 1); assert.equal(restored.attention, true); });
test('captures only substantive submitted planning prompts', (t) => { const { root, store, config } = fixture(t); const stream = store.createWorkstream(config); const session = store.createSession(stream.id, 'delegator', config.delegatorProfile); const writes = []; const child = { pid: 1, onData() {}, onExit() {}, write(value) { writes.push(value); }, kill() {} }; const manager = new SessionManager(root, store, { pty: { spawn() { return child; } } }); manager.open(session.id); manager.write(session.id, 'Please build'); manager.write(session.id, ' the named rail\r'); assert.equal(store.load().sessions[0].taskSnippet, 'Please build the named rail'); for (const ignored of ['yes\r', '/help\r', '\u0007\r', '   \r']) manager.write(session.id, ignored); assert.equal(store.load().sessions[0].taskSnippet, 'Please build the named rail'); assert.equal(substantivePlanningPrompt('okay'), null); assert.equal(substantivePlanningPrompt('Explain okay handling'), 'Explain okay handling'); assert.equal(writes.join(''), 'Please build the named rail\ryes\r/help\r\u0007\r   \r'); manager.shutdown(); });
